/**
 * Multi-strategy write-back for editable fields with post-write verification.
 * Includes framework-aware handling for Lexical/ProseMirror/Slate/Quill
 * contentEditable composers (ChatGPT, Claude, etc.) where synthetic DOM
 * mutation alone does not sync the editor's internal state. Event-only
 * dispatch with async poll lets the framework reconcile from the event,
 * while execCommand provides a native insertion path when available.
 *
 * Framework composers are written through their own input pipelines — the
 * Quill API, a synthetic Ctrl+V paste over a scripted selection, or (Draft.js)
 * the native insertText command — each attempt verified exactly, never stacked
 * on a half-applied edit.
 */
import {
  getElementText,
  isDraftOwnedEditor,
  isFocusedWithin,
  isFrameworkOwnedEditor,
} from './editable';

export { isDraftOwnedEditor, isFrameworkOwnedEditor };

export type WriteStrategyName =
  | 'execCommand+events'
  | 'execCommand-html'
  | 'ce-event-only'
  | 'insertText-events'
  | 'native-insert'
  | 'direct-assign'
  | 'framework-api'
  | 'synthetic-paste';

/**
 * Grace period between scripting a selection and pasting over it.
 *
 * Editors reconcile a scripted DOM selection asynchronously: Slate debounces
 * `selectionchange` by a task, React-based editors re-render before their
 * model sees it. Pasting in the same tick as the nudge made those editors use
 * their *stale* model selection — Slate dropped the paste entirely, Lexical
 * and Draft.js inserted the translation next to the draft instead of replacing
 * it (measured in Chromium against the real engines).
 */
const FRAMEWORK_SELECTION_SETTLE_MS = 50;

export type WriteFailureReason = 'framework-editor' | 'partial-change' | 'verify-failed';

export interface WriteBackResult {
  success: boolean;
  strategy?: WriteStrategyName;
  writtenText?: string;
  /** Why a failed write failed (drives the user-facing recovery path). */
  reason?: WriteFailureReason;
}

/**
 * Events this module dispatched itself.
 *
 * Real user input during a write-back must still cancel the in-flight request,
 * so cancellation cannot be gated on a coarse "we are writing" flag — it has to
 * ignore exactly the events we generated.
 */
const syntheticInlineEvents = new WeakSet<Event>();

/** Whether an event was generated by inline-translate write-back. */
export function isSyntheticInlineEvent(event: Event): boolean {
  return syntheticInlineEvents.has(event);
}

function dispatchInlineEvent(target: EventTarget, event: Event): boolean {
  syntheticInlineEvents.add(event);
  return target.dispatchEvent(event);
}

/**
 * Dual-mode join: input uses " / " separator; textarea/CE uses newline.
 */
export function joinDualMode(
  original: string,
  translation: string,
  el: HTMLElement,
): string {
  const isSingleLine =
    el instanceof HTMLInputElement ||
    (el instanceof HTMLTextAreaElement === false &&
      el.getAttribute('aria-multiline') !== 'true' &&
      !el.isContentEditable);
  // textarea and contentEditable → multiline
  if (el instanceof HTMLTextAreaElement || el.isContentEditable || el.contentEditable === 'true') {
    return `${original}\n${translation}`;
  }
  if (isSingleLine || el instanceof HTMLInputElement) {
    return `${original} / ${translation}`;
  }
  return `${original}\n${translation}`;
}

function setNativeInputValue(el: HTMLInputElement | HTMLTextAreaElement, value: string): void {
  const proto = el instanceof HTMLInputElement
    ? window.HTMLInputElement.prototype
    : window.HTMLTextAreaElement.prototype;
  const descriptor = Object.getOwnPropertyDescriptor(proto, 'value');
  const setter = descriptor?.set;

  const trackerHolder = el as unknown as {
    _valueTracker?: { setValue: (v: string) => void; getValue?: () => string };
  };
  const tracker = trackerHolder._valueTracker;
  if (tracker && typeof tracker.setValue === 'function') {
    tracker.setValue('');
  }

  if (setter) {
    setter.call(el, value);
  } else {
    el.value = value;
  }
}

function isContentEditableTarget(el: HTMLElement): boolean {
  return el.isContentEditable || el.contentEditable === 'true' || !(el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement);
}

function waitMs(ms: number): Promise<void> {
  const { promise, resolve } = Promise.withResolvers<undefined>();
  setTimeout(() => resolve(undefined), ms);
  return promise;
}


function isVitestEnv(): boolean {
  return typeof process !== 'undefined' && typeof process.env === 'object' && (process.env as Record<string, string>).VITEST === 'true';
}

async function pollVerify(el: HTMLElement, expected: string, timeoutMs = 160, intervalMs = 20): Promise<boolean> {
  if (verifyWrite(el, expected)) return true;
  if (isVitestEnv()) return false;
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    await waitMs(intervalMs);
    if (verifyWrite(el, expected)) return true;
  }
  return false;
}

async function waitForStableVerify(el: HTMLElement, expected: string, timeoutMs = 120): Promise<boolean> {
  if (isVitestEnv()) return verifyWrite(el, expected);
  if (!(await pollVerify(el, expected, timeoutMs))) return false;
  await waitMs(40);
  return verifyWrite(el, expected);
}


function dispatchInputEvents(el: HTMLElement, data: string, includeBeforeInput = true): void {
  if (includeBeforeInput) {
    try {
      const before = new InputEvent('beforeinput', {
        bubbles: true,
        cancelable: true,
        inputType: 'insertText',
        data,
      });
      dispatchInlineEvent(el, before);
    } catch {
      // InputEvent may be incomplete in jsdom
    }
  }
  try {
    dispatchInlineEvent(
      el,
      new InputEvent('input', {
        bubbles: true,
        inputType: 'insertText',
        data,
      }),
    );
  } catch {
    dispatchInlineEvent(el, new Event('input', { bubbles: true }));
  }
  dispatchInlineEvent(el, new Event('change', { bubbles: true }));
}

function dispatchBeforeInput(el: HTMLElement, data: string): boolean {
  try {
    const ev = new InputEvent('beforeinput', {
      bubbles: true,
      cancelable: true,
      inputType: 'insertText',
      data,
    });
    dispatchInlineEvent(el, ev);
    return ev.defaultPrevented;
  } catch {
    return false;
  }
}

function dispatchInputOnly(el: HTMLElement, data: string): void {
  try {
    dispatchInlineEvent(
      el,
      new InputEvent('input', { bubbles: true, inputType: 'insertText', data }),
    );
  } catch {
    dispatchInlineEvent(el, new Event('input', { bubbles: true }));
  }
  dispatchInlineEvent(el, new Event('change', { bubbles: true }));
}

/** Shared select-all mechanics; focus policy is the caller's job. */
function selectContents(el: HTMLElement): void {
  if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) {
    el.select();
    try {
      el.setSelectionRange(0, el.value.length);
    } catch {
      // Some input types (e.g. email/number in some browsers) throw on setSelectionRange
    }
    return;
  }
  const sel = el.ownerDocument?.defaultView?.getSelection() ?? window.getSelection();
  if (sel) {
    const range = (el.ownerDocument ?? document).createRange();
    range.selectNodeContents(el);
    sel.removeAllRanges();
    sel.addRange(range);
  }
}

/**
 * Select the whole field *without stealing focus*.
 * Returns false when the field is not focused — selection-based strategies
 * cannot work then, and focusing would yank the user back from wherever they
 * moved on to while the translation was in flight.
 */
function selectAll(el: HTMLElement): boolean {
  if (!isFocusedWithin(el)) return false;
  el.focus();
  selectContents(el);
  return true;
}

/**
 * Focus the field and select its whole contents.
 *
 * Used by the copy panel's "copy & select" flow: the draft is selected so a
 * real user paste (Ctrl+V/⌘V) replaces it through the editor's own pipeline —
 * the one write path that works on every framework composer. The click is
 * user-initiated, so taking focus is intended here.
 *
 * contentEditable uses the same text-range selection the paste path relies on
 * (see selectWholeFieldForPaste): an element-boundary selection is ignored by
 * Lexical/Slate/Draft, so the user's paste would land at their stale caret
 * instead of replacing the draft. Inputs/textarea keep the plain select-all.
 */
export function focusAndSelectContents(el: HTMLElement): boolean {
  if (!el.isConnected) return false;
  try {
    if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) {
      el.focus();
      selectContents(el);
      return true;
    }
    return selectWholeFieldForPaste(el);
  } catch {
    return false;
  }
}

function collapseSelectionAtEnd(el: HTMLElement): void {
  if (!isFocusedWithin(el)) return;
  el.focus();
  if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) {
    const end = el.value.length;
    try {
      el.setSelectionRange(end, end);
    } catch {
      // Some input types do not expose a text selection range.
    }
    return;
  }

  const selection = el.ownerDocument?.defaultView?.getSelection() ?? window.getSelection();
  if (!selection) return;
  const range = (el.ownerDocument ?? document).createRange();
  range.selectNodeContents(el);
  range.collapse(false);
  selection.removeAllRanges();
  selection.addRange(range);
}

/** Insert text into the current DOM selection (plain contentEditable only). */
function insertTextIntoSelection(el: HTMLElement, text: string): void {
  const sel = el.ownerDocument?.defaultView?.getSelection() ?? window.getSelection();
  if (sel && sel.rangeCount > 0) {
    const range = sel.getRangeAt(0);
    range.deleteContents();
    const textNode = (el.ownerDocument ?? document).createTextNode(text);
    range.insertNode(textNode);
    range.selectNodeContents(textNode);
    range.collapse(false);
    sel.removeAllRanges();
    sel.addRange(range);
  } else {
    el.textContent = text;
  }
  collapseSelectionAtEnd(el);
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function strategyExecCommand(el: HTMLElement, text: string): boolean {
  const hasExec = typeof document.execCommand === 'function';
  if (!hasExec) return false;
  if (!selectAll(el)) return false;
  const ok = document.execCommand('insertText', false, text);
  if (!ok) return false;
  if (isContentEditableTarget(el)) {
    collapseSelectionAtEnd(el);
  } else {
    dispatchInputEvents(el, text, false);
  }
  return true;
}

function strategyExecCommandHtml(el: HTMLElement, text: string): boolean {
  const isCe = isContentEditableTarget(el);
  if (!isCe) return false;
  const hasExec = typeof document.execCommand === 'function';
  if (!hasExec) return false;
  if (!selectAll(el)) return false;
  const html = escapeHtml(text).replace(/\n/g, '<br>');
  const ok = document.execCommand('insertHTML', false, html);
  if (!ok) return false;
  collapseSelectionAtEnd(el);
  return true;
}


/**
 * contentEditable event path.
 *
 * `beforeinput` is the only event model-driven editors honour, and a *prevented*
 * `beforeinput` means the editor already applied the change itself — dispatching
 * `input` afterwards made Lexical insert the text twice (measured). When the
 * event is not prevented, no editor is listening and the plain DOM insertion is
 * safe.
 */
async function strategyCeEventOnly(el: HTMLElement, text: string): Promise<boolean> {
  if (!isContentEditableTarget(el)) return false;
  if (!selectAll(el)) return false;
  const prevented = dispatchBeforeInput(el, text);
  if (prevented) {
    // Editor owns the DOM from here; give it a tick to reconcile, then verify.
    await waitMs(0);
    return pollVerify(el, text, 160, 20);
  }
  insertTextIntoSelection(el, text);
  dispatchInputOnly(el, text);
  return pollVerify(el, text, 160, 20);
}

/** Replace the whole value of an input/textarea through the native setter. */
function strategyDirectAssign(el: HTMLElement, text: string): boolean {
  if (!(el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement)) return false;
  setNativeInputValue(el, text);
  dispatchInputEvents(el, text, true);
  // Also dispatch compositionend for IME-sensitive editors
  try {
    dispatchInlineEvent(el, new CompositionEvent('compositionend', { bubbles: true, data: text }));
  } catch {
    // Composition events are optional for non-IME editors.
  }
  return true;
}

interface QuillLike {
  setText(text: string): unknown;
  getText(index?: number, length?: number): string;
  getLength?(): number;
  setSelection?(index: number, length?: number): unknown;
}

/**
 * Quill keeps its editor instance on the `.ql-container` element as `__quill`
 * (the same lookup `Quill.find` performs). Walk ancestors so custom wrappers
 * around the container still resolve.
 */
function findQuillInstance(el: HTMLElement): QuillLike | null {
  if (!el.classList.contains('ql-editor')) return null;
  let node: HTMLElement | null = el;
  for (let depth = 0; node && depth < 8; depth += 1) {
    const candidate = (node as HTMLElement & { __quill?: unknown }).__quill;
    if (
      candidate != null &&
      typeof candidate === 'object' &&
      typeof (candidate as QuillLike).setText === 'function' &&
      typeof (candidate as QuillLike).getText === 'function'
    ) {
      return candidate as QuillLike;
    }
    node = node.parentElement;
  }
  return null;
}

/**
 * Write through a framework editor's own API — currently Quill (`setText`
 * goes through Quill's model, so DOM and internal state stay in sync and the
 * change lands in the editor's undo history, unlike DOM-level writes which
 * Quill's mutation reconciliation can mangle).
 *
 * Refusal result when no usable API is exposed or the write does not verify —
 * callers then fall back to the copy panel exactly as before.
 */
function frameworkApiWrite(el: HTMLElement, text: string): WriteBackResult {
  const quill = findQuillInstance(el);
  if (!quill) return { success: false, reason: 'framework-editor' };

  try {
    quill.setText(text);
    // Caret to the end so the next keystroke lands after the translation.
    if (typeof quill.getLength === 'function' && typeof quill.setSelection === 'function') {
      try {
        quill.setSelection(Math.max(0, quill.getLength() - 1), 0);
      } catch {
        // Selection is a nicety — never fail the write over it.
      }
    }
  } catch {
    return { success: false, reason: 'framework-editor' };
  }

  // Prefer the editor's own model for verification (exact for interior blank
  // lines our DOM reader collapses); fall back to the DOM read.
  const modelMatches = (() => {
    try {
      return quill.getText().replace(/\n+$/, '') === text;
    } catch {
      return false;
    }
  })();
  if (modelMatches || verifyWrite(el, text)) {
    return { success: true, strategy: 'framework-api', writtenText: text };
  }
  return { success: false, reason: 'framework-editor' };
}

/**
 * Verify a write with an exact text comparison (no `trim()` — the previous
 * trim-based fallback reported success while the field was unchanged whenever
 * the only difference was surrounding whitespace, measured on a live
 * ProseMirror composer). contentEditable additionally compares through the
 * block-aware reader's newline normalization.
 */
export function verifyWrite(el: HTMLElement, expected: string): boolean {
  const toLf = (text: string) => text.replace(/\r\n/g, '\n');
  const current = getElementText(el);
  if (toLf(current) === toLf(expected)) return true;
  if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) return false;
  // The block-aware reader collapses runs of block-boundary newlines, so a
  // translation that keeps a blank line between paragraphs — rendered by the
  // editor as an empty block — can never match exactly (measured on Quill,
  // Lexical, ProseMirror, CKEditor 5 and TinyMCE). Compare through the
  // reader's own normalization instead of reporting a copy-panel fallback
  // over a correctly written draft.
  const collapseBlankLines = (text: string) => toLf(text).replace(/\n{2,}/g, '\n');
  return collapseBlankLines(current) === collapseBlankLines(expected);
}

function isTextControl(el: HTMLElement): el is HTMLInputElement | HTMLTextAreaElement {
  return el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement;
}

/** First and last non-empty text nodes under `el`, in document order. */
function firstAndLastTextNode(el: HTMLElement, doc: Document): {
  first: Text | null;
  last: Text | null;
} {
  let first: Text | null = null;
  let last: Text | null = null;
  try {
    const walker = doc.createTreeWalker(el, NodeFilter.SHOW_TEXT);
    let node = walker.nextNode();
    while (node) {
      const text = node as Text;
      if (text.nodeValue && text.nodeValue.length > 0) {
        if (!first) first = text;
        last = text;
      }
      node = walker.nextNode();
    }
  } catch {
    // TreeWalker unavailable — fall back to an element-boundary selection.
  }
  return { first, last };
}

/**
 * Select the whole editor the way framework editors actually adopt: a range
 * over the field's *text*, plus a `selectionchange` event.
 *
 * Measured in Chromium against the real engines (prosemirror-view, Lexical,
 * Slate, Draft.js, Quill, CKEditor 5, TinyMCE): the endpoint *shape* decides
 * whether the editor adopts the selection at all. A range whose endpoints are
 * the editable element itself (`setBaseAndExtent` / `selectNodeContents` /
 * `execCommand('selectAll')`) is ignored by Lexical and Draft.js — their paste
 * then lands at the stale model selection and the draft survives alongside the
 * translation — while a range from the first to the last text node is adopted
 * by every measured editor. `execCommand('selectAll')` is still available as a
 * rescue attempt (see strategySyntheticPaste), never as the primary path: on
 * ProseMirror it can exclude trailing whitespace and leave residue.
 */
function selectWholeFieldForPaste(el: HTMLElement): boolean {
  if (!isFocusedWithin(el)) return false;
  el.focus();
  const doc = el.ownerDocument ?? document;
  const sel = doc.defaultView?.getSelection?.() ?? window.getSelection();
  if (!sel) return false;
  try {
    const range = doc.createRange();
    const { first, last } = firstAndLastTextNode(el, doc);
    if (first && last) {
      range.setStart(first, 0);
      range.setEnd(last, (last.nodeValue ?? '').length);
    } else {
      // Empty field: nothing to read, and the paste replaces nothing anyway.
      range.selectNodeContents(el);
    }
    sel.removeAllRanges();
    sel.addRange(range);
  } catch {
    return false;
  }
  // Nudge editors to adopt the selection before the paste lands.
  try {
    dispatchInlineEvent(doc, new Event('selectionchange'));
  } catch {
    // Engines that reject synthetic document events — paste still goes out.
  }
  return true;
}

/**
 * Rescue selection for editors that only adopt the browser's own select-all
 * command (measured: Lexical with an element-boundary range). Same
 * `selectionchange` nudge, so the editor can pull the selection into its model.
 */
function selectAllForPaste(el: HTMLElement): boolean {
  if (!isFocusedWithin(el)) return false;
  const doc = el.ownerDocument ?? document;
  if (typeof doc.execCommand !== 'function') return false;
  el.focus();
  let selected: boolean;
  try {
    selected = doc.execCommand('selectAll');
  } catch {
    return false;
  }
  if (!selected) return false;
  try {
    dispatchInlineEvent(doc, new Event('selectionchange'));
  } catch {
    // Engines that reject synthetic document events — paste still goes out.
  }
  return true;
}

/**
 * Simulate the exact event a real Ctrl+V produces: a `paste` ClipboardEvent
 * carrying `text/plain` in a script-built DataTransfer, dispatched over the
 * selected draft. Editors apply pastes through their own clipboard pipeline —
 * the one write path they never fight (the copy panel's manual flow relies on
 * the same fact) — and per the Clipboard spec a synthetic event's data store
 * contains exactly the data the script added, so a compliant editor handler
 * cannot tell it from a user paste. The system clipboard is never touched and
 * no clipboard permission is needed.
 *
 * Framework editors reconcile asynchronously, so success is decided solely by
 * exact verification of the field content, never by the event outcome.
 */
async function strategySyntheticPaste(el: HTMLElement, text: string): Promise<WriteBackResult> {
  // jsdom and older engines lack the constructors — nothing to simulate with.
  if (typeof DataTransfer !== 'function' || typeof ClipboardEvent !== 'function') {
    return { success: false, reason: 'framework-editor' };
  }

  const before = getElementText(el);
  // The scripted range first; the browser's own select-all as a rescue for
  // editors that ignore it. Every attempt is verified before the next one runs.
  for (const select of [selectWholeFieldForPaste, selectAllForPaste]) {
    // A half-applied edit must never get another strategy stacked on it.
    if (getElementText(el) !== before) return { success: false, reason: 'partial-change' };
    try {
      if (!select(el)) continue;
      // Let the editor pull the selection into its model before pasting over it.
      await waitMs(FRAMEWORK_SELECTION_SETTLE_MS);
      const data = new DataTransfer();
      data.setData('text/plain', text);
      const paste = new ClipboardEvent('paste', {
        clipboardData: data,
        bubbles: true,
        cancelable: true,
        composed: true,
      });
      dispatchInlineEvent(el, paste);
      if (await waitForStableVerify(el, text, 500)) {
        return { success: true, strategy: 'synthetic-paste', writtenText: text };
      }
    } catch {
      // Try the next selection strategy.
    }
  }

  if (getElementText(el) !== before) return { success: false, reason: 'partial-change' };
  return { success: false, reason: 'framework-editor' };
}

/**
 * Draft.js write path: the browser's native `insertText` command.
 *
 * A synthetic paste cannot replace a Draft draft: Draft never adopts a
 * scripted DOM selection into its EditorState (measured 3/3 in Chromium —
 * `selectionchange` fires, React's `onSelect` runs, the model selection stays
 * put), so its paste handler inserts the translation at the stale model
 * selection and the draft survives next to it. Draft *does* apply the native
 * `insertText` command through its own beforeinput handling, which maps the
 * DOM selection into the model: measured 3/3 exact replace with the model kept
 * in sync (single- and multi-paragraph).
 */
async function strategyNativeInsertText(el: HTMLElement, text: string): Promise<boolean> {
  const doc = el.ownerDocument ?? document;
  if (typeof doc.execCommand !== 'function') return false;
  if (!selectWholeFieldForPaste(el)) return false;
  await waitMs(FRAMEWORK_SELECTION_SETTLE_MS);
  try {
    if (!doc.execCommand('insertText', false, text)) return false;
  } catch {
    return false;
  }
  return waitForStableVerify(el, text, 500);
}

/**
 * Write text into an editable element using a strategy chain with verification.
 *
 * Framework-owned composers go editor-native API first, then synthetic paste,
 * and are refused (see isFrameworkOwnedEditor) only when neither verifies; the
 * chain stops as soon as the field content changes without matching — stacking
 * another strategy on a half-applied edit is what corrupted drafts.
 */
export function writeElementText(el: HTMLElement, text: string): WriteBackResult {
  if (isFrameworkOwnedEditor(el)) return frameworkApiWrite(el, text);

  const before = getElementText(el);
  const strategies: Array<{ name: WriteStrategyName; run: () => boolean }> = isTextControl(el)
    ? [
        { name: 'execCommand+events', run: () => strategyExecCommand(el, text) },
        { name: 'direct-assign', run: () => strategyDirectAssign(el, text) },
      ]
    : [
        { name: 'execCommand+events', run: () => strategyExecCommand(el, text) },
        { name: 'execCommand-html', run: () => strategyExecCommandHtml(el, text) },
        {
          name: 'insertText-events',
          run: () => {
            if (!selectAll(el)) return false;
            if (dispatchBeforeInput(el, text)) return false; // editor took over — never double-apply
            insertTextIntoSelection(el, text);
            dispatchInputOnly(el, text);
            return true;
          },
        },
      ];

  for (const s of strategies) {
    if (getElementText(el) !== before) return { success: false, reason: 'partial-change' };
    try {
      if (!s.run()) continue;
      if (verifyWrite(el, text)) {
        return { success: true, strategy: s.name, writtenText: text };
      }
    } catch {
      // try next
    }
  }

  if (getElementText(el) !== before) return { success: false, reason: 'partial-change' };
  return { success: false, reason: 'verify-failed' };
}

/**
 * Async variant with framework-aware polling for contentEditable editors.
 * Uses the same sync strategies plus a dedicated CE event-only async step
 * and post-write stability check to avoid claiming success when an editor
 * reverts a manual mutation.
 */
export async function writeElementTextAsync(el: HTMLElement, text: string): Promise<WriteBackResult> {
  if (isFrameworkOwnedEditor(el)) {
    // Editor-native API first (Quill today): exact write through the editor's
    // own model, lands in its undo history.
    const viaApi = frameworkApiWrite(el, text);
    if (viaApi.success) return viaApi;

    // Draft.js never adopts a scripted selection, so its paste path would
    // corrupt the draft (see strategyNativeInsertText) — native command only.
    if (isDraftOwnedEditor(el)) {
      const before = getElementText(el);
      if (await strategyNativeInsertText(el, text)) {
        return { success: true, strategy: 'native-insert', writtenText: text };
      }
      if (getElementText(el) !== before) {
        return { success: false, reason: 'partial-change' };
      }
      return { success: false, reason: 'framework-editor' };
    }

    // Then the one input every framework editor honours: a paste through its
    // own clipboard pipeline — synthetic Ctrl+V over the selected draft.
    return strategySyntheticPaste(el, text);
  }

  const before = getElementText(el);

  // Fast path for inputs: immediate sync strategies are sufficient
  if (isTextControl(el)) {
    const sync = writeElementText(el, text);
    if (sync.success) return sync;
    // Fallback with poll (React may batch)
    if (await pollVerify(el, text)) return { success: true, strategy: 'direct-assign', writtenText: text };
    return getElementText(el) !== before
      ? { success: false, reason: 'partial-change' }
      : { success: false, reason: 'verify-failed' };
  }

  const steps: Array<{ name: WriteStrategyName; run: () => Promise<boolean> }> = [
    {
      name: 'execCommand+events',
      run: async () => strategyExecCommand(el, text) && (await waitForStableVerify(el, text)),
    },
    {
      name: 'execCommand-html',
      run: async () => strategyExecCommandHtml(el, text) && (await waitForStableVerify(el, text)),
    },
    {
      name: 'ce-event-only',
      run: async () => (await strategyCeEventOnly(el, text)) && (await waitForStableVerify(el, text)),
    },
  ];

  for (const step of steps) {
    if (getElementText(el) !== before) return { success: false, reason: 'partial-change' };
    try {
      if (await step.run()) {
        return { success: true, strategy: step.name, writtenText: text };
      }
    } catch {
      // try next
    }
  }

  if (getElementText(el) !== before) return { success: false, reason: 'partial-change' };
  return { success: false, reason: 'verify-failed' };
}

/**
 * Legacy-compatible replace used by older tests — delegates to write pipeline.
 */
export function replaceElementText(el: HTMLElement, newText: string): void {
  writeElementText(el, newText);
}
