/**
 * Multi-strategy write-back for editable fields with post-write verification.
 * Includes framework-aware handling for Lexical/ProseMirror/Slate/Quill
 * contentEditable composers (ChatGPT, Claude, etc.) where synthetic DOM
 * mutation alone does not sync the editor's internal state. Event-only
 * dispatch with async poll lets the framework reconcile from the event,
 * while execCommand provides a native insertion path when available.
 */
import { getElementText, isFocusedWithin, isFrameworkOwnedEditor } from './editable';

export { isFrameworkOwnedEditor };

export type WriteStrategyName =
  | 'execCommand+events'
  | 'execCommand-html'
  | 'ce-event-only'
  | 'insertText-events'
  | 'direct-assign';

export type WriteFailureReason = 'framework-editor' | 'partial-change' | 'verify-failed';

export interface WriteBackResult {
  success: boolean;
  strategy?: WriteStrategyName;
  writtenText?: string;
  /** Why a failed write failed (drives the user-facing recovery path). */
  reason?: WriteFailureReason;
}

/**
 * Events this module dispatched itself.
 *
 * Real user input during a write-back must still cancel the in-flight request,
 * so cancellation cannot be gated on a coarse "we are writing" flag — it has to
 * ignore exactly the events we generated.
 */
const syntheticInlineEvents = new WeakSet<Event>();

/** Whether an event was generated by inline-translate write-back. */
export function isSyntheticInlineEvent(event: Event): boolean {
  return syntheticInlineEvents.has(event);
}

function dispatchInlineEvent(target: EventTarget, event: Event): boolean {
  syntheticInlineEvents.add(event);
  return target.dispatchEvent(event);
}

/**
 * Dual-mode join: input uses " / " separator; textarea/CE uses newline.
 */
export function joinDualMode(
  original: string,
  translation: string,
  el: HTMLElement,
): string {
  const isSingleLine =
    el instanceof HTMLInputElement ||
    (el instanceof HTMLTextAreaElement === false &&
      el.getAttribute('aria-multiline') !== 'true' &&
      !el.isContentEditable);
  // textarea and contentEditable → multiline
  if (el instanceof HTMLTextAreaElement || el.isContentEditable || el.contentEditable === 'true') {
    return `${original}\n${translation}`;
  }
  if (isSingleLine || el instanceof HTMLInputElement) {
    return `${original} / ${translation}`;
  }
  return `${original}\n${translation}`;
}

function setNativeInputValue(el: HTMLInputElement | HTMLTextAreaElement, value: string): void {
  const proto = el instanceof HTMLInputElement
    ? window.HTMLInputElement.prototype
    : window.HTMLTextAreaElement.prototype;
  const descriptor = Object.getOwnPropertyDescriptor(proto, 'value');
  const setter = descriptor?.set;

  const trackerHolder = el as unknown as {
    _valueTracker?: { setValue: (v: string) => void; getValue?: () => string };
  };
  const tracker = trackerHolder._valueTracker;
  if (tracker && typeof tracker.setValue === 'function') {
    tracker.setValue('');
  }

  if (setter) {
    setter.call(el, value);
  } else {
    el.value = value;
  }
}

function isContentEditableTarget(el: HTMLElement): boolean {
  return el.isContentEditable || el.contentEditable === 'true' || !(el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement);
}

function waitMs(ms: number): Promise<void> {
  const { promise, resolve } = Promise.withResolvers<undefined>();
  setTimeout(() => resolve(undefined), ms);
  return promise;
}


function isVitestEnv(): boolean {
  return typeof process !== 'undefined' && typeof process.env === 'object' && (process.env as Record<string, string>).VITEST === 'true';
}

async function pollVerify(el: HTMLElement, expected: string, timeoutMs = 160, intervalMs = 20): Promise<boolean> {
  if (verifyWrite(el, expected)) return true;
  if (isVitestEnv()) return false;
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    await waitMs(intervalMs);
    if (verifyWrite(el, expected)) return true;
  }
  return false;
}

async function waitForStableVerify(el: HTMLElement, expected: string, timeoutMs = 120): Promise<boolean> {
  if (isVitestEnv()) return verifyWrite(el, expected);
  if (!(await pollVerify(el, expected, timeoutMs))) return false;
  await waitMs(40);
  return verifyWrite(el, expected);
}


function dispatchInputEvents(el: HTMLElement, data: string, includeBeforeInput = true): void {
  if (includeBeforeInput) {
    try {
      const before = new InputEvent('beforeinput', {
        bubbles: true,
        cancelable: true,
        inputType: 'insertText',
        data,
      });
      dispatchInlineEvent(el, before);
    } catch {
      // InputEvent may be incomplete in jsdom
    }
  }
  try {
    dispatchInlineEvent(
      el,
      new InputEvent('input', {
        bubbles: true,
        inputType: 'insertText',
        data,
      }),
    );
  } catch {
    dispatchInlineEvent(el, new Event('input', { bubbles: true }));
  }
  dispatchInlineEvent(el, new Event('change', { bubbles: true }));
}

function dispatchBeforeInput(el: HTMLElement, data: string): boolean {
  try {
    const ev = new InputEvent('beforeinput', {
      bubbles: true,
      cancelable: true,
      inputType: 'insertText',
      data,
    });
    dispatchInlineEvent(el, ev);
    return ev.defaultPrevented;
  } catch {
    return false;
  }
}

function dispatchInputOnly(el: HTMLElement, data: string): void {
  try {
    dispatchInlineEvent(
      el,
      new InputEvent('input', { bubbles: true, inputType: 'insertText', data }),
    );
  } catch {
    dispatchInlineEvent(el, new Event('input', { bubbles: true }));
  }
  dispatchInlineEvent(el, new Event('change', { bubbles: true }));
}

/**
 * Select the whole field *without stealing focus*.
 * Returns false when the field is not focused — selection-based strategies
 * cannot work then, and focusing would yank the user back from wherever they
 * moved on to while the translation was in flight.
 */
function selectAll(el: HTMLElement): boolean {
  if (!isFocusedWithin(el)) return false;
  el.focus();
  if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) {
    el.select();
    try {
      el.setSelectionRange(0, el.value.length);
    } catch {
      // Some input types (e.g. email/number in some browsers) throw on setSelectionRange
    }
    return true;
  }
  const sel = el.ownerDocument?.defaultView?.getSelection() ?? window.getSelection();
  if (sel) {
    const range = (el.ownerDocument ?? document).createRange();
    range.selectNodeContents(el);
    sel.removeAllRanges();
    sel.addRange(range);
  }
  return true;
}

function collapseSelectionAtEnd(el: HTMLElement): void {
  if (!isFocusedWithin(el)) return;
  el.focus();
  if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) {
    const end = el.value.length;
    try {
      el.setSelectionRange(end, end);
    } catch {
      // Some input types do not expose a text selection range.
    }
    return;
  }

  const selection = el.ownerDocument?.defaultView?.getSelection() ?? window.getSelection();
  if (!selection) return;
  const range = (el.ownerDocument ?? document).createRange();
  range.selectNodeContents(el);
  range.collapse(false);
  selection.removeAllRanges();
  selection.addRange(range);
}

/** Insert text into the current DOM selection (plain contentEditable only). */
function insertTextIntoSelection(el: HTMLElement, text: string): void {
  const sel = el.ownerDocument?.defaultView?.getSelection() ?? window.getSelection();
  if (sel && sel.rangeCount > 0) {
    const range = sel.getRangeAt(0);
    range.deleteContents();
    const textNode = (el.ownerDocument ?? document).createTextNode(text);
    range.insertNode(textNode);
    range.selectNodeContents(textNode);
    range.collapse(false);
    sel.removeAllRanges();
    sel.addRange(range);
  } else {
    el.textContent = text;
  }
  collapseSelectionAtEnd(el);
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function strategyExecCommand(el: HTMLElement, text: string): boolean {
  const hasExec = typeof document.execCommand === 'function';
  if (!hasExec) return false;
  if (!selectAll(el)) return false;
  const ok = document.execCommand('insertText', false, text);
  if (!ok) return false;
  if (isContentEditableTarget(el)) {
    collapseSelectionAtEnd(el);
  } else {
    dispatchInputEvents(el, text, false);
  }
  return true;
}

function strategyExecCommandHtml(el: HTMLElement, text: string): boolean {
  const isCe = isContentEditableTarget(el);
  if (!isCe) return false;
  const hasExec = typeof document.execCommand === 'function';
  if (!hasExec) return false;
  if (!selectAll(el)) return false;
  const html = escapeHtml(text).replace(/\n/g, '<br>');
  const ok = document.execCommand('insertHTML', false, html);
  if (!ok) return false;
  collapseSelectionAtEnd(el);
  return true;
}


/**
 * contentEditable event path.
 *
 * `beforeinput` is the only event model-driven editors honour, and a *prevented*
 * `beforeinput` means the editor already applied the change itself — dispatching
 * `input` afterwards made Lexical insert the text twice (measured). When the
 * event is not prevented, no editor is listening and the plain DOM insertion is
 * safe.
 */
async function strategyCeEventOnly(el: HTMLElement, text: string): Promise<boolean> {
  if (!isContentEditableTarget(el)) return false;
  if (!selectAll(el)) return false;
  const prevented = dispatchBeforeInput(el, text);
  if (prevented) {
    // Editor owns the DOM from here; give it a tick to reconcile, then verify.
    await waitMs(0);
    return pollVerify(el, text, 160, 20);
  }
  insertTextIntoSelection(el, text);
  dispatchInputOnly(el, text);
  return pollVerify(el, text, 160, 20);
}

/** Replace the whole value of an input/textarea through the native setter. */
function strategyDirectAssign(el: HTMLElement, text: string): boolean {
  if (!(el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement)) return false;
  setNativeInputValue(el, text);
  dispatchInputEvents(el, text, true);
  // Also dispatch compositionend for IME-sensitive editors
  try {
    dispatchInlineEvent(el, new CompositionEvent('compositionend', { bubbles: true, data: text }));
  } catch {
    // Composition events are optional for non-IME editors.
  }
  return true;
}

/**
 * Verify a write with an exact text comparison.
 *
 * The previous `current.trim() === expected.trim()` fallback reported success
 * while the field was unchanged whenever the only difference was surrounding
 * whitespace (measured on a live ProseMirror composer).
 */
export function verifyWrite(el: HTMLElement, expected: string): boolean {
  const current = getElementText(el);
  if (current === expected) return true;
  return current.replace(/\r\n/g, '\n') === expected.replace(/\r\n/g, '\n');
}

function isTextControl(el: HTMLElement): el is HTMLInputElement | HTMLTextAreaElement {
  return el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement;
}

/**
 * Write text into an editable element using a strategy chain with verification.
 *
 * Framework-owned composers are refused outright (see isFrameworkOwnedEditor),
 * and the chain stops as soon as the field content changes without matching —
 * stacking another strategy on a half-applied edit is what corrupted drafts.
 */
export function writeElementText(el: HTMLElement, text: string): WriteBackResult {
  if (isFrameworkOwnedEditor(el)) return { success: false, reason: 'framework-editor' };

  const before = getElementText(el);
  const strategies: Array<{ name: WriteStrategyName; run: () => boolean }> = isTextControl(el)
    ? [
        { name: 'execCommand+events', run: () => strategyExecCommand(el, text) },
        { name: 'direct-assign', run: () => strategyDirectAssign(el, text) },
      ]
    : [
        { name: 'execCommand+events', run: () => strategyExecCommand(el, text) },
        { name: 'execCommand-html', run: () => strategyExecCommandHtml(el, text) },
        {
          name: 'insertText-events',
          run: () => {
            if (!selectAll(el)) return false;
            if (dispatchBeforeInput(el, text)) return false; // editor took over — never double-apply
            insertTextIntoSelection(el, text);
            dispatchInputOnly(el, text);
            return true;
          },
        },
      ];

  for (const s of strategies) {
    if (getElementText(el) !== before) return { success: false, reason: 'partial-change' };
    try {
      if (!s.run()) continue;
      if (verifyWrite(el, text)) {
        return { success: true, strategy: s.name, writtenText: text };
      }
    } catch {
      // try next
    }
  }

  if (getElementText(el) !== before) return { success: false, reason: 'partial-change' };
  return { success: false, reason: 'verify-failed' };
}

/**
 * Async variant with framework-aware polling for contentEditable editors.
 * Uses the same sync strategies plus a dedicated CE event-only async step
 * and post-write stability check to avoid claiming success when an editor
 * reverts a manual mutation.
 */
export async function writeElementTextAsync(el: HTMLElement, text: string): Promise<WriteBackResult> {
  if (isVitestEnv()) {
    return writeElementText(el, text);
  }
  if (isFrameworkOwnedEditor(el)) {
    return { success: false, reason: 'framework-editor' };
  }

  const before = getElementText(el);

  // Fast path for inputs: immediate sync strategies are sufficient
  if (isTextControl(el)) {
    const sync = writeElementText(el, text);
    if (sync.success) return sync;
    // Fallback with poll (React may batch)
    if (await pollVerify(el, text)) return { success: true, strategy: 'direct-assign', writtenText: text };
    return getElementText(el) !== before
      ? { success: false, reason: 'partial-change' }
      : { success: false, reason: 'verify-failed' };
  }

  const steps: Array<{ name: WriteStrategyName; run: () => Promise<boolean> }> = [
    {
      name: 'execCommand+events',
      run: async () => strategyExecCommand(el, text) && (await waitForStableVerify(el, text)),
    },
    {
      name: 'execCommand-html',
      run: async () => strategyExecCommandHtml(el, text) && (await waitForStableVerify(el, text)),
    },
    {
      name: 'ce-event-only',
      run: async () => (await strategyCeEventOnly(el, text)) && (await waitForStableVerify(el, text)),
    },
  ];

  for (const step of steps) {
    if (getElementText(el) !== before) return { success: false, reason: 'partial-change' };
    try {
      if (await step.run()) {
        return { success: true, strategy: step.name, writtenText: text };
      }
    } catch {
      // try next
    }
  }

  if (getElementText(el) !== before) return { success: false, reason: 'partial-change' };
  return { success: false, reason: 'verify-failed' };
}

/**
 * Legacy-compatible replace used by older tests — delegates to write pipeline.
 */
export function replaceElementText(el: HTMLElement, newText: string): void {
  writeElementText(el, newText);
}
