import type { SubtitleCue, SubtitleUrlPattern, AvailableSubtitleTrack } from '@/types/subtitle';
import type { SubtitleHandler } from './registry';
import { parseSubtitles } from '@/lib/subtitleParser';

function isCourseraHost(hostname: string): boolean {
  return hostname === 'coursera.org' || hostname.endsWith('.coursera.org');
}

/** BCP-47-ish segment in URL path or filename */
const COURSERA_LANG_SEGMENT = /\/([a-z]{2,3}([-_][A-Za-z]{2,4})?)\//i;

export class CourseraHandler implements SubtitleHandler {
  readonly platform = 'coursera';

  detect(): boolean {
    return isCourseraHost(window.location.hostname);
  }

  isWatchPage(): boolean {
    return window.location.pathname.includes('/lecture/');
  }

  getPatterns(): SubtitleUrlPattern[] {
    return [
      {
        platform: 'coursera',
        pattern: /cloudfront\.net\/.*\.vtt/i,
        languageExtractor: (url) => {
          const filename = url.pathname.split('/').pop() || '';
          const fileMatch = filename.match(/[_-]([a-z]{2,3}([-_][A-Za-z]{2,4})?)\.vtt$/i);
          if (fileMatch) return fileMatch[1].replace(/_/g, '-');
          const pathMatch = url.pathname.match(/\/([a-z]{2,3}([-_][A-Za-z]{2,4})?)\//i);
          return pathMatch?.[1]?.replace(/_/g, '-') || '';
        },
      },
      {
        platform: 'coursera',
        pattern: /coursera\.org\/.*subtitle/,
        languageExtractor: (url) => {
          // Language often in query param or path segment
          const lang = url.searchParams.get('lang') || '';
          if (lang) return lang;
          const match = url.pathname.match(COURSERA_LANG_SEGMENT);
          return match?.[1]?.replace(/_/g, '-') || '';
        },
      },
      {
        platform: 'coursera',
        pattern: /coursera\.org\/.*\.vtt/,
        languageExtractor: (url) => {
          const lang = url.searchParams.get('lang') || '';
          if (lang) return lang.replace(/_/g, '-');
          // Try to extract from filename (e.g., subtitle_en.vtt, subtitle_fil.vtt)
          const filename = url.pathname.split('/').pop() || '';
          const fileMatch = filename.match(/[_-]([a-z]{2,3}([-_][A-Za-z]{2,4})?)\.vtt$/i);
          if (fileMatch) return fileMatch[1].replace(/_/g, '-');
          const match = url.pathname.match(COURSERA_LANG_SEGMENT);
          return match?.[1]?.replace(/_/g, '-') || '';
        },
      },
    ];
  }

  getMetadataPatterns(): SubtitleUrlPattern[] {
    return [
      {
        platform: 'coursera',
        // Matches Coursera's video/lecture metadata APIs containing subtitle info
        pattern: /coursera\.org\/api\/onDemandLectureVideos/,
      },
      {
        platform: 'coursera',
        pattern: /coursera\.org\/api\/onDemandLectures/,
      },
    ];
  }

  extractAvailableTracks(body: string, _contentType: string, url: string): AvailableSubtitleTrack[] {
    try {
      const data = JSON.parse(body);
      const tracks: AvailableSubtitleTrack[] = [];

      const urlLectureMatch = url.match(/\/lecture\/([^/?]+)/);

      // Coursera may provide subtitleLanguageCodes or subtitles in various locations
      const elements = data?.elements || data?.linked || [];
      for (const element of (Array.isArray(elements) ? elements : [elements])) {
        const elementId =
          (typeof element?.id === 'string' && element.id) ||
          (typeof element?.elementId === 'string' && element.elementId) ||
          undefined;
        const videoId =
          elementId ||
          (typeof data?.id === 'string' ? data.id : undefined) ||
          urlLectureMatch?.[1];

        const subtitlesMap = element?.subtitles;
        if (subtitlesMap && typeof subtitlesMap === 'object' && !Array.isArray(subtitlesMap)) {
          for (const [lang, subtitleUrl] of Object.entries(subtitlesMap)) {
            tracks.push({
              language: lang,
              label: lang,
              url: typeof subtitleUrl === 'string' ? subtitleUrl : undefined,
              isAutoGenerated: false,
              platform: 'coursera',
              videoId,
            });
          }
        }

        const subtitlesVtt = element?.subtitlesVtt;
        if (Array.isArray(subtitlesVtt)) {
          for (const entry of subtitlesVtt) {
            if (!entry || typeof entry !== 'object') continue;
            const rec = entry as Record<string, unknown>;
            const lang =
              (typeof rec.languageCode === 'string' && rec.languageCode) ||
              (typeof rec.language === 'string' && rec.language) ||
              '';
            const trackUrl = typeof rec.url === 'string' ? rec.url : undefined;
            if (!lang) continue;
            if (!tracks.some((t) => t.language === lang && t.videoId === videoId)) {
              tracks.push({
                language: lang,
                label: lang,
                url: trackUrl,
                isAutoGenerated: false,
                platform: 'coursera',
                videoId,
              });
            }
          }
        } else if (
          subtitlesVtt &&
          typeof subtitlesVtt === 'object' &&
          !Array.isArray(subtitlesVtt)
        ) {
          for (const [lang, subtitleUrl] of Object.entries(subtitlesVtt)) {
            tracks.push({
              language: lang,
              label: lang,
              url: typeof subtitleUrl === 'string' ? subtitleUrl : undefined,
              isAutoGenerated: false,
              platform: 'coursera',
              videoId,
            });
          }
        }

        // Check for subtitleLanguageCodes
        const langCodes = element?.subtitleLanguageCodes;
        if (Array.isArray(langCodes)) {
          for (const code of langCodes) {
            if (typeof code === 'string' && !tracks.some((t) => t.language === code)) {
              tracks.push({
                language: code,
                label: code,
                isAutoGenerated: false,
                platform: 'coursera',
                videoId,
              });
            }
          }
        }
      }

      return tracks;
    } catch (err) {
      console.warn('AnyLLMTranslate: Coursera extractAvailableTracks failed', err);
      return [];
    }
  }

  transformResponse(body: string, _contentType: string, _url: string): SubtitleCue[] {
    return parseSubtitles(body);
  }
}

