import type { SubtitleCue, SubtitleUrlPattern, AvailableSubtitleTrack } from '@/types/subtitle';
import type { SubtitleHandler } from './registry';
import { parseWebVTT } from '@/lib/subtitleParser';

export class CourseraHandler implements SubtitleHandler {
  readonly platform = 'coursera';

  detect(): boolean {
    return window.location.hostname.includes('coursera.org');
  }

  isWatchPage(): boolean {
    return window.location.pathname.includes('/lecture/');
  }

  getPatterns(): SubtitleUrlPattern[] {
    return [
      {
        platform: 'coursera',
        pattern: /coursera\.org\/.*subtitle/,
        languageExtractor: (url) => {
          // Language often in query param or path segment
          const lang = url.searchParams.get('lang') || '';
          if (lang) return lang;
          const match = url.pathname.match(/\/([a-z]{2}(-[A-Z]{2})?)\//);
          return match?.[1] || '';
        },
      },
      {
        platform: 'coursera',
        pattern: /coursera\.org\/.*\.vtt/,
        languageExtractor: (url) => {
          const lang = url.searchParams.get('lang') || '';
          if (lang) return lang;
          // Try to extract from filename (e.g., subtitle_en.vtt)
          const filename = url.pathname.split('/').pop() || '';
          const fileMatch = filename.match(/[_-]([a-z]{2}([-_][A-Z]{2})?)\.vtt$/i);
          if (fileMatch) return fileMatch[1].replace('_', '-');
          const match = url.pathname.match(/\/([a-z]{2}(-[A-Z]{2})?)\//);
          return match?.[1] || '';
        },
      },
    ];
  }

  getMetadataPatterns(): SubtitleUrlPattern[] {
    return [
      {
        platform: 'coursera',
        // Matches Coursera's video/lecture metadata APIs containing subtitle info
        pattern: /coursera\.org\/api\/onDemandLectureVideos/,
      },
      {
        platform: 'coursera',
        pattern: /coursera\.org\/api\/onDemandLectures/,
      },
    ];
  }

  extractAvailableTracks(body: string, _contentType: string, url: string): AvailableSubtitleTrack[] {
    try {
      const data = JSON.parse(body);
      const tracks: AvailableSubtitleTrack[] = [];

      // Extract videoId from URL path (e.g., /learn/.../lecture/xyz)
      const urlMatch = url.match(/\/lecture\/([^/?]+)/);
      const videoId = urlMatch?.[1] || undefined;

      // Coursera may provide subtitleLanguageCodes or subtitles in various locations
      const elements = data?.elements || data?.linked || [];
      for (const element of (Array.isArray(elements) ? elements : [elements])) {
        // Check for subtitles array
        const subtitles = element?.subtitles || element?.subtitlesVtt || {};
        if (typeof subtitles === 'object' && !Array.isArray(subtitles)) {
          for (const [lang, url] of Object.entries(subtitles)) {
            tracks.push({
              language: lang,
              label: lang,
              url: typeof url === 'string' ? url : undefined,
              isAutoGenerated: false,
              platform: 'coursera',
              videoId,
            });
          }
        }

        // Check for subtitleLanguageCodes
        const langCodes = element?.subtitleLanguageCodes;
        if (Array.isArray(langCodes)) {
          for (const code of langCodes) {
            if (typeof code === 'string' && !tracks.some((t) => t.language === code)) {
              tracks.push({
                language: code,
                label: code,
                isAutoGenerated: false,
                platform: 'coursera',
                videoId,
              });
            }
          }
        }
      }

      return tracks;
    } catch {
      return [];
    }
  }

  transformResponse(body: string, _contentType: string, _url: string): SubtitleCue[] {
    // Coursera subtitles are standard WebVTT
    return parseWebVTT(body);
  }
}

