import type { SubtitleCue, SubtitleUrlPattern, AvailableSubtitleTrack } from '@/types/subtitle';
import type { SubtitleHandler } from './registry';
import { parseSubtitles } from '@/lib/subtitleParser';
import { ISO_639_2_TO_1 } from '@/lib/subtitleLanguageMatch';

export const DEEP_LEARNING_AI_PLATFORM = 'deeplearningai';

export function isDeepLearningAiHost(hostname: string): boolean {
  const host = hostname.toLowerCase();
  return host === 'deeplearning.ai' || host.endsWith('.deeplearning.ai');
}

/** Normalize a DLAI language code ('en-us', 'eng', 'JPN') to lowercase BCP-47-lite form. */
export function normalizeDeepLearningAiLanguage(code: string): string {
  let normalized = (code || '').trim().toLowerCase().replace(/_/g, '-');
  if (!normalized) return '';
  if (ISO_639_2_TO_1[normalized]) return ISO_639_2_TO_1[normalized];
  const parts = normalized.split('-');
  if (parts[0] && ISO_639_2_TO_1[parts[0]]) {
    parts[0] = ISO_639_2_TO_1[parts[0]];
    normalized = parts.join('-');
  }
  return normalized;
}

const LANG_SEGMENT = /^[a-z]{2,3}([-][a-z]{2,4})?$/i;

/** Extract the subtitle language from a video.deeplearning.ai subtitle URL
 *  (e.g. .../subtitle/eng/<file>.vtt or .../subtitle/jpn/<file>.vtt). */
export function extractDeepLearningAiLanguageFromUrl(url: URL): string {
  const parts = url.pathname.split('/').filter(Boolean);
  const subtitlesIdx = parts.findIndex((p) => p.toLowerCase() === 'subtitle');
  if (subtitlesIdx >= 0 && parts[subtitlesIdx + 1] && LANG_SEGMENT.test(parts[subtitlesIdx + 1])) {
    return normalizeDeepLearningAiLanguage(parts[subtitlesIdx + 1]);
  }
  // Fallback: a bare language-looking segment earlier in the path.
  for (const part of parts) {
    if (part.toLowerCase() !== 'subtitle' && LANG_SEGMENT.test(part)) {
      return normalizeDeepLearningAiLanguage(part);
    }
  }
  return '';
}

/** Result of scanning a DLAI payload for lesson video subtitle data. */
export interface DeepLearningAiVideoData {
  tracks: AvailableSubtitleTrack[];
  videoId?: string;
}

const MAX_VISITS = 4000;

/**
 * Recursively locate the lesson video object inside any DLAI payload
 * (the embedded `__NEXT_DATA__` dehydrated tRPC state, a tRPC API response,
 * or a bare video object) and extract its subtitle tracks.
 *
 * Recognized shapes:
 *  - `tracks: [{ kind: 'subtitles', label, src: '...vtt', srcLang }]`
 *  - `subtitle: '{"en-us": {"URI": "...vtt", "NAME": "ENGLISH"}, ...}'` (string-encoded map)
 */
export function extractDeepLearningAiVideoData(value: unknown): DeepLearningAiVideoData | null {
  if (!value || typeof value !== 'object') return null;
  const seen = new Set<unknown>();
  const queue: unknown[] = [value];
  let visits = 0;
  while (queue.length > 0 && visits < MAX_VISITS) {
    const node = queue.shift();
    if (!node || typeof node !== 'object') continue;
    visits += 1;
    if (seen.has(node)) continue;
    seen.add(node);

    const result = extractVideoFromNode(node as Record<string, unknown>);
    if (result) return result;

    for (const child of Object.values(node as Record<string, unknown>)) {
      if (child && typeof child === 'object') queue.push(child);
    }
  }
  return null;
}

function extractVideoFromNode(node: Record<string, unknown>): DeepLearningAiVideoData | null {
  const videoId =
    typeof node.videoId === 'string' || typeof node.videoId === 'number'
      ? String(node.videoId)
      : undefined;

  const tracks: AvailableSubtitleTrack[] = [];
  const pushTrack = (language: string, label: string, url: string) => {
    if (!language || !url || tracks.some((t) => t.url === url)) return;
    tracks.push({
      language,
      label: label || language,
      url,
      isAutoGenerated: false,
      platform: DEEP_LEARNING_AI_PLATFORM,
      videoId,
    });
  };

  // Primary: native <track>-style list from course.getLessonVideo
  if (Array.isArray(node.tracks)) {
    for (const entry of node.tracks) {
      if (!entry || typeof entry !== 'object') continue;
      const rec = entry as Record<string, unknown>;
      if (typeof rec.src !== 'string' || !/\.(vtt|webvtt)$/i.test(rec.src)) continue;
      const kind = typeof rec.kind === 'string' ? rec.kind.toLowerCase() : 'subtitles';
      if (kind !== 'subtitles') continue;
      const language =
        typeof rec.srcLang === 'string' && rec.srcLang
          ? normalizeDeepLearningAiLanguage(rec.srcLang)
          : safeLanguageFromUrl(rec.src);
      const label = typeof rec.label === 'string' ? rec.label : '';
      pushTrack(language, label, rec.src);
    }
  }

  // Secondary: string-encoded language map ("subtitle" field)
  if (typeof node.subtitle === 'string' && node.subtitle.trim()) {
    try {
      const map = JSON.parse(node.subtitle) as Record<string, unknown>;
      for (const [code, rawEntry] of Object.entries(map)) {
        const entry = rawEntry as Record<string, unknown> | null;
        const uri = entry && typeof entry.URI === 'string' ? entry.URI : undefined;
        if (!uri || !/\.(vtt|webvtt)$/i.test(uri)) continue;
        pushTrack(
          normalizeDeepLearningAiLanguage(code),
          typeof entry?.NAME === 'string' ? entry.NAME : '',
          uri,
        );
      }
    } catch {
      // Not a JSON-encoded map — ignore.
    }
  }

  return tracks.length > 0 ? { tracks, videoId } : null;
}

function safeLanguageFromUrl(url: string): string {
  try {
    return extractDeepLearningAiLanguageFromUrl(new URL(url));
  } catch {
    return '';
  }
}

/** Read the SSR-embedded Next.js data payload (`#__NEXT_DATA__`) from the DOM. */
export function readNextDataJson(doc: Document = document): unknown | null {
  const el = doc.getElementById('__NEXT_DATA__');
  if (!el?.textContent) return null;
  try {
    const parsed: unknown = JSON.parse(el.textContent);
    return parsed && typeof parsed === 'object' ? parsed : null;
  } catch {
    return null;
  }
}

export class DeepLearningAiHandler implements SubtitleHandler {
  readonly platform = DEEP_LEARNING_AI_PLATFORM;

  detect(): boolean {
    return isDeepLearningAiHost(window.location.hostname);
  }

  /** Lesson pages look like /courses/{slug}/lesson/{videoId}/{lessonName}. */
  isWatchPage(): boolean {
    return /\/lesson(\/|$)/i.test(window.location.pathname);
  }

  getPatterns(): SubtitleUrlPattern[] {
    return [
      {
        platform: DEEP_LEARNING_AI_PLATFORM,
        // Cue files on the DLAI CDN: .../upv2/<course>/<lesson>/subtitle/<lang>/<file>.vtt.
        // Requires the /subtitle/ segment so thumbnail/chapter VTTs never match.
        pattern: /video\.deeplearning\.ai\/.*\/subtitle\/[^/?#]+\/.+\.vtt(?:\?|$)/i,
        languageExtractor: (url) => extractDeepLearningAiLanguageFromUrl(url),
      },
    ];
  }

  getMetadataPatterns(): SubtitleUrlPattern[] {
    return [
      {
        platform: DEEP_LEARNING_AI_PLATFORM,
        // Client-side (SPA navigation) tRPC lesson-video request. The SSR payload
        // is handled by embedded __NEXT_DATA__ discovery in the MAIN world.
        pattern: /(?:deeplearning\.ai|dlai\.link)\/api\/trpc\/.*getLessonVideo/i,
      },
    ];
  }

  extractAvailableTracks(
    body: string,
    _contentType: string,
    _url: string,
  ): AvailableSubtitleTrack[] {
    // Empty body: DOM discovery fallback (SSR __NEXT_DATA__ on lesson pages).
    const source: unknown = body ? safeParseJson(body) : readNextDataJson();
    if (!source) return [];
    return extractDeepLearningAiVideoData(source)?.tracks ?? [];
  }

  transformResponse(body: string, _contentType: string, _url: string): SubtitleCue[] {
    return parseSubtitles(body);
  }
}

function safeParseJson(body: string): unknown | null {
  try {
    const parsed: unknown = JSON.parse(body);
    return parsed && typeof parsed === 'object' ? parsed : null;
  } catch {
    return null;
  }
}
