import type {
  SubtitleCue,
  SubtitleUrlPattern,
  AvailableSubtitleTrack,
} from '@/types/subtitle';
import type { SubtitleHandler } from './registry';
import { parseSubtitles } from '@/lib/subtitleParser';

function isDisneyPlusHost(hostname: string): boolean {
  const host = hostname.toLowerCase();
  return host === 'disneyplus.com' || host.endsWith('.disneyplus.com');
}

function pickCaptionUrl(caption: Record<string, unknown>): string | undefined {
  const direct =
    (caption.url as string) ||
    (caption.href as string) ||
    (caption.vtt as string) ||
    (caption.webVtt as string);
  if (typeof direct === 'string' && direct.length > 0) return direct;

  const sources = caption.sources;
  if (Array.isArray(sources)) {
    for (const s of sources) {
      if (s && typeof s === 'object') {
        const u = (s as Record<string, unknown>).url ?? (s as Record<string, unknown>).href;
        if (typeof u === 'string' && u.length > 0) return u;
      }
    }
  }
  return undefined;
}

/**
 * Disney+ asset JSON (Immersive disneyplus handler watches asset.captions).
 */
export function extractDisneyPlusTracksFromValue(value: unknown): AvailableSubtitleTrack[] {
  if (!value || typeof value !== 'object') return [];

  const root = value as Record<string, unknown>;
  const asset = (root.asset as Record<string, unknown> | undefined) ?? root;
  const captions = asset.captions;

  if (!Array.isArray(captions) || captions.length === 0) return [];

  const videoId =
    (typeof asset.id === 'string' && asset.id) ||
    (typeof root.id === 'string' && root.id) ||
    undefined;

  const tracks: AvailableSubtitleTrack[] = [];

  for (const item of captions) {
    if (!item || typeof item !== 'object') continue;
    const c = item as Record<string, unknown>;
    const language =
      (typeof c.language === 'string' && c.language.replace(/_/g, '-')) ||
      (typeof c.bcp47 === 'string' && c.bcp47.replace(/_/g, '-')) ||
      (typeof c.lang === 'string' && c.lang.replace(/_/g, '-')) ||
      '';
    if (!language) continue;

    const url = pickCaptionUrl(c);
    const label =
      (typeof c.label === 'string' && c.label) ||
      (typeof c.name === 'string' && c.name) ||
      language;

    tracks.push({
      language,
      label,
      url,
      isAutoGenerated: c.type === 'auto' || c.isAutoGenerated === true,
      platform: 'disneyplus',
      videoId,
    });
  }

  return tracks;
}

export class DisneyPlusHandler implements SubtitleHandler {
  readonly platform = 'disneyplus';

  detect(): boolean {
    return isDisneyPlusHost(window.location.hostname);
  }

  isWatchPage(): boolean {
    return (
      window.location.pathname.includes('/video/') ||
      window.location.pathname.includes('/play/')
    );
  }

  getPatterns(): SubtitleUrlPattern[] {
    return [
      {
        platform: 'disneyplus',
        pattern: /\.vtt(?:\?|$)/i,
        languageExtractor: (url) => {
          const lang = url.searchParams.get('lang') || url.searchParams.get('language');
          if (lang) return lang.replace(/_/g, '-');
          const parts = url.pathname.split('/').filter(Boolean);
          const seg = parts.find((p) => /^[a-z]{2}([-_][A-Za-z]{2,4})?$/i.test(p));
          return seg?.replace(/_/g, '-') || '';
        },
      },
    ];
  }

  extractTracksFromParsedJson(value: unknown): AvailableSubtitleTrack[] {
    return extractDisneyPlusTracksFromValue(value);
  }

  extractAvailableTracks(body: string, _contentType: string, _url: string): AvailableSubtitleTrack[] {
    try {
      const data = JSON.parse(body) as { tracks?: AvailableSubtitleTrack[] };
      if (Array.isArray(data.tracks)) {
        return data.tracks.filter((t) => t.language?.length > 0);
      }
      return extractDisneyPlusTracksFromValue(data);
    } catch {
      return [];
    }
  }

  transformResponse(body: string, _contentType: string, _url: string): SubtitleCue[] {
    return parseSubtitles(body);
  }
}
