import type {
  SubtitleCue,
  SubtitleUrlPattern,
  AvailableSubtitleTrack,
  DomCueSource,
} from '@/types/subtitle';
import type { SubtitleHandler } from './registry';

/** Max aria-label → ISO 639-1 / BCP-47 code. Covers observed track labels. */
const LABEL_TO_LANGUAGE: Record<string, string> = {
  English: 'en',
  'Chinese (Simplified)': 'zh-Hans',
  'Chinese (Traditional)': 'zh-Hant',
  Indonesian: 'id',
  Malay: 'ms',
  Thai: 'th',
  Vietnamese: 'vi',
};

export class HboMaxHandler implements SubtitleHandler {
  readonly platform = 'hbomax';

  detect(): boolean {
    const host = window.location.hostname;
    return (
      host === 'max.com' ||
      host === 'www.max.com' ||
      host.endsWith('.max.com') ||
      host === 'play.hbomax.com' ||
      host.endsWith('.hbomax.com')
    );
  }

  getPatterns(): SubtitleUrlPattern[] {
    // Max renders captions into the DOM — no URL interception.
    return [];
  }

  transformResponse(_body: string, _contentType: string, _url: string): SubtitleCue[] {
    return [];
  }

  extractAvailableTracks(
    _body: string,
    _contentType: string,
    _url: string,
  ): AvailableSubtitleTrack[] {
    const buttons = document.querySelectorAll<HTMLButtonElement>(
      '[data-testid="player-ux-text-track-button"]',
    );
    if (buttons.length === 0) return [];

    const videoId = this.extractVideoId();

    const tracks: AvailableSubtitleTrack[] = [];
    for (const btn of buttons) {
      const label = btn.getAttribute('aria-label') || '';
      if (!label || label.toLowerCase() === 'off') continue;
      const language = LABEL_TO_LANGUAGE[label] ?? label.toLowerCase();
      tracks.push({
        language,
        label,
        url: undefined, // DOM-sourced — no fetch URL
        isAutoGenerated: false,
        platform: 'hbomax',
        videoId,
      });
    }
    return tracks;
  }

  getDomCueSource(): DomCueSource {
    return {
      cueSelector: '[data-testid="cueBoxRowTextCue"]',
      captionWindowSelector: '[data-testid="caption_renderer_overlay"]',
      observeRootSelector: '[data-testid="caption_renderer_overlay"]',
      readActiveLanguage: () => this.readActiveLanguage(),
    };
  }

  /** Read the active track's language from the aria-checked button. */
  private readActiveLanguage(): string {
    const buttons = document.querySelectorAll<HTMLButtonElement>(
      '[data-testid="player-ux-text-track-button"]',
    );
    for (const btn of buttons) {
      if (btn.getAttribute('aria-checked') === 'true') {
        const label = btn.getAttribute('aria-label') || '';
        if (!label || label.toLowerCase() === 'off') return '';
        return LABEL_TO_LANGUAGE[label] ?? label.toLowerCase();
      }
    }
    return '';
  }

  /** Extract videoId from /video/watch/<id>/... path. */
  private extractVideoId(): string | undefined {
    const match = window.location.pathname.match(/\/video\/watch\/([^/]+)/);
    return match?.[1];
  }
}
