import type {
  SubtitleCue,
  SubtitleUrlPattern,
  AvailableSubtitleTrack,
  DomCueSource,
} from '@/types/subtitle';
import type { SubtitleHandler } from './registry';

/** Max aria-label → ISO 639-1 / BCP-47 code. Covers observed track labels. */
const LABEL_TO_LANGUAGE: Record<string, string> = {
  English: 'en',
  'Chinese (Simplified)': 'zh-Hans',
  'Chinese (Traditional)': 'zh-Hant',
  Indonesian: 'id',
  Malay: 'ms',
  Thai: 'th',
  Spanish: 'es',
  Vietnamese: 'vi',
  French: 'fr',
  German: 'de',
  Italian: 'it',
  Japanese: 'ja',
  Korean: 'ko',
  Portuguese: 'pt',
  'Portuguese (Brazil)': 'pt-BR',
  Russian: 'ru',
  Arabic: 'ar',
  Hindi: 'hi',
  Polish: 'pl',
  Turkish: 'tr',
  Dutch: 'nl',
  Danish: 'da',
  Finnish: 'fi',
  Swedish: 'sv',
  Norwegian: 'no',
  'Norwegian Bokmål': 'nb',
  Czech: 'cs',
  Hungarian: 'hu',
  Greek: 'el',
  Hebrew: 'he',
  Romanian: 'ro',
  Catalan: 'ca',
  Ukrainian: 'uk',
  Bulgarian: 'bg',
  Croatian: 'hr',
  Slovak: 'sk',
  Slovenian: 'sl',
  Estonian: 'et',
  Latvian: 'lv',
  Lithuanian: 'lt',
};

export class HboMaxHandler implements SubtitleHandler {
  readonly platform = 'hbomax';

  detect(): boolean {
    const host = window.location.hostname;
    return (
      host === 'max.com' ||
      host === 'www.max.com' ||
      host.endsWith('.max.com') ||
      host === 'play.hbomax.com' ||
      host.endsWith('.hbomax.com')
    );
  }

  isWatchPage(): boolean {
    return window.location.pathname.includes('/video/watch/');
  }

  getPatterns(): SubtitleUrlPattern[] {
    // Max renders captions into the DOM — no URL interception.
    return [];
  }

  getManifestPatterns(): SubtitleUrlPattern[] {
    // Best-guess manifest patterns for HLS/DASH on Max CDN domains.
    // Correctness pending live confirmation — DOM scraping is retained as fallback.
    return [
      {
        platform: 'hbomax',
        // HLS multivariant or media playlist on Max CDN domains
        pattern: /https?:\/\/[^/]*(?:max\.com|hbomax\.com|hbo\.com)[^?]*\.m3u8(?:\?|$)/i,
      },
      {
        platform: 'hbomax',
        // DASH manifest on Max CDN domains
        pattern: /https?:\/\/[^/]*(?:max\.com|hbomax\.com|hbo\.com)[^?]*\.mpd(?:\?|$)/i,
      },
    ];
  }

  transformResponse(_body: string, _contentType: string, _url: string): SubtitleCue[] {
    return [];
  }

  extractAvailableTracks(
    _body: string,
    _contentType: string,
    _url: string,
  ): AvailableSubtitleTrack[] {
    const buttons = document.querySelectorAll<HTMLButtonElement>(
      '[data-testid="player-ux-text-track-button"]',
    );
    if (buttons.length === 0) return [];

    const videoId = this.extractVideoId();

    const tracks: AvailableSubtitleTrack[] = [];
    for (const btn of buttons) {
      const label = btn.getAttribute('aria-label') || '';
      if (!label || label.toLowerCase() === 'off') continue;
      const language = LABEL_TO_LANGUAGE[label] ?? label.toLowerCase();
      tracks.push({
        language,
        label,
        url: undefined, // DOM-sourced — no fetch URL
        isAutoGenerated: false,
        platform: 'hbomax',
        videoId,
      });
    }
    return tracks;
  }

  getDomCueSource(): DomCueSource {
    return {
      cueSelector: '[data-testid="cueBoxRowTextCue"]',
      captionWindowSelector: '[data-testid="caption_renderer_overlay"]',
      observeRootSelector: '[data-testid="caption_renderer_overlay"]',
      readActiveLanguage: () => this.readActiveLanguage(),
      videoIdExtractor: () => this.extractVideoId(),
      // Track-switch detection: Max's text-track buttons carry aria-checked.
      // (Previously hardcoded in domCueSource.ts; now declared per-platform.)
      trackSwitchSelector: '[data-testid="player-ux-text-track-button"]',
      trackSwitchAttribute: 'aria-checked',
    };
  }

  /** Read the active track's language from the aria-checked button. */
  private readActiveLanguage(): string {
    const buttons = document.querySelectorAll<HTMLButtonElement>(
      '[data-testid="player-ux-text-track-button"]',
    );
    for (const btn of buttons) {
      if (btn.getAttribute('aria-checked') === 'true') {
        const label = btn.getAttribute('aria-label') || '';
        if (!label || label.toLowerCase() === 'off') return '';
        return LABEL_TO_LANGUAGE[label] ?? label.toLowerCase();
      }
    }
    return '';
  }

  /** Extract videoId from /video/watch/<id>/... path. */
  private extractVideoId(): string | undefined {
    const match = window.location.pathname.match(/\/video\/watch\/([^/]+)/);
    return match?.[1];
  }
}
