import type {
  SubtitleCue,
  SubtitleUrlPattern,
  AvailableSubtitleTrack,
  DomCueSource,
} from '@/types/subtitle';
import type { SubtitleHandler } from './registry';
import { normalizeMaxSubtitleLanguage, readMaxActiveSubtitleLanguage } from '@/lib/maxSubtitleLanguages';
import { parseSubtitles } from '@/lib/subtitleParser';

export class HboMaxHandler implements SubtitleHandler {
  readonly platform = 'hbomax';

  detect(): boolean {
    const host = window.location.hostname;
    return (
      host === 'max.com' ||
      host === 'www.max.com' ||
      host.endsWith('.max.com') ||
      host === 'play.hbomax.com' ||
      host.endsWith('.hbomax.com')
    );
  }

  isWatchPage(): boolean {
    return window.location.pathname.includes('/video/watch/');
  }

  getPatterns(): SubtitleUrlPattern[] {
    // Immersive Translate hbomax rule: type webvtt, subtitleUrlRegExp \.vtt$,
    // enableHookDownload (overlay/out-of-band — not in-player VTT swap; IT notes
    // self-hosted responses desync timelines). Fetch/XHR intercept on Max CDN .vtt.
    return [
      {
        platform: 'hbomax',
        pattern: /\.vtt(?:\?|$)/i,
        languageExtractor: (url) => this.languageFromVttUrl(url.pathname),
      },
    ];
  }

  getManifestPatterns(): SubtitleUrlPattern[] {
    // Max streams HLS/DASH through generic Akamai/Fastly CDN edges whose
    // hostnames are NOT max.com/hbomax.com (e.g. beam-*.prd.api.hbomax.com,
    // dl.delivery.mp.microsoft.com, etc.).  Since detect() already confirms
    // we are on a Max page, match any .m3u8 / .mpd URL — the FetchInterceptor
    // only calls getManifestPatterns() for the registered handler anyway.
    return [
      {
        platform: 'hbomax',
        // Any HLS multivariant or media playlist URL
        pattern: /https?:\/\/.+\.m3u8(?:\?|$)/i,
      },
      {
        platform: 'hbomax',
        // Any DASH manifest URL
        pattern: /https?:\/\/.+\.mpd(?:\?|$)/i,
      },
      {
        platform: 'hbomax',
        // Max CDN extensionless manifests: single asset-id path segment before query
        pattern: /https?:\/\/[^/]*prd\.media\.max\.com\/[^/?]+?\?manifest-params=/i,
      },
    ];
  }

  transformResponse(body: string, _contentType: string, url: string): SubtitleCue[] {
    // DASH segment VTT may use segment-relative times; MPD/manifest path applies
    // offsets when available. This path mirrors IT hook-download for progressive cues.
    void url;
    return parseSubtitles(body);
  }

  extractAvailableTracks(
    _body: string,
    _contentType: string,
    _url: string,
  ): AvailableSubtitleTrack[] {
    const buttons = document.querySelectorAll<HTMLButtonElement>(
      '[data-testid="player-ux-text-track-button"]',
    );
    if (buttons.length === 0) return [];

    const videoId = this.extractVideoId();

    const tracks: AvailableSubtitleTrack[] = [];
    for (const btn of buttons) {
      const label = btn.getAttribute('aria-label') || '';
      if (!label || label.toLowerCase() === 'off') continue;
      const language = normalizeMaxSubtitleLanguage(
        label,
        btn.getAttribute('lang') || btn.getAttribute('data-language'),
      );
      tracks.push({
        language,
        label,
        url: undefined, // DOM-sourced — no fetch URL
        isAutoGenerated: false,
        platform: 'hbomax',
        videoId,
      });
    }
    return tracks;
  }

  getDomCueSource(): DomCueSource {
    return {
      cueSelector: '[data-testid="cueBoxRowTextCue"]',
      captionWindowSelector: '[data-testid="caption_renderer_overlay"]',
      observeRootSelector: '[data-testid="caption_renderer_overlay"]',
      readActiveLanguage: () => this.readActiveLanguage(),
      videoIdExtractor: () => this.extractVideoId(),
      // Track-switch detection: Max's text-track buttons carry aria-checked.
      // (Previously hardcoded in domCueSource.ts; now declared per-platform.)
      trackSwitchSelector: '[data-testid="player-ux-text-track-button"]',
      trackSwitchAttribute: 'aria-checked',
    };
  }

  /** Read the active track's language from the aria-checked button. */
  private readActiveLanguage(): string {
    return readMaxActiveSubtitleLanguage();
  }

  /** Extract videoId from /video/watch/<id>/... path. */
  private extractVideoId(): string | undefined {
    const match = window.location.pathname.match(/\/video\/watch\/([^/]+)/);
    return match?.[1];
  }

  /** Best-effort language from Max CDN VTT path (e.g. .../t/<trackId>/3.vtt). */
  private languageFromVttUrl(pathname: string): string {
    const active = readMaxActiveSubtitleLanguage();
    if (active) return active;
    const seg = pathname.match(/\/t\/([^/]+)\//);
    return seg?.[1] ?? '';
  }
}
