import type {
  SubtitleCue,
  SubtitleUrlPattern,
  AvailableSubtitleTrack,
} from '@/types/subtitle';
import type { SubtitleHandler } from './registry';
import { parseSubtitles } from '@/lib/subtitleParser';

/** Netflix timed-text CDN (see Immersive Translate subtitleUrlRegExp). */
const NFLX_SUBTITLE_URL = /^https?:\/\/[^/]+\.nflxvideo\.net\/\?/i;

function isNetflixHost(hostname: string): boolean {
  const host = hostname.toLowerCase();
  return host === 'netflix.com' || host.endsWith('.netflix.com');
}

function normalizeNetflixLanguage(code: unknown, label?: unknown): string {
  if (typeof code === 'string' && code.length > 0) {
    return code.replace(/_/g, '-');
  }
  if (typeof label === 'string' && /^[a-z]{2}([-_][A-Za-z]{2,4})?$/i.test(label)) {
    return label.replace(/_/g, '-');
  }
  return '';
}

interface NetflixTimedTextTrack {
  language?: string;
  languageCode?: string;
  bcp47?: string;
  displayName?: string;
  label?: string;
  href?: string;
  url?: string;
  downloadUrls?: string[] | Record<string, string>;
  isForcedNarrative?: boolean;
  isImageBased?: boolean;
}

/**
 * Netflix player metadata shape (varies by API version).
 * Immersive hooks result.timedtexttracks + result.movieId.
 */
export function extractNetflixTracksFromValue(value: unknown): AvailableSubtitleTrack[] {
  if (!value || typeof value !== 'object') return [];

  const root = value as Record<string, unknown>;
  const result = (root.result as Record<string, unknown> | undefined) ?? root;

  const movieId =
    (typeof result.movieId === 'string' && result.movieId) ||
    (typeof result.watchId === 'string' && result.watchId) ||
    undefined;

  const rawTracks = result.timedtexttracks ?? result.timedTextTracks;
  if (!Array.isArray(rawTracks)) return [];

  const tracks: AvailableSubtitleTrack[] = [];

  for (const item of rawTracks) {
    if (!item || typeof item !== 'object') continue;
    const t = item as NetflixTimedTextTrack;
    if (t.isImageBased) continue;

    const language = normalizeNetflixLanguage(
      t.bcp47 ?? t.languageCode ?? t.language,
      t.displayName ?? t.label,
    );
    if (!language) continue;

    let url: string | undefined;
    if (typeof t.href === 'string') url = t.href;
    else if (typeof t.url === 'string') url = t.url;
    else if (Array.isArray(t.downloadUrls) && typeof t.downloadUrls[0] === 'string') {
      url = t.downloadUrls[0];
    } else if (t.downloadUrls && typeof t.downloadUrls === 'object') {
      const first = Object.values(t.downloadUrls).find((v) => typeof v === 'string');
      if (typeof first === 'string') url = first;
    }

    tracks.push({
      language,
      label: (t.displayName as string) || (t.label as string) || language,
      url,
      isAutoGenerated: false,
      platform: 'netflix',
      videoId: movieId,
    });
  }

  return tracks;
}

export class NetflixHandler implements SubtitleHandler {
  readonly platform = 'netflix';

  detect(): boolean {
    return isNetflixHost(window.location.hostname);
  }

  isWatchPage(): boolean {
    return window.location.pathname.startsWith('/watch/');
  }

  getPatterns(): SubtitleUrlPattern[] {
    return [
      {
        platform: 'netflix',
        pattern: NFLX_SUBTITLE_URL,
        languageExtractor: (url) => {
          const lang =
            url.searchParams.get('lang') ||
            url.searchParams.get('language') ||
            url.searchParams.get('l');
          return lang?.replace(/_/g, '-') || '';
        },
      },
    ];
  }

  extractTracksFromParsedJson(value: unknown): AvailableSubtitleTrack[] {
    return extractNetflixTracksFromValue(value);
  }

  extractAvailableTracks(body: string, _contentType: string, _url: string): AvailableSubtitleTrack[] {
    try {
      const data = JSON.parse(body) as { tracks?: AvailableSubtitleTrack[] };
      if (Array.isArray(data.tracks)) {
        return data.tracks.filter((t) => t.language?.length > 0);
      }
      return extractNetflixTracksFromValue(data);
    } catch {
      return [];
    }
  }

  transformResponse(body: string, _contentType: string, _url: string): SubtitleCue[] {
    return parseSubtitles(body);
  }
}
