import type { SubtitleCue, SubtitleUrlPattern, AvailableSubtitleTrack } from '@/types/subtitle';
import type { SubtitleHandler } from './registry';
import { parseWebVTT } from '@/lib/subtitleParser';

export class UdemyHandler implements SubtitleHandler {
  readonly platform = 'udemy';

  detect(): boolean {
    return window.location.hostname.includes('udemy.com');
  }

  isWatchPage(): boolean {
    return window.location.pathname.includes('/learn/');
  }

  getPatterns(): SubtitleUrlPattern[] {
    return [
      {
        platform: 'udemy',
        pattern: /\.udemycdn\.com\/(?!.*(sprite|thumbnail|board)).*\.vtt/,
        languageExtractor: (url) => {
          const pathParts = url.pathname.split('/');
          // Language is usually in the path: /subtitle-en/ or /en/
          const langMatch = pathParts.find((p) => /^[a-z]{2}(-[A-Z]{2})?$/.test(p));
          return langMatch || '';
        },
      },
    ];
  }

  getMetadataPatterns(): SubtitleUrlPattern[] {
    return [
      {
        platform: 'udemy',
        // Matches Udemy's internal lecture metadata API which contains captions array
        pattern: /udemy\.com\/api-2\.0\/.*lectures\/\d+/,
      },
    ];
  }

  extractAvailableTracks(body: string, _contentType: string, url: string): AvailableSubtitleTrack[] {
    try {
      const data = JSON.parse(body);
      // Extract lecture ID from URL (e.g., /api-2.0/lectures/12345/)
      const urlMatch = url.match(/lectures\/(\d+)/);
      const videoId = urlMatch?.[1] || undefined;
      // Udemy nests captions under asset.captions or directly in results
      const captions = data?.asset?.captions || data?.captions || data?.results || [];
      if (!Array.isArray(captions)) return [];

      return captions
        .filter((c: Record<string, unknown>) => c.status === 1 || c.status === undefined)
        .map((c: Record<string, unknown>) => ({
          language:
            (typeof c.locale_id === 'string' ? c.locale_id.replace('_', '-') : '') || '',
          label: (c.title as string) || (c.locale_id as string) || '',
          url: (c.url as string) || undefined,
          isAutoGenerated: c.source === 'auto',
          platform: 'udemy',
          videoId,
        }))
        .filter((t: AvailableSubtitleTrack) => t.language.length > 0);
    } catch {
      return [];
    }
  }

  transformResponse(body: string, _contentType: string, _url: string): SubtitleCue[] {
    // Udemy subtitles are standard WebVTT
    const cues = parseWebVTT(body);

    // Cue-level filtering: remove ONLY cues that are pure sprite metadata
    // Sprite metadata is very short (typically < 100 chars) and matches the pattern exactly
    const filteredCues = cues.filter((cue) => {
      const text = cue.text.trim();

      // Only filter if the text is short AND matches sprite pattern
      // This prevents false positives on legitimate subtitles discussing image files
      if (text.length > 100) {
        return true; // Keep long subtitles (they're not sprite metadata)
      }

      // Check for sprite-specific pattern: image file with #xywh= coordinates
      // Must be the entire text, not just contained within
      const spritePattern = /^(.+)\.(jpg|png|jpeg|webp|gif)#xywh=.+$/i;
      return !spritePattern.test(text);
    });

    // Early-exit heuristic: if ALL cues were filtered out (pure sprite track), return empty array
    // This is an optimization to avoid processing pure sprite metadata tracks
    if (filteredCues.length === 0 && cues.length > 0) {
      return [];
    }

    return filteredCues;
  }
}

