import type { SubtitleCue, SubtitleUrlPattern, AvailableSubtitleTrack } from '@/types/subtitle';
import type { SubtitleHandler } from './registry';
import { parseSubtitles } from '@/lib/subtitleParser';

function isUdemyHost(hostname: string): boolean {
  return hostname === 'udemy.com' || hostname.endsWith('.udemy.com');
}

/** Language folder in Udemy CDN paths: .../subtitles/{lectureId}/{lang}/file.vtt */
function extractUdemyLanguageFromUrl(url: URL): string {
  const parts = url.pathname.split('/').filter(Boolean);
  const subtitlesIdx = parts.findIndex((p) => p === 'subtitles');
  if (subtitlesIdx >= 0 && parts.length > subtitlesIdx + 2) {
    const langSegment = parts[subtitlesIdx + 2];
    if (/^[a-z]{2,3}([-_][A-Za-z]{2,4})?$/i.test(langSegment)) {
      return langSegment.replace(/_/g, '-');
    }
  }
  const langMatch = parts.find((p) => /^[a-z]{2,3}([-_][A-Za-z]{2,4})?$/i.test(p));
  return langMatch?.replace(/_/g, '-') || '';
}

export class UdemyHandler implements SubtitleHandler {
  readonly platform = 'udemy';

  detect(): boolean {
    return isUdemyHost(window.location.hostname);
  }

  isWatchPage(): boolean {
    return window.location.pathname.includes('/learn/');
  }

  getPatterns(): SubtitleUrlPattern[] {
    return [
      {
        platform: 'udemy',
        pattern: /\.udemycdn\.com\/(?!.*(sprite|thumbnail|board)).*\.vtt/,
        languageExtractor: (url) => extractUdemyLanguageFromUrl(url),
      },
    ];
  }

  getMetadataPatterns(): SubtitleUrlPattern[] {
    return [
      {
        platform: 'udemy',
        // Matches Udemy's internal lecture metadata API which contains captions array
        pattern: /udemy\.com\/api-2\.0\/.*lectures\/\d+/,
      },
    ];
  }

  extractAvailableTracks(body: string, _contentType: string, url: string): AvailableSubtitleTrack[] {
    try {
      const data = JSON.parse(body);
      // Extract lecture ID from URL (e.g., /api-2.0/lectures/12345/)
      const urlMatch = url.match(/lectures\/(\d+)/);
      const videoId = urlMatch?.[1] || undefined;
      // Udemy nests captions under asset.captions or directly in results
      const captions = data?.asset?.captions || data?.captions || [];
      if (!Array.isArray(captions)) return [];

      return captions
        .filter((c: Record<string, unknown>) => c.status === 1 || c.status === undefined)
        .map((c: Record<string, unknown>) => ({
          language:
            (typeof c.locale_id === 'string' ? c.locale_id.replace('_', '-') : '') || '',
          label: (c.title as string) || (c.locale_id as string) || '',
          url: (c.url as string) || undefined,
          isAutoGenerated: c.source === 'auto' || c.source === 'auto-generated',
          platform: 'udemy',
          videoId,
        }))
        .filter((t: AvailableSubtitleTrack) => t.language.length > 0);
    } catch (err) {
      console.warn('AnyLLMTranslate: Udemy extractAvailableTracks failed', err);
      return [];
    }
  }

  transformResponse(body: string, _contentType: string, _url: string): SubtitleCue[] {
    const cues = parseSubtitles(body);

    // Cue-level filtering: remove ONLY cues that are pure sprite metadata
    // Sprite metadata is very short (typically < 100 chars) and matches the pattern exactly
    return cues.filter((cue) => {
      const text = cue.text.trim();
      const spritePattern = /^(.+)\.(jpg|png|jpeg|webp|gif)#xywh=.+$/i;
      return !spritePattern.test(text);
    });
  }
}

