import type {
  SubtitleCue,
  SubtitleUrlPattern,
  AvailableSubtitleTrack,
} from '@/types/subtitle';
import type { SubtitleHandler } from './registry';
import { parseSubtitles } from '@/lib/subtitleParser';

/** Immersive Translate `iflix` rule: www.iflix.com + wetv.vip, XHR + .vtt */
function isWetvHost(hostname: string): boolean {
  const host = hostname.toLowerCase();
  if (host === 'iflix.com' || host.endsWith('.iflix.com')) return true;
  if (host === 'wetv.vip' || host.endsWith('.wetv.vip')) return true;
  return false;
}

export class WetvHandler implements SubtitleHandler {
  readonly platform = 'wetv';

  detect(): boolean {
    return isWetvHost(window.location.hostname);
  }

  isWatchPage(): boolean {
    const path = window.location.pathname;
    return path.length > 1 && path !== '/';
  }

  getPatterns(): SubtitleUrlPattern[] {
    return [
      {
        platform: 'wetv',
        pattern: /\.vtt(?:\?|$)/i,
        languageExtractor: (url) => {
          const lang =
            url.searchParams.get('lang') ||
            url.searchParams.get('language') ||
            url.searchParams.get('code') ||
            '';
          if (lang) return lang.replace(/_/g, '-');
          const file = url.pathname.split('/').pop() || '';
          const m = file.match(/[_-]([a-z]{2,3}([-_][A-Za-z]{2,4})?)\.vtt$/i);
          return m?.[1]?.replace(/_/g, '-') || '';
        },
      },
    ];
  }

  transformResponse(body: string, _contentType: string, _url: string): SubtitleCue[] {
    return parseSubtitles(body);
  }

  /** Immersive hides `.text-track` while the bilingual overlay is active. */
  getNativeCaptionHide(): { selector: string; method: 'display' | 'visibility' } {
    return { selector: '.text-track', method: 'display' };
  }

  extractAvailableTracks(
    _body: string,
    _contentType: string,
    url: string,
  ): AvailableSubtitleTrack[] {
    if (!/\.vtt/i.test(url)) return [];
    const parsed = new URL(url, window.location.origin);
    const pattern = this.getPatterns()[0];
    const language = pattern.languageExtractor?.(parsed) || '';
    return [
      {
        language,
        label: language || 'subtitle',
        url,
        isAutoGenerated: false,
        platform: 'wetv',
      },
    ];
  }
}