import type {
  SubtitleCue,
  SubtitleUrlPattern,
  AvailableSubtitleTrack,
  DomCueSource,
} from '@/types/subtitle';
import type { SubtitleHandler } from './registry';

/**
 * Youku internal subtitle codes (as seen in the language picker `data-val`)
 * → BCP-47. CHS is exposed as `data-val="default"` on the Simplified-Chinese
 * item; KR maps to ISO 639-1 `ko` and PO to `pt`. The rest are identity.
 *
 * AR and MS are flagged "auto-translated" by Youku — kept here as first-class
 * mappings so they still resolve when present in the picker.
 */
const YOUKU_CODE_TO_LANGUAGE: Record<string, string> = {
  default: 'zh-Hans',
  chs: 'zh-Hans',
  cht: 'zh-Hant',
  en: 'en',
  kr: 'ko',
  es: 'es',
  po: 'pt',
  th: 'th',
  ar: 'ar',
  id: 'id',
  vi: 'vi',
  ms: 'ms',
};

/**
 * Map a Youku subtitle code (from the picker's `data-val`) to a BCP-47 tag.
 * Case-insensitive. Unknown codes fall back to their lowercased form so a
 * novel two-letter code still surfaces; the empty string stays empty.
 */
export function youkuCodeToLanguage(code: string): string {
  if (!code) return '';
  const key = code.toLowerCase();
  return YOUKU_CODE_TO_LANGUAGE[key] ?? key;
}

/**
 * Youku subtitle handler — DRM/MSE H5 player (KUI framework) that renders
 * captions as SVG `<text>/<tspan>` inside `<div id="subtitle">`. There is no
 * `<track>`/`textTracks` and no interceptable VTT URL in the static HTML, so
 * this is a DOM cue-scraping handler (mirrors {@link HboMaxHandler}).
 *
 * Phase 2 (optional) may add `getPatterns()`/`transformResponse()` if a live
 * DevTools session reveals the subtitle API endpoint.
 */
export class YoukuHandler implements SubtitleHandler {
  readonly platform = 'youku';

  detect(): boolean {
    const host = window.location.hostname;
    return (
      host === 'youku.tv' ||
      host.endsWith('.youku.tv') ||
      host === 'youku.com' ||
      host.endsWith('.youku.com')
    );
  }

  isWatchPage(): boolean {
    // Canonical Youku watch path is /v_show/id_<videoId>(.html), optionally
    // prefixed with /v on youku.tv (/v/v_show/id_*). Both contain "/v_show/id_".
    return window.location.pathname.includes('/v_show/id_');
  }

  getPatterns(): SubtitleUrlPattern[] {
    // No URL interception in Phase 1 — captions are scraped from the DOM.
    return [];
  }

  transformResponse(_body: string, _contentType: string, _url: string): SubtitleCue[] {
    return [];
  }

  extractAvailableTracks(
    _body: string,
    _contentType: string,
    _url: string,
  ): AvailableSubtitleTrack[] {
    const videoId = this.extractVideoId();
    const tracks: AvailableSubtitleTrack[] = [];

    // Youku's subtitle picker is a panel marked com="subtitle" containing
    // language items (commonly <li>) each carrying a data-val language code.
    const items = document.querySelectorAll<HTMLElement>('[com="subtitle"] [data-val]');
    for (const item of items) {
      const code = item.getAttribute('data-val') || '';
      const label = (item.textContent || '').trim();
      if (!code) continue; // structural item without a language binding
      tracks.push({
        language: youkuCodeToLanguage(code),
        label: label || youkuCodeToLanguage(code),
        url: undefined, // DOM-sourced — no fetch URL
        isAutoGenerated: false,
        platform: 'youku',
        videoId,
      });
    }
    return tracks;
  }

  getDomCueSource(): DomCueSource {
    return {
      // Cue text is the aggregated textContent of the SVG caption container.
      cueSelector: '#subtitle',
      // The native caption window we hide (visibility:hidden) while active.
      captionWindowSelector: '#subtitle',
      // Observe the stable player container so the observer survives inner
      // SVG replacement by the KUI player across cue transitions.
      observeRootSelector: '#ykPlayer',
      readActiveLanguage: () => this.readActiveLanguage(),
      videoIdExtractor: () => this.extractVideoId(),
    };
  }

  /**
   * Read the active subtitle language from the picker. Youku marks the active
   * item with a class (current/active/on) or aria-selected="true". Returns ''
   * when the picker is absent or no item is active (treated as "captions off"
   * by the coordinator's auto-activate precondition).
   */
  private readActiveLanguage(): string {
    const items = document.querySelectorAll<HTMLElement>('[com="subtitle"] [data-val]');
    for (const item of items) {
      if (this.isItemActive(item)) {
        const code = item.getAttribute('data-val') || '';
        return youkuCodeToLanguage(code);
      }
    }
    return '';
  }

  /** Whether a picker item represents the currently-active subtitle track. */
  private isItemActive(item: HTMLElement): boolean {
    if (item.getAttribute('aria-selected') === 'true') return true;
    const cls = item.className || '';
    if (typeof cls !== 'string') return false;
    return /\b(current|active|on|selected)\b/i.test(cls);
  }

  /** Extract the video id from a /v_show/id_<id>(.html) watch path.
   *  The id is base64-like (e.g. XNjQ4MDkzODY2NA==) and never contains a dot
   *  or slash, so the match stops at the `.html` suffix or path end. */
  private extractVideoId(): string | undefined {
    const match = window.location.pathname.match(/\/v_show\/id_([^/.]+)/);
    return match?.[1];
  }
}
