import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { InterceptorRegistry } from '@/inject/interceptorRegistry';
import { YouTubeHandler } from '@/inject/subtitleHandlers/youtube';
import {
  requestYoutubeNativeCaptions,
  restoreYoutubeNativeCaptions,
  startYoutubeMetadataDiscovery,
} from '@/inject/youtubePlayer';

// @vitest-environment jsdom

describe('InterceptorRegistry metadata URL matching', () => {
  it('matches a host-qualified pattern when the request URL is relative', () => {
    const registry = new InterceptorRegistry();
    registry.registerMetadataPattern({
      platform: 'deeplearningai',
      pattern: /localhost(?::\d+)?\/api\/trpc\/.*getLessonVideo/i,
    });

    expect(registry.matchMetadataUrl('/api/trpc/course.getLessonVideo?batch=1')).toMatchObject({
      platform: 'deeplearningai',
    });
  });
});

/**
 * @vitest-environment jsdom
 */

describe('messageBridge early coordinator queue', () => {
  let posted: unknown[];
  let originalPostMessage: typeof window.postMessage;

  beforeEach(async () => {
    vi.resetModules();
    posted = [];
    originalPostMessage = window.postMessage.bind(window);
    window.postMessage = ((data: unknown) => {
      posted.push(data);
      // Also dispatch so COORDINATOR_READY reaches the bridge listener.
      window.dispatchEvent(new MessageEvent('message', { data, origin: window.location.origin }));
    }) as typeof window.postMessage;

    // Ensure origin matches MessageEvent origin in jsdom.
    Object.defineProperty(window, 'location', {
      value: { ...window.location, origin: 'https://www.youtube.com', href: 'https://www.youtube.com/watch?v=abc' },
      writable: true,
      configurable: true,
    });
  });

  afterEach(async () => {
    window.postMessage = originalPostMessage;
    const bridge = await import('@/inject/messageBridge');
    bridge.__resetMessageBridgeForTests?.();
    vi.resetModules();
  });

  it('queues SUBTITLE_INTERCEPTED / SUBTITLE_TRACKS_DISCOVERED until COORDINATOR_READY then posts immediately (no double queue), and posts YouTube player commands immediately from the isolated side', async () => {
    const bridge = await import('@/inject/messageBridge');
    bridge.__resetMessageBridgeForTests();

    const requestId = bridge.sendMessage('SUBTITLE_INTERCEPTED', {
      url: 'https://www.youtube.com/api/timedtext?lang=en&kind=asr&v=abc',
      body: '{"events":[]}',
      contentType: 'application/json',
      platform: 'youtube',
      originalLanguage: 'en',
    });

    // Not ready yet — must not deliver to isolated world.
    expect(posted).toHaveLength(0);

    // Coordinator attaches and announces ready (same-origin postMessage).
    window.dispatchEvent(
      new MessageEvent('message', {
        origin: window.location.origin,
        data: {
          channel: 'anyllm-translate',
          type: 'COORDINATOR_READY',
          requestId: 'ready-1',
          payload: {},
        },
      }),
    );

    expect(posted).toHaveLength(1);
    expect(posted[0]).toEqual(
      expect.objectContaining({
        type: 'SUBTITLE_INTERCEPTED',
        requestId,
        channel: 'anyllm-translate',
        payload: expect.objectContaining({
          platform: 'youtube',
          originalLanguage: 'en',
        }),
      }),
    );

    // SUBTITLE_TRACKS_DISCOVERED follows the same queue-until-ready path
    bridge.__resetMessageBridgeForTests();
    posted.length = 0;

    bridge.sendMessage('SUBTITLE_TRACKS_DISCOVERED', {
      tracks: [{ language: 'en', label: 'English', isAutoGenerated: true, platform: 'youtube' }],
      platform: 'youtube',
    });

    expect(posted).toHaveLength(0);

    window.dispatchEvent(
      new MessageEvent('message', {
        origin: window.location.origin,
        data: {
          channel: 'anyllm-translate',
          type: 'COORDINATOR_READY',
          requestId: 'ready-2',
          payload: {},
        },
      }),
    );

    expect(posted).toHaveLength(1);
    expect((posted[0] as { type: string }).type).toBe('SUBTITLE_TRACKS_DISCOVERED');

    // After ready, subsequent messages post immediately — no double queue.
    posted.length = 0;
    bridge.sendMessage('SUBTITLE_INTERCEPTED', {
      url: 'https://www.youtube.com/api/timedtext?lang=en&kind=asr',
      body: '{}',
      contentType: 'application/json',
      platform: 'youtube',
      originalLanguage: 'en',
    });

    expect(posted).toHaveLength(1);
    expect((posted[0] as { type: string }).type).toBe('SUBTITLE_INTERCEPTED');

    // YouTube player commands post immediately from the isolated side.
    bridge.__resetMessageBridgeForTests();
    posted.length = 0;

    bridge.sendMessage('YOUTUBE_REQUEST_CAPTIONS', {});
    bridge.sendMessage('YOUTUBE_RESTORE_CAPTIONS', {});

    expect(posted.map((message) => (message as { type: string }).type)).toEqual([
      'YOUTUBE_REQUEST_CAPTIONS',
      'YOUTUBE_RESTORE_CAPTIONS',
    ]);
  });

  it('queues Max manifest lifecycle and cue messages until COORDINATOR_READY', async () => {
    const bridge = await import('@/inject/messageBridge');
    bridge.__resetMessageBridgeForTests();
    posted.length = 0;

    bridge.sendMessage('SUBTITLE_MPD_PROCESSING', { status: 'started', platform: 'hbomax' });
    bridge.sendMessage('SUBTITLE_MANIFEST_CUES', {
      cues: [{ startTime: 1, endTime: 2, text: 'hello' }],
      platform: 'hbomax',
      language: 'en',
    });

    expect(posted).toHaveLength(0);

    window.dispatchEvent(
      new MessageEvent('message', {
        origin: window.location.origin,
        data: {
          channel: 'anyllm-translate',
          type: 'COORDINATOR_READY',
          requestId: 'ready-max',
          payload: {},
        },
      }),
    );

    expect(posted.map((message) => (message as { type: string }).type)).toEqual([
      'SUBTITLE_MPD_PROCESSING',
      'SUBTITLE_MANIFEST_CUES',
    ]);
  });

  it('delivers SUBTITLE_CAPTURE_RESET immediately, even before COORDINATOR_READY', async () => {
    const bridge = await import('@/inject/messageBridge');
    bridge.__resetMessageBridgeForTests();
    posted.length = 0;

    // ISOLATED → MAIN: the MAIN world drops capture state for the old title.
    // It must never sit in the early queue (the queue only exists to protect
    // MAIN → ISOLATED first-load captures).
    bridge.sendMessage('SUBTITLE_CAPTURE_RESET', { platform: 'hbomax' });

    expect(posted.map((message) => (message as { type: string }).type)).toEqual([
      'SUBTITLE_CAPTURE_RESET',
    ]);
  });
});

/**
 * @vitest-environment jsdom
 */

describe('YouTubeHandler native caption hide', () => {
  let handler: YouTubeHandler;

  beforeEach(() => {
    handler = new YouTubeHandler();
  });

  it('exposes getNativeCaptionHide targeting YouTube caption windows', () => {
    expect(typeof handler.getNativeCaptionHide).toBe('function');
    const hide = handler.getNativeCaptionHide!();
    expect(hide.method ?? 'display').toBe('display');
    expect(hide.selector).toMatch(/ytp-caption-window-container/);
    expect(hide.selector).toMatch(/caption-window/);
  });
});

describe('YouTubeHandler watch-page detection', () => {
  it('accepts /watch, /live/ID and /shorts/ID but not listing pages', () => {
    const setPath = (pathname: string) =>
      Object.defineProperty(window, 'location', {
        value: { hostname: 'www.youtube.com', pathname },
        writable: true,
        configurable: true,
      });
    const handler = new YouTubeHandler();

    setPath('/watch');
    expect(handler.isWatchPage()).toBe(true);
    setPath('/live/abc123');
    expect(handler.isWatchPage()).toBe(true);
    setPath('/shorts/abc123');
    expect(handler.isWatchPage()).toBe(true);
    setPath('/results');
    expect(handler.isWatchPage()).toBe(false);
    setPath('/');
    expect(handler.isWatchPage()).toBe(false);
  });
});

describe('YouTubeHandler timedtext parsing', () => {
  it('parses real srv3 <p t d> bodies into cues and word events', () => {
    const handler = new YouTubeHandler();
    const srv3 =
      '<?xml version="1.0"?><timedtext format="3"><body>' +
      '<p t="1230" d="4560"><s t="0">Hello</s><s t="500">world</s></p>' +
      '</body></timedtext>';

    const cues = handler.transformResponse(
      srv3,
      'text/xml',
      'https://www.youtube.com/api/timedtext?v=x&lang=en&kind=asr&fmt=srv3',
    );
    expect(cues).toHaveLength(1);
    expect(cues[0]).toMatchObject({ startTime: 1.23, endTime: 5.79, text: 'Hello world' });

    expect(handler.parseWordEvents(srv3).map((w) => w.text)).toEqual(['Hello', 'world']);
  });

  it('still parses srv1 <text start dur> bodies', () => {
    const handler = new YouTubeHandler();
    const srv1 = '<transcript><text start="1" dur="2">Hi there</text></transcript>';
    const cues = handler.transformResponse(
      srv1,
      'text/xml',
      'https://www.youtube.com/api/timedtext?v=x&lang=en&fmt=srv1',
    );
    expect(cues).toHaveLength(1);
    expect(cues[0]).toMatchObject({ startTime: 1, endTime: 3, text: 'Hi there' });
  });
});

const bridge = { send: vi.fn(() => 'request-1') };

function embeddedResponse() {
  return {
    videoDetails: { videoId: 'ltJukPGSqEg' },
    captions: {
      playerCaptionsTracklistRenderer: {
        captionTracks: [
          {
            baseUrl:
              'https://www.youtube.com/api/timedtext?v=ltJukPGSqEg&lang=en&kind=asr',
            languageCode: 'en',
            kind: 'asr',
            name: { simpleText: 'English (auto-generated)' },
          },
        ],
      },
    },
  };
}

function responseWithoutCaptions(videoId = 'ltJukPGSqEg') {
  return { videoDetails: { videoId } };
}

function embeddedResponseForVideo(videoId: string) {
  return {
    ...embeddedResponse(),
    videoDetails: { videoId },
    captions: {
      playerCaptionsTracklistRenderer: {
        captionTracks: [{
          baseUrl: `https://www.youtube.com/api/timedtext?v=${videoId}&lang=en&kind=asr`,
          languageCode: 'en',
          kind: 'asr',
          name: { simpleText: 'English (auto-generated)' },
        }],
      },
    },
  };
}

beforeEach(() => {
  vi.useFakeTimers();
  vi.clearAllMocks();
  restoreYoutubeNativeCaptions();
  document.body.innerHTML = '';
  delete (window as Window & { ytInitialPlayerResponse?: unknown })
    .ytInitialPlayerResponse;
  delete (window as Window & { ytplayer?: unknown }).ytplayer;
});

afterEach(() => {
  vi.useRealTimers();
});

describe('YouTube metadata discovery', () => {
  it('emits caption tracks from ytInitialPlayerResponse, raw_player_response, or falls back when the initial response has no captions', () => {
    (window as Window & { ytInitialPlayerResponse?: unknown }).ytInitialPlayerResponse =
      embeddedResponse();

    let cleanup = startYoutubeMetadataDiscovery(new YouTubeHandler(), bridge);

    expect(bridge.send).toHaveBeenCalledWith(
      'SUBTITLE_TRACKS_DISCOVERED',
      expect.objectContaining({
        platform: 'youtube',
        videoId: 'ltJukPGSqEg',
        tracks: [
          expect.objectContaining({
            language: 'en',
            isAutoGenerated: true,
            videoId: 'ltJukPGSqEg',
          }),
        ],
      }),
    );

    cleanup();

    // raw_player_response is read when the initial global is unavailable.
    bridge.send.mockClear();
    (window as Window & { ytInitialPlayerResponse?: unknown }).ytInitialPlayerResponse =
      undefined;
    (window as Window & { ytplayer?: unknown }).ytplayer = {
      config: { args: { raw_player_response: JSON.stringify(embeddedResponse()) } },
    };
    cleanup = startYoutubeMetadataDiscovery(new YouTubeHandler(), bridge);

    expect(bridge.send).toHaveBeenCalledWith(
      'SUBTITLE_TRACKS_DISCOVERED',
      expect.objectContaining({ videoId: 'ltJukPGSqEg' }),
    );
    cleanup();

    // Falls back to raw_player_response when the initial response has no captions.
    bridge.send.mockClear();
    (window as Window & { ytInitialPlayerResponse?: unknown }).ytInitialPlayerResponse =
      responseWithoutCaptions();
    cleanup = startYoutubeMetadataDiscovery(new YouTubeHandler(), bridge);

    expect(bridge.send).toHaveBeenCalledTimes(1);
    expect(bridge.send).toHaveBeenCalledWith(
      'SUBTITLE_TRACKS_DISCOVERED',
      expect.objectContaining({ videoId: 'ltJukPGSqEg' }),
    );
    cleanup();
  });

  it('retries discovery and emits once when metadata appears later (including after navigation), does not re-emit duplicate or stale metadata, and stops retrying after cleanup', () => {
    // No metadata at start; discovery keeps polling.
    let cleanup = startYoutubeMetadataDiscovery(new YouTubeHandler(), bridge);
    vi.advanceTimersByTime(250);
    expect(bridge.send).not.toHaveBeenCalled();

    (window as Window & { ytInitialPlayerResponse?: unknown }).ytInitialPlayerResponse =
      embeddedResponse();
    vi.advanceTimersByTime(250);
    expect(bridge.send).toHaveBeenCalledTimes(1);
    cleanup();

    // After navigation, delayed metadata with a new key is emitted once.
    bridge.send.mockClear();
    (window as Window & { ytInitialPlayerResponse?: unknown }).ytInitialPlayerResponse =
      embeddedResponseForVideo('old-video');
    cleanup = startYoutubeMetadataDiscovery(new YouTubeHandler(), bridge);
    expect(bridge.send).toHaveBeenCalledTimes(1);

    window.dispatchEvent(new Event('yt-navigate-finish'));
    vi.advanceTimersByTime(250);
    expect(bridge.send).toHaveBeenCalledTimes(1);

    (window as Window & { ytplayer?: unknown }).ytplayer = {
      config: {
        args: {
          raw_player_response: JSON.stringify(embeddedResponseForVideo('new-video')),
        },
      },
    };
    vi.advanceTimersByTime(250);

    expect(bridge.send).toHaveBeenCalledTimes(2);
    expect(bridge.send).toHaveBeenLastCalledWith(
      'SUBTITLE_TRACKS_DISCOVERED',
      expect.objectContaining({ videoId: 'new-video' }),
    );
    cleanup();

    // Same response re-discovered (yt-navigate-finish) is not re-emitted.
    delete (window as Window & { ytplayer?: unknown }).ytplayer;
    bridge.send.mockClear();
    (window as Window & { ytInitialPlayerResponse?: unknown }).ytInitialPlayerResponse =
      embeddedResponse();
    cleanup = startYoutubeMetadataDiscovery(new YouTubeHandler(), bridge);
    window.dispatchEvent(new Event('yt-navigate-finish'));
    vi.advanceTimersByTime(250);

    expect(bridge.send).toHaveBeenCalledTimes(1);
    cleanup();

    // Stale metadata is not re-emitted after a newer response is discovered.
    bridge.send.mockClear();
    (window as Window & { ytInitialPlayerResponse?: unknown }).ytInitialPlayerResponse =
      embeddedResponseForVideo('old-video');
    cleanup = startYoutubeMetadataDiscovery(new YouTubeHandler(), bridge);
    expect(bridge.send).toHaveBeenCalledTimes(1);

    (window as Window & { ytplayer?: unknown }).ytplayer = {
      config: {
        args: {
          raw_player_response: JSON.stringify(embeddedResponseForVideo('new-video')),
        },
      },
    };
    window.dispatchEvent(new Event('yt-navigate-finish'));
    vi.advanceTimersByTime(250);
    expect(bridge.send).toHaveBeenCalledTimes(2);

    window.dispatchEvent(new Event('yt-navigate-finish'));
    vi.advanceTimersByTime(250);

    expect(bridge.send).toHaveBeenCalledTimes(2);
    cleanup();

    // Cleanup stops the retry loop entirely.
    bridge.send.mockClear();
    delete (window as Window & { ytInitialPlayerResponse?: unknown }).ytInitialPlayerResponse;
    delete (window as Window & { ytplayer?: unknown }).ytplayer;
    const cleanup3 = startYoutubeMetadataDiscovery(new YouTubeHandler(), bridge);
    cleanup3();
    vi.advanceTimersByTime(10_000);

    expect(bridge.send).not.toHaveBeenCalled();
  });
});

describe('native caption fallback', () => {
  function addButton(pressed: 'true' | 'false') {
    const button = document.createElement('button');
    button.className = 'ytp-subtitles-button ytp-button';
    button.setAttribute('aria-pressed', pressed);
    button.addEventListener('click', () => {
      button.setAttribute(
        'aria-pressed',
        button.getAttribute('aria-pressed') === 'true' ? 'false' : 'true',
      );
    });
    document.body.appendChild(button);
    return button;
  }

  it('clicks the YouTube caption button only when captions are off, and restores only what the extension enabled', () => {
    // Captions off → button is pressed.
    const offButton = addButton('false');
    requestYoutubeNativeCaptions();
    expect(offButton.getAttribute('aria-pressed')).toBe('true');

    // Captions already on → no click.
    const onButton = addButton('true');
    const click = vi.spyOn(onButton, 'click');
    requestYoutubeNativeCaptions();
    expect(click).not.toHaveBeenCalled();

    // The extension-enabled press is restored.
    restoreYoutubeNativeCaptions();
    expect(offButton.getAttribute('aria-pressed')).toBe('false');
  });
});
