/**
 * @vitest-environment jsdom
 */
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';

describe('messageBridge early coordinator queue', () => {
  let posted: unknown[];
  let originalPostMessage: typeof window.postMessage;

  beforeEach(async () => {
    vi.resetModules();
    posted = [];
    originalPostMessage = window.postMessage.bind(window);
    window.postMessage = ((data: unknown) => {
      posted.push(data);
      // Also dispatch so COORDINATOR_READY reaches the bridge listener.
      window.dispatchEvent(new MessageEvent('message', { data, origin: window.location.origin }));
    }) as typeof window.postMessage;

    // Ensure origin matches MessageEvent origin in jsdom.
    Object.defineProperty(window, 'location', {
      value: { ...window.location, origin: 'https://www.youtube.com', href: 'https://www.youtube.com/watch?v=abc' },
      writable: true,
      configurable: true,
    });
  });

  afterEach(async () => {
    window.postMessage = originalPostMessage;
    const bridge = await import('@/inject/messageBridge');
    bridge.__resetMessageBridgeForTests?.();
    vi.resetModules();
  });

  it('queues SUBTITLE_INTERCEPTED / SUBTITLE_TRACKS_DISCOVERED until COORDINATOR_READY, then posts immediately (no double queue)', async () => {
    const bridge = await import('@/inject/messageBridge');
    bridge.__resetMessageBridgeForTests();

    const requestId = bridge.sendMessage('SUBTITLE_INTERCEPTED', {
      url: 'https://www.youtube.com/api/timedtext?lang=en&kind=asr&v=abc',
      body: '{"events":[]}',
      contentType: 'application/json',
      platform: 'youtube',
      originalLanguage: 'en',
    });

    // Not ready yet — must not deliver to isolated world.
    expect(posted).toHaveLength(0);

    // Coordinator attaches and announces ready (same-origin postMessage).
    window.dispatchEvent(
      new MessageEvent('message', {
        origin: window.location.origin,
        data: {
          channel: 'anyllm-translate',
          type: 'COORDINATOR_READY',
          requestId: 'ready-1',
          payload: {},
        },
      }),
    );

    expect(posted).toHaveLength(1);
    expect(posted[0]).toEqual(
      expect.objectContaining({
        type: 'SUBTITLE_INTERCEPTED',
        requestId,
        channel: 'anyllm-translate',
        payload: expect.objectContaining({
          platform: 'youtube',
          originalLanguage: 'en',
        }),
      }),
    );

    // SUBTITLE_TRACKS_DISCOVERED follows the same queue-until-ready path
    bridge.__resetMessageBridgeForTests();
    posted.length = 0;

    bridge.sendMessage('SUBTITLE_TRACKS_DISCOVERED', {
      tracks: [{ language: 'en', label: 'English', isAutoGenerated: true, platform: 'youtube' }],
      platform: 'youtube',
    });

    expect(posted).toHaveLength(0);

    window.dispatchEvent(
      new MessageEvent('message', {
        origin: window.location.origin,
        data: {
          channel: 'anyllm-translate',
          type: 'COORDINATOR_READY',
          requestId: 'ready-2',
          payload: {},
        },
      }),
    );

    expect(posted).toHaveLength(1);
    expect((posted[0] as { type: string }).type).toBe('SUBTITLE_TRACKS_DISCOVERED');

    // After ready, subsequent messages post immediately — no double queue.
    posted.length = 0;
    bridge.sendMessage('SUBTITLE_INTERCEPTED', {
      url: 'https://www.youtube.com/api/timedtext?lang=en&kind=asr',
      body: '{}',
      contentType: 'application/json',
      platform: 'youtube',
      originalLanguage: 'en',
    });

    expect(posted).toHaveLength(1);
    expect((posted[0] as { type: string }).type).toBe('SUBTITLE_INTERCEPTED');
  });

  it('posts YouTube player commands immediately from the isolated side', async () => {
    const bridge = await import('@/inject/messageBridge');
    bridge.__resetMessageBridgeForTests();
    posted.length = 0;

    bridge.sendMessage('YOUTUBE_REQUEST_CAPTIONS', {});
    bridge.sendMessage('YOUTUBE_RESTORE_CAPTIONS', {});

    expect(posted.map((message) => (message as { type: string }).type)).toEqual([
      'YOUTUBE_REQUEST_CAPTIONS',
      'YOUTUBE_RESTORE_CAPTIONS',
    ]);
  });
});
