import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { YouTubeHandler } from '@/inject/subtitleHandlers/youtube';
import {
  requestYoutubeNativeCaptions,
  restoreYoutubeNativeCaptions,
  startYoutubeMetadataDiscovery,
} from '@/inject/youtubePlayer';

const bridge = { send: vi.fn(() => 'request-1') };

function embeddedResponse() {
  return {
    videoDetails: { videoId: 'ltJukPGSqEg' },
    captions: {
      playerCaptionsTracklistRenderer: {
        captionTracks: [
          {
            baseUrl:
              'https://www.youtube.com/api/timedtext?v=ltJukPGSqEg&lang=en&kind=asr',
            languageCode: 'en',
            kind: 'asr',
            name: { simpleText: 'English (auto-generated)' },
          },
        ],
      },
    },
  };
}

function responseWithoutCaptions(videoId = 'ltJukPGSqEg') {
  return { videoDetails: { videoId } };
}

function embeddedResponseForVideo(videoId: string) {
  return {
    ...embeddedResponse(),
    videoDetails: { videoId },
    captions: {
      playerCaptionsTracklistRenderer: {
        captionTracks: [{
          baseUrl: `https://www.youtube.com/api/timedtext?v=${videoId}&lang=en&kind=asr`,
          languageCode: 'en',
          kind: 'asr',
          name: { simpleText: 'English (auto-generated)' },
        }],
      },
    },
  };
}

beforeEach(() => {
  vi.useFakeTimers();
  vi.clearAllMocks();
  restoreYoutubeNativeCaptions();
  document.body.innerHTML = '';
  delete (window as Window & { ytInitialPlayerResponse?: unknown })
    .ytInitialPlayerResponse;
  delete (window as Window & { ytplayer?: unknown }).ytplayer;
});

afterEach(() => {
  vi.useRealTimers();
});

describe('YouTube metadata discovery', () => {
  it('emits caption tracks from ytInitialPlayerResponse', () => {
    (window as Window & { ytInitialPlayerResponse?: unknown }).ytInitialPlayerResponse =
      embeddedResponse();

    const cleanup = startYoutubeMetadataDiscovery(new YouTubeHandler(), bridge);

    expect(bridge.send).toHaveBeenCalledWith(
      'SUBTITLE_TRACKS_DISCOVERED',
      expect.objectContaining({
        platform: 'youtube',
        videoId: 'ltJukPGSqEg',
        tracks: [
          expect.objectContaining({
            language: 'en',
            isAutoGenerated: true,
            videoId: 'ltJukPGSqEg',
          }),
        ],
      }),
    );

    cleanup();
  });

  it('reads raw_player_response when the initial global is unavailable', () => {
    (window as Window & { ytplayer?: unknown }).ytplayer = {
      config: { args: { raw_player_response: JSON.stringify(embeddedResponse()) } },
    };

    const cleanup = startYoutubeMetadataDiscovery(new YouTubeHandler(), bridge);

    expect(bridge.send).toHaveBeenCalledWith(
      'SUBTITLE_TRACKS_DISCOVERED',
      expect.objectContaining({ videoId: 'ltJukPGSqEg' }),
    );

    cleanup();
  });

  it('falls back to raw_player_response when the initial response has no captions', () => {
    (window as Window & { ytInitialPlayerResponse?: unknown }).ytInitialPlayerResponse =
      responseWithoutCaptions();
    (window as Window & { ytplayer?: unknown }).ytplayer = {
      config: { args: { raw_player_response: JSON.stringify(embeddedResponse()) } },
    };

    const cleanup = startYoutubeMetadataDiscovery(new YouTubeHandler(), bridge);

    expect(bridge.send).toHaveBeenCalledTimes(1);
    expect(bridge.send).toHaveBeenCalledWith(
      'SUBTITLE_TRACKS_DISCOVERED',
      expect.objectContaining({ videoId: 'ltJukPGSqEg' }),
    );
    cleanup();
  });

  it('retries discovery and emits once when metadata appears later', () => {
    const cleanup = startYoutubeMetadataDiscovery(new YouTubeHandler(), bridge);

    vi.advanceTimersByTime(250);
    expect(bridge.send).not.toHaveBeenCalled();

    (window as Window & { ytInitialPlayerResponse?: unknown }).ytInitialPlayerResponse =
      embeddedResponse();
    vi.advanceTimersByTime(250);

    expect(bridge.send).toHaveBeenCalledTimes(1);
    cleanup();
  });

  it('does not emit duplicate metadata for the same video response', () => {
    (window as Window & { ytInitialPlayerResponse?: unknown }).ytInitialPlayerResponse =
      embeddedResponse();

    const cleanup = startYoutubeMetadataDiscovery(new YouTubeHandler(), bridge);
    window.dispatchEvent(new Event('yt-navigate-finish'));
    vi.advanceTimersByTime(250);

    expect(bridge.send).toHaveBeenCalledTimes(1);
    cleanup();
  });

  it('keeps retrying after navigation until delayed metadata has a new key', () => {
    (window as Window & { ytInitialPlayerResponse?: unknown }).ytInitialPlayerResponse =
      embeddedResponseForVideo('old-video');

    const cleanup = startYoutubeMetadataDiscovery(new YouTubeHandler(), bridge);
    expect(bridge.send).toHaveBeenCalledTimes(1);

    window.dispatchEvent(new Event('yt-navigate-finish'));
    vi.advanceTimersByTime(250);
    expect(bridge.send).toHaveBeenCalledTimes(1);

    (window as Window & { ytplayer?: unknown }).ytplayer = {
      config: {
        args: {
          raw_player_response: JSON.stringify(embeddedResponseForVideo('new-video')),
        },
      },
    };
    vi.advanceTimersByTime(250);

    expect(bridge.send).toHaveBeenCalledTimes(2);
    expect(bridge.send).toHaveBeenLastCalledWith(
      'SUBTITLE_TRACKS_DISCOVERED',
      expect.objectContaining({ videoId: 'new-video' }),
    );
    cleanup();
  });

  it('does not re-emit stale metadata after discovering a newer response', () => {
    (window as Window & { ytInitialPlayerResponse?: unknown }).ytInitialPlayerResponse =
      embeddedResponseForVideo('old-video');

    const cleanup = startYoutubeMetadataDiscovery(new YouTubeHandler(), bridge);
    (window as Window & { ytplayer?: unknown }).ytplayer = {
      config: {
        args: {
          raw_player_response: JSON.stringify(embeddedResponseForVideo('new-video')),
        },
      },
    };
    window.dispatchEvent(new Event('yt-navigate-finish'));
    vi.advanceTimersByTime(250);
    expect(bridge.send).toHaveBeenCalledTimes(2);

    window.dispatchEvent(new Event('yt-navigate-finish'));
    vi.advanceTimersByTime(250);

    expect(bridge.send).toHaveBeenCalledTimes(2);
    cleanup();
  });

  it('stops retrying after cleanup', () => {
    const cleanup = startYoutubeMetadataDiscovery(new YouTubeHandler(), bridge);
    cleanup();
    vi.advanceTimersByTime(10_000);

    expect(bridge.send).not.toHaveBeenCalled();
  });
});

describe('native caption fallback', () => {
  function addButton(pressed: 'true' | 'false') {
    const button = document.createElement('button');
    button.className = 'ytp-subtitles-button ytp-button';
    button.setAttribute('aria-pressed', pressed);
    button.addEventListener('click', () => {
      button.setAttribute(
        'aria-pressed',
        button.getAttribute('aria-pressed') === 'true' ? 'false' : 'true',
      );
    });
    document.body.appendChild(button);
    return button;
  }

  it('clicks the YouTube caption button once when captions are off', () => {
    const button = addButton('false');
    requestYoutubeNativeCaptions();
    expect(button.getAttribute('aria-pressed')).toBe('true');
  });

  it('does not click the caption button when captions are already on', () => {
    const button = addButton('true');
    const click = vi.spyOn(button, 'click');
    requestYoutubeNativeCaptions();
    expect(click).not.toHaveBeenCalled();
  });

  it('restores captions only after the extension enabled them', () => {
    const button = addButton('false');
    requestYoutubeNativeCaptions();
    expect(button.getAttribute('aria-pressed')).toBe('true');

    restoreYoutubeNativeCaptions();

    expect(button.getAttribute('aria-pressed')).toBe('false');
  });
});
