/**
 * Subtitle-related type definitions.
 */

/** Internal normalized subtitle cue representation */
export interface SubtitleCue {
  startTime: number;
  endTime: number;
  text: string;
  originalText?: string;
  position?: { line?: number; position?: number; align?: string };
  voice?: string;
  metadata?: Record<string, string>;
}

/** Discovered subtitle track metadata (proactive discovery) */
export interface AvailableSubtitleTrack {
  /** Language code (ISO 639-1, e.g. 'en', 'vi', 'ja') */
  language: string;
  /** Human-readable label (e.g. 'English', 'Vietnamese') */
  label: string;
  /** Direct URL to the subtitle file (if known) */
  url?: string;
  /** Whether this is auto-generated (e.g. YouTube ASR) */
  isAutoGenerated: boolean;
  /** Platform identifier */
  platform: string;
  /** Scoped video identifier (e.g. YouTube video ID). Used to isolate tracks across multi-video pages. */
  videoId?: string;
}

/** Message types for postMessage bridge between MAIN and ISOLATED worlds */
export type BridgeMessageType =
  | 'SUBTITLE_INTERCEPTED'
  | 'SUBTITLE_TRANSLATED'
  | 'SUBTITLE_METADATA'
  | 'SUBTITLE_ERROR'
  | 'SUBTITLE_TRACKS_DISCOVERED'
  | 'SUBTITLE_DOM_CUES'
  | 'SUBTITLE_DOM_TRACK_CHANGED'
  | 'SUBTITLE_TEXTTRACK_CUES'
  | 'SUBTITLE_MSE_CUES'
  | 'SUBTITLE_CONFIG';

/** postMessage payload between worlds */
export interface BridgeMessage<T = unknown> {
  type: BridgeMessageType;
  requestId: string;
  channel: 'anyllm-translate';
  payload: T;
}

/** Payload for SUBTITLE_INTERCEPTED messages */
export interface SubtitleInterceptedPayload {
  url: string;
  contentType: string;
  body: string;
  platform: string;
  originalLanguage: string;
  /** Track language from the intercepted URL (if extractable) */
  trackLanguage?: string;
  /** Full track URL for identity comparison (race condition prevention) */
  trackUrl?: string;
}

/** Payload for SUBTITLE_TRANSLATED messages */
export interface SubtitleTranslatedPayload {
  vttContent: string;
  requestId: string;
}

/** Payload for SUBTITLE_METADATA messages */
export interface SubtitleMetadataPayload {
  url: string;
  language: string;
  isAutoGenerated: boolean;
  platform: string;
}

/** Payload for SUBTITLE_ERROR messages */
export interface SubtitleErrorPayload {
  message: string;
  url?: string;
  code: string;
}

/** Payload for SUBTITLE_TRACKS_DISCOVERED messages */
export interface SubtitleTracksDiscoveredPayload {
  tracks: AvailableSubtitleTrack[];
  platform: string;
  videoId?: string;
}
/** Payload for SUBTITLE_DOM_CUES messages (DOM-scraped cues from MAIN world) */
export interface SubtitleDomCuesPayload {
  cues: SubtitleCue[];
  platform: string;   // e.g. 'hbomax'
  language: string;   // active source language ('' if unknown)
  videoId?: string;
}

/** Payload when the user switches a DOM-sourced subtitle track mid-session */
export interface SubtitleDomTrackChangedPayload {
  platform: string;
  language: string;
  videoId?: string;
}

/** Payload for SUBTITLE_CONFIG messages (coordinator → MAIN world interceptors) */
export interface SubtitleConfigPayload {
  /** Translation timeout in milliseconds */
  translationTimeoutMs: number;
}

/** Payload for SUBTITLE_TEXTTRACK_CUES messages (full track cues from HTML5 TextTrack) */
export interface SubtitleTextTrackCuesPayload {
  cues: SubtitleCue[];
  language: string;
  label: string;
  /** URL of the <track> element if available */
  url?: string;
}

/** Platform subtitle URL pattern definition */
export interface SubtitleUrlPattern {
  platform: string;
  pattern: RegExp;
  languageExtractor?: (url: URL) => string;
}

/** Manifest-sourced subtitle track (from HLS/DASH manifest parsing) */
export interface ManifestSubtitleTrack {
  /** Subtitle playlist URL (e.g. .m3u8 media playlist or direct .vtt from DASH) */
  url: string;
  /** Language code (BCP-47 or ISO 639-1) */
  language: string;
  /** Human-readable label */
  label: string;
  /** Whether this is the default track */
  isDefault: boolean;
  /** Manifest format: 'hls' or 'dash' */
  format: 'hls' | 'dash';
  /** Platform identifier */
  platform: string;
}

/** Payload for FETCH_MANIFEST_SUBTITLES messages (coordinator → background) */
export interface FetchManifestSubtitlesMessage {
  type: 'FETCH_MANIFEST_SUBTITLES';
  playlistUrl: string;
}

/** Result of fetching manifest subtitle segments */
export interface ManifestSubtitleResult {
  success: boolean;
  cues?: Array<{ startTime: number; endTime: number; text: string }>;
  error?: string;
}

/** Payload for SUBTITLE_MSE_CUES messages (MSE SourceBuffer hook, Tier 3) */
export interface SubtitleMseCuesPayload {
  cues: SubtitleCue[];
  platform: string;
  language: string;
  videoId?: string;
}

/** Contract for DOM-scraped cue sources (platforms like Max with no VTT URL) */
export interface DomCueSource {
  /** Selector for the element whose textContent = current cue text */
  cueSelector: string;
  /** Selector for the native caption window/overlay to hide while active */
  captionWindowSelector: string;
  /** Selector for a stable ancestor to observe (survives cue node replacement by React) */
  observeRootSelector: string;
  /** Extract the active track's language from the DOM ('' if unknown/off) */
  readActiveLanguage(): string;
  /**
   * Extract a platform-specific video id from the current page (URL/DOM).
   * Used to scope DOM cues to a single video. Optional — defaults to undefined.
   */
  videoIdExtractor?: () => string | undefined;
  /**
   * Selector for subtitle-track buttons whose activation signals a track
   * switch mid-session (the rolling cue buffer is reset on switch). When
   * absent, no track-switch detection is performed — cue text still updates
   * via the main observer, but the buffer is not reset on a language change.
   * E.g. HBO Max `[data-testid="player-ux-text-track-button"]`,
   * Youku `[com="subtitle"] [data-val]`.
   */
  trackSwitchSelector?: string;
  /**
   * Attribute on {@link trackSwitchSelector} items whose value 'true' marks
   * the newly-active track. Defaults to 'aria-checked'; Youku's picker uses
   * 'aria-selected'.
   */
  trackSwitchAttribute?: string;
  /**
   * How to hide the native caption window while the overlay is active.
   * - `'display'` (default): `display: none !important` — fully removes the
   *   caption from layout. Correct when the caption renderer keeps populating
   *   the node while it is display:none (HBO Max).
   * - `'visibility'`: `visibility: hidden !important` — preserves box geometry
   *   and keeps the caption renderer producing cues. Required for platforms
   *   (Youku) that stop populating a `display:none` container, AND when the
   *   hide target IS the cue source (cueSelector === captionWindowSelector).
   */
  captionHideMethod?: 'display' | 'visibility';
}

/** Supported subtitle formats */
export type SubtitleFormat = 'vtt' | 'srt' | 'ttml';
