/**
 * Subtitle-related type definitions.
 */

/** Internal normalized subtitle cue representation */
export interface SubtitleCue {
  startTime: number;
  endTime: number;
  text: string;
  originalText?: string;
  position?: { line?: number; position?: number; align?: string };
  voice?: string;
  metadata?: Record<string, string>;
}

/** Discovered subtitle track metadata (proactive discovery) */
export interface AvailableSubtitleTrack {
  /** Language code (ISO 639-1, e.g. 'en', 'vi', 'ja') */
  language: string;
  /** Human-readable label (e.g. 'English', 'Vietnamese') */
  label: string;
  /** Direct URL to the subtitle file (if known) */
  url?: string;
  /** Whether this is auto-generated (e.g. YouTube ASR) */
  isAutoGenerated: boolean;
  /** Platform identifier */
  platform: string;
}

/** Message types for postMessage bridge between MAIN and ISOLATED worlds */
export type BridgeMessageType =
  | 'SUBTITLE_INTERCEPTED'
  | 'SUBTITLE_TRANSLATED'
  | 'SUBTITLE_METADATA'
  | 'SUBTITLE_ERROR'
  | 'SUBTITLE_TRACKS_DISCOVERED';

/** postMessage payload between worlds */
export interface BridgeMessage<T = unknown> {
  type: BridgeMessageType;
  requestId: string;
  channel: 'anyllm-translate';
  payload: T;
}

/** Payload for SUBTITLE_INTERCEPTED messages */
export interface SubtitleInterceptedPayload {
  url: string;
  contentType: string;
  body: string;
  platform: string;
  originalLanguage: string;
}

/** Payload for SUBTITLE_TRANSLATED messages */
export interface SubtitleTranslatedPayload {
  vttContent: string;
  requestId: string;
}

/** Payload for SUBTITLE_METADATA messages */
export interface SubtitleMetadataPayload {
  url: string;
  language: string;
  isAutoGenerated: boolean;
  platform: string;
}

/** Payload for SUBTITLE_ERROR messages */
export interface SubtitleErrorPayload {
  message: string;
  url?: string;
  code: string;
}

/** Payload for SUBTITLE_TRACKS_DISCOVERED messages */
export interface SubtitleTracksDiscoveredPayload {
  tracks: AvailableSubtitleTrack[];
  platform: string;
  videoId?: string;
}

/** Platform subtitle URL pattern definition */
export interface SubtitleUrlPattern {
  platform: string;
  pattern: RegExp;
  languageExtractor?: (url: URL) => string;
}

/** Supported subtitle formats */
export type SubtitleFormat = 'vtt' | 'srt';
