/**
 * Subtitle-related type definitions.
 */

/** Internal normalized subtitle cue representation */
export interface SubtitleCue {
  startTime: number;
  endTime: number;
  text: string;
  originalText?: string;
  position?: { line?: number; position?: number; align?: string };
  voice?: string;
  metadata?: Record<string, string>;
}

/** Message types for postMessage bridge between MAIN and ISOLATED worlds */
export type BridgeMessageType =
  | 'SUBTITLE_INTERCEPTED'
  | 'SUBTITLE_TRANSLATED'
  | 'SUBTITLE_METADATA'
  | 'SUBTITLE_ERROR';

/** postMessage payload between worlds */
export interface BridgeMessage<T = unknown> {
  type: BridgeMessageType;
  requestId: string;
  channel: 'anyllm-translate';
  payload: T;
}

/** Payload for SUBTITLE_INTERCEPTED messages */
export interface SubtitleInterceptedPayload {
  url: string;
  contentType: string;
  body: string;
  platform: string;
  originalLanguage: string;
}

/** Payload for SUBTITLE_TRANSLATED messages */
export interface SubtitleTranslatedPayload {
  vttContent: string;
  requestId: string;
}

/** Payload for SUBTITLE_METADATA messages */
export interface SubtitleMetadataPayload {
  url: string;
  language: string;
  isAutoGenerated: boolean;
  platform: string;
}

/** Payload for SUBTITLE_ERROR messages */
export interface SubtitleErrorPayload {
  message: string;
  url?: string;
  code: string;
}

/** Platform subtitle URL pattern definition */
export interface SubtitleUrlPattern {
  platform: string;
  pattern: RegExp;
  languageExtractor?: (url: URL) => string;
}

/** Supported subtitle formats */
export type SubtitleFormat = 'vtt' | 'srt';
