/**
 * TextTrack Discovery — HTML5 fallback for subtitle track detection.
 *
 * Scans for <video> elements and monitors their textTracks property
 * to discover available subtitle/caption tracks on any website.
 * Sends SUBTITLE_TRACKS_DISCOVERED over the bridge when tracks are found.
 *
 * This provides universal fallback coverage for sites not explicitly
 * handled by platform-specific handlers (Udemy, YouTube, Coursera).
 */

import type { MessageBridgeSender } from '@/inject/messageBridge';
import type { AvailableSubtitleTrack, SubtitleTracksDiscoveredPayload } from '@/types/subtitle';

/** Set of already-reported video elements to avoid duplicate messages */
const reportedVideos = new WeakSet<HTMLVideoElement>();

/** Scan a video element's textTracks and send discovery message */
function scanVideoTracks(video: HTMLVideoElement, bridge: MessageBridgeSender): void {
  const tracks: AvailableSubtitleTrack[] = [];

  const domTracks = Array.from(video.querySelectorAll('track'));

  for (let i = 0; i < video.textTracks.length; i++) {
    const track = video.textTracks[i];
    if (track.kind === 'subtitles' || track.kind === 'captions') {
      // Try to find the corresponding <track> element to get its src URL
      const domTrack = domTracks.find(
        (t) => t.srclang === track.language && t.kind === track.kind
      );

      tracks.push({
        language: track.language || '',
        label: track.label || track.language || '',
        url: domTrack?.src || undefined,
        isAutoGenerated: false,
        platform: 'html5',
      });
    }
  }

  if (tracks.length > 0) {
    bridge.send('SUBTITLE_TRACKS_DISCOVERED', {
      tracks,
      platform: 'html5',
    } as SubtitleTracksDiscoveredPayload);

    console.log('AnyLLMTranslate: TextTrack discovery found tracks', {
      count: tracks.length,
      languages: tracks.map((t) => t.language),
    });
  }
}

/** Attach track listeners to a video element */
function watchVideo(video: HTMLVideoElement, bridge: MessageBridgeSender): void {
  if (reportedVideos.has(video)) return;
  reportedVideos.add(video);

  // Scan existing tracks
  if (video.textTracks.length > 0) {
    scanVideoTracks(video, bridge);
  }

  // Listen for future track additions
  video.textTracks.addEventListener('addtrack', () => {
    scanVideoTracks(video, bridge);
  });
}

/**
 * Find the "primary" video element on the page — the one the user is watching.
 * Heuristic: largest visible area + has a currentSrc (not a thumbnail preview).
 * Falls back to any video with a src if nothing dominant is found.
 */
function findPrimaryVideo(): HTMLVideoElement | null {
  const videos = Array.from(document.querySelectorAll<HTMLVideoElement>('video'));
  if (videos.length === 0) return null;
  if (videos.length === 1) return videos[0];

  // Score by visible area × (has currentSrc bonus)
  const scored = videos
    .filter((v) => v.readyState >= 1) // HAVE_METADATA or more
    .map((v) => {
      const rect = v.getBoundingClientRect();
      const area = rect.width * rect.height;
      const srcBonus = v.currentSrc ? 2 : 1;
      return { video: v, score: area * srcBonus };
    })
    .sort((a, b) => b.score - a.score);

  return scored[0]?.video ?? null;
}

/**
 * Start HTML5 TextTrack discovery.
 * Targets only the primary (largest/loaded) video element to avoid
 * picking up thumbnail preview videos on listing pages.
 * Returns a cleanup function.
 */
export function startTextTrackDiscovery(bridge: MessageBridgeSender): () => void {
  const scanPrimary = () => {
    const primary = findPrimaryVideo();
    if (primary) {
      watchVideo(primary, bridge);
    }
  };

  // Initial scan
  scanPrimary();

  // Watch for dynamically inserted video elements
  const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      for (const node of mutation.addedNodes) {
        if (node instanceof HTMLVideoElement) {
          // Re-evaluate primary on each new video addition
          scanPrimary();
        }
        // Also check descendants of added containers
        if (node instanceof HTMLElement && node.querySelector('video')) {
          scanPrimary();
        }
      }
    }
  });

  observer.observe(document.documentElement, {
    childList: true,
    subtree: true,
  });

  return () => {
    observer.disconnect();
  };
}

