/**
 * TextTrack Discovery — HTML5 fallback for subtitle track detection.
 *
 * Scans for <video> elements and monitors their textTracks property
 * to discover available subtitle/caption tracks on any website.
 * Sends SUBTITLE_TRACKS_DISCOVERED over the bridge when tracks are found.
 *
 * This provides universal fallback coverage for sites not explicitly
 * handled by platform-specific handlers (Udemy, YouTube, Coursera).
 */

import type { MessageBridgeSender } from '@/inject/messageBridge';
import type { AvailableSubtitleTrack, SubtitleTracksDiscoveredPayload } from '@/types/subtitle';
import { findPrimaryVideo } from '@/lib/findPrimaryVideo';

/** Scan a video element's textTracks and send discovery message */
function scanVideoTracks(video: HTMLVideoElement, bridge: MessageBridgeSender): void {
  const tracks: AvailableSubtitleTrack[] = [];

  const domTracks = Array.from(video.querySelectorAll('track'));

  for (let i = 0; i < video.textTracks.length; i++) {
    const track = video.textTracks[i];
    if (track.kind === 'subtitles' || track.kind === 'captions') {
      // Try to find the corresponding <track> element to get its src URL
      const domTrack = domTracks.find(
        (t) => t.srclang === track.language && t.kind === track.kind
      );

      tracks.push({
        language: track.language || '',
        label: track.label || track.language || '',
        url: domTrack?.src || undefined,
        isAutoGenerated: false,
        platform: 'html5',
      });
    }
  }

  if (tracks.length > 0) {
    bridge.send('SUBTITLE_TRACKS_DISCOVERED', {
      tracks,
      platform: 'html5',
    } as SubtitleTracksDiscoveredPayload);

    console.log('AnyLLMTranslate: TextTrack discovery found tracks', {
      count: tracks.length,
      languages: tracks.map((t) => t.language),
    });
  }
}

/**
 * Start HTML5 TextTrack discovery.
 * Targets only the primary (largest/loaded) video element to avoid
 * picking up thumbnail preview videos on listing pages.
 * Returns a cleanup function.
 *
 * P2: all per-invocation state (reportedVideos, metadataListenedVideos,
 * cleanup handlers) lives in CLOSURE scope, not module scope. Previously these
 * were module-level, so a second invocation (e.g. BFCache restore re-init)
 * would (a) skip already-reported videos via the shared WeakSet and (b) have
 * its cleanup handlers cleared by the first invocation's teardown.
 */
export function startTextTrackDiscovery(bridge: MessageBridgeSender): () => void {
  /** Set of already-reported video elements to avoid duplicate messages */
  const reportedVideos = new WeakSet<HTMLVideoElement>();
  /** Videos that have a loadedmetadata listener attached */
  const metadataListenedVideos = new WeakSet<HTMLVideoElement>();
  /** Cleanup handlers for event listeners attached to video elements. */
  const videoCleanupHandlers: Array<{ target: EventTarget; event: string; handler: EventListener }> = [];

  /** Attach track listeners to a video element */
  const watchVideo = (video: HTMLVideoElement) => {
    if (reportedVideos.has(video)) return;
    reportedVideos.add(video);

    // Scan existing tracks
    if (video.textTracks.length > 0) {
      scanVideoTracks(video, bridge);
    }

    // Listen for future track additions
    const addTrackHandler = () => {
      scanVideoTracks(video, bridge);
    };
    video.textTracks.addEventListener('addtrack', addTrackHandler);
    videoCleanupHandlers.push({ target: video.textTracks, event: 'addtrack', handler: addTrackHandler });

    // Re-scan when metadata becomes available — tracks may not exist until then
    if (!metadataListenedVideos.has(video)) {
      metadataListenedVideos.add(video);
      const metadataHandler = () => {
        scanVideoTracks(video, bridge);
      };
      video.addEventListener('loadedmetadata', metadataHandler);
      videoCleanupHandlers.push({ target: video, event: 'loadedmetadata', handler: metadataHandler });
    }
  };

  const scanPrimary = () => {
    const primary = findPrimaryVideo();
    if (primary) {
      watchVideo(primary);
    }
  };

  // Initial scan
  scanPrimary();

  // Watch for dynamically inserted video elements (throttled)
  let scanTimer: ReturnType<typeof setTimeout> | null = null;
  const debouncedScan = () => {
    if (scanTimer) clearTimeout(scanTimer);
    scanTimer = setTimeout(scanPrimary, 50);
  };

  const observer = new MutationObserver((mutations) => {
    let hasVideo = false;
    for (const mutation of mutations) {
      for (const node of mutation.addedNodes) {
        if (node instanceof HTMLVideoElement) {
          hasVideo = true;
          break;
        }
        if (node instanceof HTMLElement && node.querySelector('video')) {
          hasVideo = true;
          break;
        }
      }
      if (hasVideo) break;
    }
    if (hasVideo) debouncedScan();
  });

  observer.observe(document.documentElement, {
    childList: true,
    subtree: true,
  });

  return () => {
    observer.disconnect();
    if (scanTimer) clearTimeout(scanTimer);
    // Remove all video event listeners registered by THIS invocation only.
    for (const { target, event, handler } of videoCleanupHandlers) {
      target.removeEventListener(event, handler);
    }
    videoCleanupHandlers.length = 0;
  };
}
