import type {
  AvailableSubtitleTrack,
  SubtitleTracksDiscoveredPayload,
} from '@/types/subtitle';
import type { MessageBridgeSender } from '@/inject/messageBridge';
import type { YouTubeHandler } from '@/inject/subtitleHandlers/youtube';

const YOUTUBE_CAPTION_BUTTON_SELECTOR = '.ytp-subtitles-button';
const DISCOVERY_RETRY_MS = 250;
const DISCOVERY_RETRY_LIMIT = 40;
const CAPTION_BUTTON_RETRY_MS = 200;
const CAPTION_BUTTON_RETRY_LIMIT = 10;

type YoutubeWindow = Window & {
  ytInitialPlayerResponse?: unknown;
  ytplayer?: {
    config?: {
      args?: {
        raw_player_response?: unknown;
      };
    };
  };
};

const youtubeState = {
  captionsEnabledByExtension: false,
  captionButtonRetry: null as ReturnType<typeof setTimeout> | null,
};

function parseResponseCandidate(candidate: unknown): unknown | null {
  if (candidate && typeof candidate === 'object') return candidate;
  if (typeof candidate !== 'string') return null;
  try {
    const parsed: unknown = JSON.parse(candidate);
    return parsed && typeof parsed === 'object' ? parsed : null;
  } catch {
    return null;
  }
}

function readEmbeddedPlayerResponses(win: Window = window): unknown[] {
  const youtubeWindow = win as YoutubeWindow;
  return [
    parseResponseCandidate(youtubeWindow.ytInitialPlayerResponse),
    parseResponseCandidate(youtubeWindow.ytplayer?.config?.args?.raw_player_response),
  ].filter((response): response is object => response !== null);
}

function emitEmbeddedTracks(
  handler: YouTubeHandler,
  bridge: MessageBridgeSender,
  emittedKeys: ReadonlySet<string>,
  requireDifferentKey = false,
): { key: string; emitted: boolean } | null {
  const candidates = readEmbeddedPlayerResponses()
    .map((response) => {
      const tracks = handler.extractAvailableTracks(JSON.stringify(response));
      if (tracks.length === 0) return null;
      const videoId = tracks.find((track) => track.videoId)?.videoId;
      const key = [
        videoId ?? '',
        ...tracks.map(
          (track: AvailableSubtitleTrack) =>
            `${track.language}:${track.isAutoGenerated ? 'asr' : 'manual'}:${track.url ?? ''}`,
        ),
      ].join('|');
      return { key, tracks, videoId };
    })
    .filter((candidate): candidate is NonNullable<typeof candidate> => candidate !== null);

  const candidate =
    candidates.find(({ key }) => !requireDifferentKey || !emittedKeys.has(key)) ??
    candidates[0];
  if (!candidate) return null;
  if (emittedKeys.has(candidate.key)) return { key: candidate.key, emitted: false };

  bridge.send('SUBTITLE_TRACKS_DISCOVERED', {
    tracks: candidate.tracks,
    platform: 'youtube',
    ...(candidate.videoId ? { videoId: candidate.videoId } : {}),
  } satisfies SubtitleTracksDiscoveredPayload);

  return { key: candidate.key, emitted: true };
}

export function startYoutubeMetadataDiscovery(
  handler: YouTubeHandler,
  bridge: MessageBridgeSender,
): () => void {
  let retryTimer: ReturnType<typeof setTimeout> | null = null;
  let attempts = 0;
  const emittedKeys = new Set<string>();
  let requireDifferentKey = false;

  const clearRetry = () => {
    if (retryTimer) {
      clearTimeout(retryTimer);
      retryTimer = null;
    }
  };

  const discover = () => {
    const result = emitEmbeddedTracks(handler, bridge, emittedKeys, requireDifferentKey);
    if (result?.emitted) {
      emittedKeys.add(result.key);
      requireDifferentKey = false;
    }
    if (result?.key && !requireDifferentKey || attempts >= DISCOVERY_RETRY_LIMIT) {
      clearRetry();
      return;
    }
    attempts += 1;
    retryTimer = setTimeout(discover, DISCOVERY_RETRY_MS);
  };

  const onNavigation = () => {
    clearRetry();
    attempts = 0;
    requireDifferentKey = emittedKeys.size > 0;
    discover();
  };

  window.addEventListener('yt-navigate-finish', onNavigation);
  discover();

  return () => {
    clearRetry();
    window.removeEventListener('yt-navigate-finish', onNavigation);
  };
}

function findCaptionButton(): HTMLButtonElement | null {
  return document.querySelector<HTMLButtonElement>(YOUTUBE_CAPTION_BUTTON_SELECTOR);
}

export function requestYoutubeNativeCaptions(): void {
  if (youtubeState.captionsEnabledByExtension || youtubeState.captionButtonRetry) return;

  let attempts = 0;
  const attempt = () => {
    const button = findCaptionButton();
    if (button) {
      youtubeState.captionButtonRetry = null;
      if (button.getAttribute('aria-pressed') !== 'true') {
        button.click();
        youtubeState.captionsEnabledByExtension = true;
      }
      return;
    }

    attempts += 1;
    if (attempts >= CAPTION_BUTTON_RETRY_LIMIT) {
      youtubeState.captionButtonRetry = null;
      return;
    }
    youtubeState.captionButtonRetry = setTimeout(attempt, CAPTION_BUTTON_RETRY_MS);
  };

  attempt();
}

export function restoreYoutubeNativeCaptions(): void {
  if (youtubeState.captionButtonRetry) {
    clearTimeout(youtubeState.captionButtonRetry);
    youtubeState.captionButtonRetry = null;
  }
  if (!youtubeState.captionsEnabledByExtension) return;

  const button = findCaptionButton();
  if (button?.getAttribute('aria-pressed') === 'true') {
    button.click();
  }
  youtubeState.captionsEnabledByExtension = false;
}
