/**
 * Pure helpers for the YouTube link pre-align flow (Settings → Subtitle Studio).
 * Extracts `ytInitialPlayerResponse` from watch-page HTML, selects the ASR
 * caption track, and canonicalizes timedtext URLs on `fmt=json3` so the
 * Settings flow and the playback flow produce identical units + contentHash.
 *
 * No I/O, no Chrome APIs, no DOMParser — network lives in
 * `services/youtubeLinkPrealign.ts`.
 */

import { isYoutubeAsrUrl } from '@/lib/youtubeAsrResegment';
import type { AvailableSubtitleTrack } from '@/types/subtitle';

export interface ExtractedPlayerResponse {
  /** Raw JSON text of ytInitialPlayerResponse — feeds YouTubeHandler.extractAvailableTracks. */
  rawJson: string;
  /** Parsed player response (videoDetails, captions, …). */
  data: Record<string, unknown>;
}

const PLAYER_RESPONSE_MARKER = /(?:var\s+)?(?:window\.)?ytInitialPlayerResponse\s*=\s*/g;

/**
 * Extract the `ytInitialPlayerResponse` object from watch-page HTML.
 * Returns null on consent/bot pages (marker absent) and malformed JSON.
 * When several assignments exist, the first one that parses as an object wins.
 */
export function extractPlayerResponseFromWatchHtml(
  html: string,
): ExtractedPlayerResponse | null {
  if (!html) return null;
  PLAYER_RESPONSE_MARKER.lastIndex = 0;
  let match: RegExpExecArray | null;
  while ((match = PLAYER_RESPONSE_MARKER.exec(html)) !== null) {
    const start = match.index + match[0].length;
    const candidate = extractBalancedJsonObject(html, start);
    if (!candidate) continue;
    try {
      const data = JSON.parse(candidate) as unknown;
      if (!data || typeof data !== 'object' || Array.isArray(data)) continue;
      return { rawJson: candidate, data: data as Record<string, unknown> };
    } catch {
      // Malformed assignment — try a later one.
    }
  }
  return null;
}

/**
 * Scan from the first `{` at/after `start` to its balanced `}`, skipping
 * string contents (so braces/quotes inside values do not break the scan).
 * Only whitespace is allowed between the assignment and the opening brace.
 */
function extractBalancedJsonObject(text: string, start: number): string | null {
  const open = text.indexOf('{', start);
  if (open < 0) return null;
  if (text.slice(start, open).trim().length > 0) return null;

  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let i = open; i < text.length; i++) {
    const ch = text[i];
    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (ch === '\\') {
        escaped = true;
      } else if (ch === '"') {
        inString = false;
      }
      continue;
    }
    if (ch === '"') {
      inString = true;
    } else if (ch === '{') {
      depth++;
    } else if (ch === '}') {
      depth--;
      if (depth === 0) return text.slice(open, i + 1);
    }
  }
  return null;
}

export type AsrTrackSelection =
  | { ok: true; track: AvailableSubtitleTrack }
  | { ok: false; reason: 'no-tracks' | 'no-asr' };

/**
 * Pick the auto-generated (ASR) caption track from a track list.
 * ASR detection mirrors the playback gate: `isAutoGenerated` meta OR a
 * `kind=asr` timedtext URL. Tracks without a fetchable URL are unusable.
 */
export function selectAsrTrack(tracks: AvailableSubtitleTrack[]): AsrTrackSelection {
  if (tracks.length === 0) return { ok: false, reason: 'no-tracks' };
  const asr = tracks.find(
    (t) => !!t.url && (t.isAutoGenerated === true || isYoutubeAsrUrl(t.url as string)),
  );
  if (!asr) return { ok: false, reason: 'no-asr' };
  return { ok: true, track: asr };
}

/**
 * Canonicalize a timedtext track URL on `fmt=json3` (word-level timing).
 * Replaces an existing `fmt` param; falls back to string surgery when the
 * URL constructor cannot parse the input.
 */
export function buildJson3TimedtextUrl(baseUrl: string): string {
  try {
    const u = new URL(baseUrl);
    u.searchParams.set('fmt', 'json3');
    return u.toString();
  } catch {
    const withoutFmt = baseUrl
      .replace(/([?&])fmt=[^&]*(&)?/, (_m, sep: string, tail: string | undefined) => {
        if (tail) return sep;
        return sep === '?' ? '?' : '';
      })
      .replace(/[?&]$/, '');
    const sepChar = withoutFmt.includes('?') ? '&' : '?';
    return `${withoutFmt}${sepChar}fmt=json3`;
  }
}
