import { describe, expect, it } from 'vitest';
import {
  extractPlayerResponseFromWatchHtml,
  selectAsrTrack,
  buildJson3TimedtextUrl,
} from '@/lib/youtubeWatchPage';
import { YouTubeHandler } from '@/inject/subtitleHandlers/youtube';
import type { AvailableSubtitleTrack } from '@/types/subtitle';

const TRACKS = {
  captionTracks: [
    {
      baseUrl: 'https://www.youtube.com/api/timedtext?v=abc123&lang=en',
      name: { simpleText: 'English' },
      languageCode: 'en',
    },
    {
      baseUrl: 'https://www.youtube.com/api/timedtext?v=abc123&lang=en&kind=asr',
      name: { simpleText: 'English (auto-generated)' },
      languageCode: 'en',
      kind: 'asr',
    },
  ],
};

function playerResponseJson(overrides: Record<string, unknown> = {}): string {
  return JSON.stringify({
    videoDetails: {
      videoId: 'abc123',
      title: 'Sample Video - YouTube',
    },
    captions: {
      playerCaptionsTracklistRenderer: TRACKS,
    },
    ...overrides,
  });
}

function watchHtml(playerResponse: string, opts: { prefix?: string; suffix?: string } = {}): string {
  const { prefix = 'var ', suffix = ';' } = opts;
  return `<!doctype html><html><head><script>ytcfg.set({"a":1});</script></head>` +
    `<body><script>${prefix}ytInitialPlayerResponse = ${playerResponse}${suffix}` +
    `var ytInitialData = {};</script></body></html>`;
}

describe('extractPlayerResponseFromWatchHtml', () => {
  it('extracts a standard `var ytInitialPlayerResponse = {...};` assignment', () => {
    const json = playerResponseJson();
    const result = extractPlayerResponseFromWatchHtml(watchHtml(json));
    expect(result).not.toBeNull();
    expect(result?.data?.videoDetails).toMatchObject({ videoId: 'abc123' });
    expect(JSON.parse(result!.rawJson)).toEqual(JSON.parse(json));
  });

  it('handles no `var`, window prefix, and whitespace/newline variants', () => {
    const json = playerResponseJson();
    const noVar = extractPlayerResponseFromWatchHtml(watchHtml(json, { prefix: '' }));
    expect(noVar?.data?.videoDetails).toMatchObject({ videoId: 'abc123' });

    const windowPrefix = extractPlayerResponseFromWatchHtml(
      watchHtml(json, { prefix: 'window.' }),
    );
    expect(windowPrefix?.data?.videoDetails).toMatchObject({ videoId: 'abc123' });

    const spaced = extractPlayerResponseFromWatchHtml(
      `<script>var ytInitialPlayerResponse =\n  ${json}\n;</script>`,
    );
    expect(spaced?.data?.videoDetails).toMatchObject({ videoId: 'abc123' });
  });

  it('tolerates braces and escaped quotes inside string values', () => {
    const json = JSON.stringify({
      videoDetails: { videoId: 'abc123', title: 'Weird {title} with "quotes" and \\ backslash' },
      captions: { playerCaptionsTracklistRenderer: TRACKS },
    });
    const result = extractPlayerResponseFromWatchHtml(watchHtml(json));
    expect(result?.data?.videoDetails).toMatchObject({ videoId: 'abc123' });
  });

  it('returns null when the marker is absent (consent/bot page)', () => {
    const consent = '<html><body><form action="https://consent.youtube.com/save">…</form></body></html>';
    expect(extractPlayerResponseFromWatchHtml(consent)).toBeNull();
    expect(extractPlayerResponseFromWatchHtml('')).toBeNull();
  });

  it('returns null on malformed / unbalanced JSON', () => {
    expect(
      extractPlayerResponseFromWatchHtml(
        '<script>var ytInitialPlayerResponse = {"videoDetails": {"videoId": "abc123";</script>',
      ),
    ).toBeNull();
  });

  it('returns null when the assignment is not an object', () => {
    expect(
      extractPlayerResponseFromWatchHtml('<script>var ytInitialPlayerResponse = null;</script>'),
    ).toBeNull();
    expect(
      extractPlayerResponseFromWatchHtml(
        '<script>var ytInitialPlayerResponse = undefined;</script>',
      ),
    ).toBeNull();
  });

  it('uses a later valid assignment when the first is malformed', () => {
    const good = playerResponseJson();
    const html =
      '<script>var ytInitialPlayerResponse = {broken;</script>' +
      `<script>var ytInitialPlayerResponse = ${good};</script>`;
    const result = extractPlayerResponseFromWatchHtml(html);
    expect(result?.data?.videoDetails).toMatchObject({ videoId: 'abc123' });
  });
});

describe('selectAsrTrack', () => {
  const asrTrack: AvailableSubtitleTrack = {
    language: 'en',
    label: 'English (auto-generated)',
    url: 'https://www.youtube.com/api/timedtext?v=abc123&lang=en&kind=asr',
    isAutoGenerated: true,
    platform: 'youtube',
    videoId: 'abc123',
  };
  const humanTrack: AvailableSubtitleTrack = {
    language: 'en',
    label: 'English',
    url: 'https://www.youtube.com/api/timedtext?v=abc123&lang=en',
    isAutoGenerated: false,
    platform: 'youtube',
    videoId: 'abc123',
  };

  it('reports no-tracks for an empty list', () => {
    expect(selectAsrTrack([])).toEqual({ ok: false, reason: 'no-tracks' });
  });

  it('reports no-asr when only human-uploaded tracks exist', () => {
    expect(selectAsrTrack([humanTrack])).toEqual({ ok: false, reason: 'no-asr' });
  });

  it('selects the ASR track among mixed tracks', () => {
    const result = selectAsrTrack([humanTrack, asrTrack]);
    expect(result).toEqual({ ok: true, track: asrTrack });
  });

  it('detects ASR via kind=asr URL even when the flag is missing', () => {
    const urlOnly: AvailableSubtitleTrack = { ...asrTrack, isAutoGenerated: false };
    const result = selectAsrTrack([urlOnly]);
    expect(result).toEqual({ ok: true, track: urlOnly });
  });

  it('reports no-asr when the ASR track has no fetchable URL', () => {
    const noUrl: AvailableSubtitleTrack = { ...asrTrack, url: undefined };
    expect(selectAsrTrack([noUrl])).toEqual({ ok: false, reason: 'no-asr' });
  });
});

describe('buildJson3TimedtextUrl', () => {
  it('appends fmt=json3 when missing', () => {
    const out = buildJson3TimedtextUrl('https://www.youtube.com/api/timedtext?v=abc123&lang=en');
    expect(out).toContain('fmt=json3');
    expect(out).toContain('v=abc123');
    expect(out).toContain('lang=en');
  });

  it('replaces an existing fmt value', () => {
    const out = buildJson3TimedtextUrl(
      'https://www.youtube.com/api/timedtext?v=abc123&lang=en&fmt=srv3',
    );
    expect(out).toContain('fmt=json3');
    expect(out).not.toContain('fmt=srv3');
  });

  it('preserves kind=asr and signature params', () => {
    const out = buildJson3TimedtextUrl(
      'https://www.youtube.com/api/timedtext?v=abc123&lang=en&kind=asr&sig=xyz',
    );
    expect(out).toContain('kind=asr');
    expect(out).toContain('sig=xyz');
    expect(out).toContain('fmt=json3');
  });

  it('falls back to string surgery for non-parseable URLs', () => {
    const out = buildJson3TimedtextUrl('not a url at all');
    expect(out).toContain('fmt=json3');
    const replaced = buildJson3TimedtextUrl('weird?fmt=vtt&x=1');
    expect(replaced).toContain('fmt=json3');
    expect(replaced).not.toContain('fmt=vtt');
    expect(replaced).toContain('x=1');
  });
});

describe('adapter: extracted player response → YouTubeHandler.extractAvailableTracks', () => {
  it('feeds rawJson directly into the existing track parser (no duplicated parsing)', () => {
    const html = watchHtml(playerResponseJson());
    const extracted = extractPlayerResponseFromWatchHtml(html);
    expect(extracted).not.toBeNull();

    const tracks = new YouTubeHandler().extractAvailableTracks(extracted!.rawJson);
    expect(tracks).toHaveLength(2);
    expect(tracks[0]).toMatchObject({
      language: 'en',
      label: 'English',
      isAutoGenerated: false,
      platform: 'youtube',
      videoId: 'abc123',
    });
    expect(tracks[1]).toMatchObject({
      language: 'en',
      isAutoGenerated: true,
      videoId: 'abc123',
    });
    expect(tracks[1]?.url).toContain('kind=asr');

    // And the ASR selection works end-to-end on the adapter output.
    const selection = selectAsrTrack(tracks);
    expect(selection.ok).toBe(true);
  });

  it('exposes videoDetails title for the cache entry metadata', () => {
    const extracted = extractPlayerResponseFromWatchHtml(watchHtml(playerResponseJson()));
    const details = extracted?.data?.videoDetails as { title?: string } | undefined;
    expect(details?.title).toBe('Sample Video - YouTube');
  });

  it('yields no-tracks for a player response without captions', () => {
    const html = watchHtml(playerResponseJson({ captions: undefined }));
    const extracted = extractPlayerResponseFromWatchHtml(html);
    const tracks = new YouTubeHandler().extractAvailableTracks(extracted!.rawJson);
    expect(tracks).toEqual([]);
    expect(selectAsrTrack(tracks)).toEqual({ ok: false, reason: 'no-tracks' });
  });
});
