import { describe, expect, it } from 'vitest';
import {
  extractPlayerResponseFromWatchHtml,
  selectAsrTrack,
  buildJson3TimedtextUrl,
} from '@/lib/youtubeWatchPage';
import { YouTubeHandler } from '@/inject/subtitleHandlers/youtube';
import type { AvailableSubtitleTrack } from '@/types/subtitle';

const TRACKS = {
  captionTracks: [
    {
      baseUrl: 'https://www.youtube.com/api/timedtext?v=abc123&lang=en',
      name: { simpleText: 'English' },
      languageCode: 'en',
    },
    {
      baseUrl: 'https://www.youtube.com/api/timedtext?v=abc123&lang=en&kind=asr',
      name: { simpleText: 'English (auto-generated)' },
      languageCode: 'en',
      kind: 'asr',
    },
  ],
};

function playerResponseJson(overrides: Record<string, unknown> = {}): string {
  return JSON.stringify({
    videoDetails: {
      videoId: 'abc123',
      title: 'Sample Video - YouTube',
    },
    captions: {
      playerCaptionsTracklistRenderer: TRACKS,
    },
    ...overrides,
  });
}

function watchHtml(playerResponse: string, opts: { prefix?: string; suffix?: string } = {}): string {
  const { prefix = 'var ', suffix = ';' } = opts;
  return `<!doctype html><html><head><script>ytcfg.set({"a":1});</script></head>` +
    `<body><script>${prefix}ytInitialPlayerResponse = ${playerResponse}${suffix}` +
    `var ytInitialData = {};</script></body></html>`;
}

describe('extractPlayerResponseFromWatchHtml', () => {
  it('extracts a standard `var ytInitialPlayerResponse = {...};` assignment', () => {
    const json = playerResponseJson();
    const result = extractPlayerResponseFromWatchHtml(watchHtml(json));
    expect(result).not.toBeNull();
    expect(result?.data?.videoDetails).toMatchObject({ videoId: 'abc123' });
    expect(JSON.parse(result!.rawJson)).toEqual(JSON.parse(json));
  });

  it('handles no `var`, window prefix, and whitespace/newline variants', () => {
    const json = playerResponseJson();
    const noVar = extractPlayerResponseFromWatchHtml(watchHtml(json, { prefix: '' }));
    expect(noVar?.data?.videoDetails).toMatchObject({ videoId: 'abc123' });

    const windowPrefix = extractPlayerResponseFromWatchHtml(
      watchHtml(json, { prefix: 'window.' }),
    );
    expect(windowPrefix?.data?.videoDetails).toMatchObject({ videoId: 'abc123' });

    const spaced = extractPlayerResponseFromWatchHtml(
      `<script>var ytInitialPlayerResponse =\n  ${json}\n;</script>`,
    );
    expect(spaced?.data?.videoDetails).toMatchObject({ videoId: 'abc123' });
  });

  it('tolerates braces and escaped quotes inside string values', () => {
    const json = JSON.stringify({
      videoDetails: { videoId: 'abc123', title: 'Weird {title} with "quotes" and \\ backslash' },
      captions: { playerCaptionsTracklistRenderer: TRACKS },
    });
    const result = extractPlayerResponseFromWatchHtml(watchHtml(json));
    expect(result?.data?.videoDetails).toMatchObject({ videoId: 'abc123' });
  });

  it('returns null for consent/bot pages, malformed JSON, and non-object assignments', () => {
    const consent =
      '<html><body><form action="https://consent.youtube.com/save">…</form></body></html>';
    expect(extractPlayerResponseFromWatchHtml(consent)).toBeNull();
    expect(extractPlayerResponseFromWatchHtml('')).toBeNull();
    expect(
      extractPlayerResponseFromWatchHtml(
        '<script>var ytInitialPlayerResponse = {"videoDetails": {"videoId": "abc123";</script>',
      ),
    ).toBeNull();
    expect(
      extractPlayerResponseFromWatchHtml('<script>var ytInitialPlayerResponse = null;</script>'),
    ).toBeNull();
    expect(
      extractPlayerResponseFromWatchHtml(
        '<script>var ytInitialPlayerResponse = undefined;</script>',
      ),
    ).toBeNull();
  });

  it('uses a later valid assignment when the first is malformed', () => {
    const good = playerResponseJson();
    const html =
      '<script>var ytInitialPlayerResponse = {broken;</script>' +
      `<script>var ytInitialPlayerResponse = ${good};</script>`;
    const result = extractPlayerResponseFromWatchHtml(html);
    expect(result?.data?.videoDetails).toMatchObject({ videoId: 'abc123' });
  });
});

describe('selectAsrTrack', () => {
  const asrTrack: AvailableSubtitleTrack = {
    language: 'en',
    label: 'English (auto-generated)',
    url: 'https://www.youtube.com/api/timedtext?v=abc123&lang=en&kind=asr',
    isAutoGenerated: true,
    platform: 'youtube',
    videoId: 'abc123',
  };
  const humanTrack: AvailableSubtitleTrack = {
    language: 'en',
    label: 'English',
    url: 'https://www.youtube.com/api/timedtext?v=abc123&lang=en',
    isAutoGenerated: false,
    platform: 'youtube',
    videoId: 'abc123',
  };

  it('selects the ASR track and reports no-tracks/no-asr appropriately', () => {
    // Empty list -> no-tracks.
    expect(selectAsrTrack([])).toEqual({ ok: false, reason: 'no-tracks' });
    // Only human-uploaded tracks -> no-asr.
    expect(selectAsrTrack([humanTrack])).toEqual({ ok: false, reason: 'no-asr' });
    // Mixed tracks -> ASR selected.
    expect(selectAsrTrack([humanTrack, asrTrack])).toEqual({ ok: true, track: asrTrack });
    // kind=asr URL selects even when the isAutoGenerated flag is missing.
    const urlOnly: AvailableSubtitleTrack = { ...asrTrack, isAutoGenerated: false };
    expect(selectAsrTrack([urlOnly])).toEqual({ ok: true, track: urlOnly });
    // ASR track without a fetchable URL -> no-asr.
    const noUrl: AvailableSubtitleTrack = { ...asrTrack, url: undefined };
    expect(selectAsrTrack([noUrl])).toEqual({ ok: false, reason: 'no-asr' });
  });
});

describe('buildJson3TimedtextUrl', () => {
  it('ensures fmt=json3 while preserving other query params', () => {
    // Appends fmt=json3 when missing.
    const appended = buildJson3TimedtextUrl(
      'https://www.youtube.com/api/timedtext?v=abc123&lang=en',
    );
    expect(appended).toContain('fmt=json3');
    expect(appended).toContain('v=abc123');
    expect(appended).toContain('lang=en');
    // Replaces an existing fmt value.
    const replaced = buildJson3TimedtextUrl(
      'https://www.youtube.com/api/timedtext?v=abc123&lang=en&fmt=srv3',
    );
    expect(replaced).toContain('fmt=json3');
    expect(replaced).not.toContain('fmt=srv3');
    // Preserves kind=asr and signature params.
    const preserved = buildJson3TimedtextUrl(
      'https://www.youtube.com/api/timedtext?v=abc123&lang=en&kind=asr&sig=xyz',
    );
    expect(preserved).toContain('kind=asr');
    expect(preserved).toContain('sig=xyz');
    expect(preserved).toContain('fmt=json3');
    // String-surgery fallback for non-parseable URLs.
    expect(buildJson3TimedtextUrl('not a url at all')).toContain('fmt=json3');
    const fallback = buildJson3TimedtextUrl('weird?fmt=vtt&x=1');
    expect(fallback).toContain('fmt=json3');
    expect(fallback).not.toContain('fmt=vtt');
    expect(fallback).toContain('x=1');
  });
});

describe('adapter: extracted player response → YouTubeHandler.extractAvailableTracks', () => {
  it('feeds rawJson directly into the existing track parser (no duplicated parsing)', () => {
    const html = watchHtml(playerResponseJson());
    const extracted = extractPlayerResponseFromWatchHtml(html);
    expect(extracted).not.toBeNull();

    const tracks = new YouTubeHandler().extractAvailableTracks(extracted!.rawJson);
    expect(tracks).toHaveLength(2);
    expect(tracks[0]).toMatchObject({
      language: 'en',
      label: 'English',
      isAutoGenerated: false,
      platform: 'youtube',
      videoId: 'abc123',
    });
    expect(tracks[1]).toMatchObject({
      language: 'en',
      isAutoGenerated: true,
      videoId: 'abc123',
    });
    expect(tracks[1]?.url).toContain('kind=asr');

    // And the ASR selection works end-to-end on the adapter output.
    const selection = selectAsrTrack(tracks);
    expect(selection.ok).toBe(true);
  });

  it('exposes videoDetails title for the cache entry metadata', () => {
    const extracted = extractPlayerResponseFromWatchHtml(watchHtml(playerResponseJson()));
    const details = extracted?.data?.videoDetails as { title?: string } | undefined;
    expect(details?.title).toBe('Sample Video - YouTube');
  });

  it('yields no-tracks for a player response without captions', () => {
    const html = watchHtml(playerResponseJson({ captions: undefined }));
    const extracted = extractPlayerResponseFromWatchHtml(html);
    const tracks = new YouTubeHandler().extractAvailableTracks(extracted!.rawJson);
    expect(tracks).toEqual([]);
    expect(selectAsrTrack(tracks)).toEqual({ ok: false, reason: 'no-tracks' });
  });
});
