import { describe, it, expect, beforeEach, vi } from 'vitest';
import { HboMaxHandler } from '@/inject/subtitleHandlers/hbomax';

describe('HboMaxHandler', () => {
  let handler: HboMaxHandler;

  beforeEach(() => {
    handler = new HboMaxHandler();
    document.body.innerHTML = '';
  });

  it('has platform identifier', () => {
    expect(handler.platform).toBe('hbomax');
  });

  describe('detect', () => {
    it('detects play.hbomax.com', () => {
      vi.stubGlobal('location', { hostname: 'play.hbomax.com' });
      expect(handler.detect()).toBe(true);
    });

    it('detects max.com', () => {
      vi.stubGlobal('location', { hostname: 'www.max.com' });
      expect(handler.detect()).toBe(true);
    });

    it('rejects unrelated hostnames', () => {
      vi.stubGlobal('location', { hostname: 'www.youtube.com' });
      expect(handler.detect()).toBe(false);
    });

    it('detects arbitrary max.com subdomains', () => {
      vi.stubGlobal('location', { hostname: 'foo.max.com' });
      expect(handler.detect()).toBe(true);
    });

    it('detects arbitrary hbomax.com subdomains', () => {
      vi.stubGlobal('location', { hostname: 'bar.hbomax.com' });
      expect(handler.detect()).toBe(true);
    });
  });

  describe('getPatterns', () => {
    it('returns empty array (no URL interception)', () => {
      expect(handler.getPatterns()).toEqual([]);
    });
  });

  describe('getManifestPatterns', () => {
    const patterns = () => handler.getManifestPatterns().map((p) => p.pattern);

    it('matches extensionless Max CDN manifest URLs', () => {
      const re = patterns().find((p) => p.source.includes('manifest-params'));
      expect(re?.test(
        'https://akm.asia.prd.media.max.com/fadb6e8d-4efa-49a7?manifest-params=TOKEN&rtype=s',
      )).toBe(true);
    });

    it('does not match Max CDN WebVTT segment URLs', () => {
      const re = patterns().find((p) => p.source.includes('manifest-params'));
      expect(re?.test(
        'https://akm.asia.prd.media.max.com/fadb6e8d-4efa-49a7/t/2_ada795/t0/1.vtt?manifest-params=TOKEN',
      )).toBe(false);
    });
  });

  describe('transformResponse', () => {
    it('returns empty array (never called for DOM source)', () => {
      expect(handler.transformResponse('anything', 'text/vtt', 'https://max.com/x')).toEqual([]);
    });
  });

  describe('extractAvailableTracks', () => {
    it('reads track buttons, excludes Off, extracts videoId from path', () => {
      vi.stubGlobal('location', {
        hostname: 'play.hbomax.com',
        pathname:
          '/video/watch/847404c3-4390-4195-bf4b-465a8935fd04/194b0aab-a97a-42b6-a7f8-ca5bc3576d56',
      });
      document.body.innerHTML = `
        <button data-testid="player-ux-text-track-button" aria-label="Off" aria-checked="false"></button>
        <button data-testid="player-ux-text-track-button" aria-label="English" aria-checked="true"></button>
        <button data-testid="player-ux-text-track-button" aria-label="Chinese (Simplified)" aria-checked="false"></button>
        <button data-testid="player-ux-text-track-button" aria-label="Vietnamese" aria-checked="false"></button>
      `;

      const tracks = handler.extractAvailableTracks('', 'application/json', '');

      expect(tracks).toHaveLength(3);
      expect(tracks[0]).toMatchObject({
        platform: 'hbomax',
        url: undefined,
        isAutoGenerated: false,
        videoId: '847404c3-4390-4195-bf4b-465a8935fd04',
      });
      // English is the active one (aria-checked="true")
      const english = tracks.find((t) => t.language === 'en');
      expect(english).toBeDefined();
      expect(english?.label).toBe('English');
    });

    it('returns empty array when no track buttons present', () => {
      document.body.innerHTML = '';
      expect(handler.extractAvailableTracks('', 'application/json', '')).toEqual([]);
    });

    it('falls back to lowercased label for unmapped aria-labels', () => {
      vi.stubGlobal('location', { hostname: 'play.hbomax.com', pathname: '/video/watch/abc/def' });
      document.body.innerHTML = `
        <button data-testid="player-ux-text-track-button" aria-label="Spanish" aria-checked="true"></button>
      `;
      const tracks = handler.extractAvailableTracks('', 'application/json', '');
      expect(tracks).toHaveLength(1);
      expect(tracks[0].language).toBe('es');
      expect(tracks[0].label).toBe('Spanish');
    });

    it('uses the same localized label normalization as active-language detection', () => {
      vi.stubGlobal('location', { hostname: 'play.hbomax.com', pathname: '/video/watch/abc/def' });
      document.body.innerHTML = `
        <button data-testid="player-ux-text-track-button" aria-label="Inglés" aria-checked="true"></button>
        <button data-testid="player-ux-text-track-button" aria-label="Português (Brasil)" aria-checked="false"></button>
      `;

      const tracks = handler.extractAvailableTracks('', 'application/json', '');

      expect(tracks.map((t) => t.language)).toEqual(['en', 'pt-BR']);
      expect(handler.getDomCueSource().readActiveLanguage()).toBe('en');
    });
  });

  describe('getDomCueSource', () => {
    it('returns selectors and a readActiveLanguage that maps active label to code', () => {
      document.body.innerHTML = `
        <button data-testid="player-ux-text-track-button" aria-label="English" aria-checked="true"></button>
      `;
      const source = handler.getDomCueSource();
      expect(source.cueSelector).toBe('[data-testid="cueBoxRowTextCue"]');
      expect(source.captionWindowSelector).toBe('[data-testid="caption_renderer_overlay"]');
      expect(source.observeRootSelector).toBe('[data-testid="caption_renderer_overlay"]');
      expect(source.readActiveLanguage()).toBe('en');
    });

    it('readActiveLanguage returns empty when no active button', () => {
      document.body.innerHTML = `
        <button data-testid="player-ux-text-track-button" aria-label="Off" aria-checked="true"></button>
      `;
      expect(handler.getDomCueSource().readActiveLanguage()).toBe('');
    });

    it('does not override captionHideMethod (defaults to display:none)', () => {
      // Regression guard: Max's caption window is the PARENT of the cue element,
      // so display:none is safe and correct. Must NOT declare 'visibility'.
      const source = handler.getDomCueSource();
      expect(source.captionHideMethod).toBeUndefined();
    });
  });
});
