import { describe, it, expect, afterEach } from 'vitest';
import { NetflixHandler, extractNetflixTracksFromValue } from '@/inject/subtitleHandlers/netflix';

describe('NetflixHandler', () => {
  const handler = new NetflixHandler();
  const originalHostname = window.location.hostname;
  const originalPathname = window.location.pathname;

  afterEach(() => {
    Object.defineProperty(window, 'location', {
      value: { hostname: originalHostname, pathname: originalPathname },
      writable: true,
    });
  });

  const setLocation = (hostname: string, pathname: string = '/') => {
    Object.defineProperty(window, 'location', {
      value: { hostname, pathname },
      writable: true,
    });
  };

  it('has platform identifier', () => {
    expect(handler.platform).toBe('netflix');
  });

  describe('detect', () => {
    it('returns true for www.netflix.com', () => {
      setLocation('www.netflix.com');
      expect(handler.detect()).toBe(true);
    });

    it('returns false for notnetflix.com', () => {
      setLocation('notnetflix.com');
      expect(handler.detect()).toBe(false);
    });
  });

  describe('getPatterns', () => {
    it('matches nflxvideo.net subtitle URLs', () => {
      const patterns = handler.getPatterns();
      expect(
        patterns[0].pattern.test(
          'https://abc123.oca.nflxvideo.net/?o=1&e=2&t=3&v=4',
        ),
      ).toBe(true);
    });
  });

  describe('extractNetflixTracksFromValue', () => {
    it('parses timedtexttracks from result wrapper', () => {
      const tracks = extractNetflixTracksFromValue({
        result: {
          movieId: '80057281',
          timedtexttracks: [
            {
              bcp47: 'en',
              displayName: 'English',
              href: 'https://x.oca.nflxvideo.net/?o=1',
            },
            { isImageBased: true, language: 'en' },
          ],
        },
      });
      expect(tracks).toHaveLength(1);
      expect(tracks[0].language).toBe('en');
      expect(tracks[0].videoId).toBe('80057281');
      expect(tracks[0].platform).toBe('netflix');
    });
  });

  describe('extractAvailableTracks', () => {
    it('reads pre-wrapped tracks from JSON.parse hook payload', () => {
      const body = JSON.stringify({
        tracks: [{ language: 'vi', label: 'Vietnamese', platform: 'netflix', isAutoGenerated: false }],
      });
      const tracks = handler.extractAvailableTracks!(body, 'application/json', '');
      expect(tracks[0].language).toBe('vi');
    });
  });
});
