import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { startTextTrackDiscovery } from '@/inject/textTrackDiscovery';
import type { SubtitleTracksDiscoveredPayload } from '@/types/subtitle';

/** Flush pending MutationObserver callbacks (jsdom delivers them as microtasks).
 *  Also waits for the 50ms debounce in textTrackDiscovery's MutationObserver wrapper. */
function flushObservers(): Promise<void> {
  return new Promise((resolve) => {
    Promise.resolve()
      .then(() => Promise.resolve())
      .then(() => setTimeout(resolve, 60));
  });
}

interface MockTrack {
  kind: string;
  language: string;
  label: string;
}

function makeTextTracks(initial: MockTrack[] = []) {
  const tracks = [...initial];
  const listeners: Record<string, Array<(e?: Event) => void>> = {};

  const list = tracks as MockTrack[] & {
    addEventListener: (event: string, handler: (e?: Event) => void) => void;
    removeEventListener: (event: string, handler: (e?: Event) => void) => void;
    dispatchEvent: (event: Event) => boolean;
    __addTrack: (track: MockTrack) => void;
  };

  (list as unknown as Record<string, unknown>).addEventListener = (
    event: string,
    handler: (e?: Event) => void
  ) => {
    (listeners[event] ??= []).push(handler);
  };
  (list as unknown as Record<string, unknown>).removeEventListener = (
    event: string,
    handler: (e?: Event) => void
  ) => {
    listeners[event] = (listeners[event] || []).filter((h) => h !== handler);
  };
  (list as unknown as Record<string, unknown>).dispatchEvent = (event: Event) => {
    (listeners[event.type] || []).forEach((h) => h(event));
    return true;
  };
  (list as unknown as Record<string, unknown>).__addTrack = (track: MockTrack) => {
    tracks.push(track);
    const evt = new Event('addtrack');
    (listeners['addtrack'] || []).forEach((h) => h(evt));
  };

  return list;
}

function stubTextTracks(video: HTMLVideoElement, tracks: ReturnType<typeof makeTextTracks>) {
  Object.defineProperty(video, 'textTracks', {
    configurable: true,
    value: tracks,
  });
}

function makeVideo(tracks: MockTrack[] = [], domTrackSrcs: Array<{ srclang: string; kind: string; src: string }> = []): HTMLVideoElement {
  const video = document.createElement('video');
  for (const dt of domTrackSrcs) {
    const el = document.createElement('track');
    el.kind = dt.kind;
    el.srclang = dt.srclang;
    el.src = dt.src;
    video.appendChild(el);
  }
  stubTextTracks(video, makeTextTracks(tracks));
  return video;
}

describe('startTextTrackDiscovery', () => {
  let bridge: { send: ReturnType<typeof vi.fn> };

  beforeEach(() => {
    bridge = { send: vi.fn(() => 'req-1') };
    document.body.innerHTML = '';
    vi.spyOn(console, 'log').mockImplementation(() => {});
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('emits tracks payload (or not), prefers primary video, cleanup is a function', () => {
    const cleanupEmpty = startTextTrackDiscovery(bridge);
    expect(typeof cleanupEmpty).toBe('function');
    cleanupEmpty();
    bridge.send.mockClear();

    const emptyVideo = makeVideo([]);
    document.body.appendChild(emptyVideo);
    const cleanupNoTracks = startTextTrackDiscovery(bridge);
    expect(bridge.send).not.toHaveBeenCalled();
    cleanupNoTracks();
    document.body.innerHTML = '';
    bridge.send.mockClear();

    // Thumbnail vs primary
    const thumb = makeVideo(
      [{ kind: 'subtitles', language: 'en', label: 'English' }],
      [{ srclang: 'en', kind: 'subtitles', src: 'https://example.com/thumb.vtt' }]
    );
    thumb.getBoundingClientRect = () =>
      ({ width: 100, height: 100, left: 0, top: 0, right: 100, bottom: 100, x: 0, y: 0, toJSON: () => ({}) }) as DOMRect;
    document.body.appendChild(thumb);

    const primary = makeVideo(
      [
        { kind: 'subtitles', language: 'en', label: 'English' },
        { kind: 'captions', language: 'es', label: 'Spanish' },
      ],
      [
        { srclang: 'en', kind: 'subtitles', src: 'https://example.com/en.vtt' },
        { srclang: 'es', kind: 'captions', src: 'https://example.com/es.vtt' },
      ]
    );
    Object.defineProperty(primary, 'readyState', { configurable: true, get: () => 1 });
    primary.getBoundingClientRect = () =>
      ({ width: 1280, height: 720, left: 0, top: 0, right: 1280, bottom: 720, x: 0, y: 0, toJSON: () => ({}) }) as DOMRect;
    document.body.appendChild(primary);

    const cleanup = startTextTrackDiscovery(bridge);
    expect(bridge.send).toHaveBeenCalledWith('SUBTITLE_TRACKS_DISCOVERED', expect.any(Object));
    const payload = bridge.send.mock.calls[0][1] as SubtitleTracksDiscoveredPayload;
    expect(payload.platform).toBe('html5');
    expect(payload.tracks).toHaveLength(2);
    expect(payload.tracks[0].language).toBe('en');
    expect(payload.tracks[0].label).toBe('English');
    expect(payload.tracks[0].url).toBe('https://example.com/en.vtt');
    expect(payload.tracks[0].isAutoGenerated).toBe(false);
    expect(payload.tracks[1].language).toBe('es');
    cleanup();
  });

  it('watches dynamic video insert, addtrack, and loadedmetadata re-scans', async () => {
    const cleanup = startTextTrackDiscovery(bridge);
    expect(bridge.send).not.toHaveBeenCalled();

    const video = makeVideo(
      [{ kind: 'subtitles', language: 'fr', label: 'French' }],
      [{ srclang: 'fr', kind: 'subtitles', src: 'https://example.com/fr.vtt' }]
    );
    document.body.appendChild(video);
    await flushObservers();
    expect(bridge.send).toHaveBeenCalledTimes(1);
    expect(bridge.send).toHaveBeenCalledWith(
      'SUBTITLE_TRACKS_DISCOVERED',
      expect.objectContaining({ platform: 'html5' })
    );
    cleanup();
    document.body.innerHTML = '';
    bridge.send.mockClear();

    // addtrack
    const tracks = makeTextTracks([]);
    const video2 = document.createElement('video');
    stubTextTracks(video2, tracks);
    document.body.appendChild(video2);
    const cleanup2 = startTextTrackDiscovery(bridge);
    expect(bridge.send).not.toHaveBeenCalled();
    (tracks as unknown as { __addTrack: (t: MockTrack) => void }).__addTrack({
      kind: 'subtitles',
      language: 'de',
      label: 'German',
    });
    expect(bridge.send).toHaveBeenCalledTimes(1);
    const payload = bridge.send.mock.calls[0][1] as SubtitleTracksDiscoveredPayload;
    expect(payload.tracks).toHaveLength(1);
    expect(payload.tracks[0].language).toBe('de');
    cleanup2();
    document.body.innerHTML = '';
    bridge.send.mockClear();

    // loadedmetadata
    const tracks3 = makeTextTracks([
      { kind: 'subtitles', language: 'ja', label: 'Japanese' },
    ]);
    const video3 = document.createElement('video');
    stubTextTracks(video3, tracks3);
    Object.defineProperty(video3, 'textTracks', {
      configurable: true,
      value: makeTextTracks([]),
    });
    document.body.appendChild(video3);
    const cleanup3 = startTextTrackDiscovery(bridge);
    expect(bridge.send).not.toHaveBeenCalled();
    stubTextTracks(video3, tracks3);
    video3.dispatchEvent(new Event('loadedmetadata'));
    expect(bridge.send).toHaveBeenCalledTimes(1);
    const payload3 = bridge.send.mock.calls[0][1] as SubtitleTracksDiscoveredPayload;
    expect(payload3.tracks).toHaveLength(1);
    expect(payload3.tracks[0].language).toBe('ja');
    cleanup3();
  });

  it('cleanup disconnects observers and removes listeners', async () => {
    const tracks = makeTextTracks([]);
    const video = document.createElement('video');
    stubTextTracks(video, tracks);
    document.body.appendChild(video);

    const cleanup = startTextTrackDiscovery(bridge);
    cleanup();
    (tracks as unknown as { __addTrack: (t: MockTrack) => void }).__addTrack({
      kind: 'subtitles',
      language: 'ko',
      label: 'Korean',
    });
    expect(bridge.send).not.toHaveBeenCalled();

    const video2 = makeVideo([{ kind: 'subtitles', language: 'zh', label: 'Chinese' }]);
    document.body.appendChild(video2);
    await flushObservers();
    expect(bridge.send).not.toHaveBeenCalled();
  });
});
