import { describe, it, expect, afterEach, vi } from 'vitest';
import { UdemyHandler } from '@/inject/subtitleHandlers/udemy';

describe('UdemyHandler', () => {
  const handler = new UdemyHandler();
  const extractTracks = (body: string, contentType: string, url: string) => {
    if (!handler.extractAvailableTracks) throw new Error('extractAvailableTracks missing');
    return handler.extractAvailableTracks(body, contentType, url);
  };
  const originalHostname = window.location.hostname;
  const originalPathname = window.location.pathname;

  afterEach(() => {
    Object.defineProperty(window, 'location', {
      value: { hostname: originalHostname, pathname: originalPathname },
      writable: true,
    });
  });

  const setLocation = (hostname: string, pathname: string = '/') => {
    Object.defineProperty(window, 'location', {
      value: { hostname, pathname },
      writable: true,
    });
  };

  it('has platform identifier', () => {
    expect(handler.platform).toBe('udemy');
  });

  describe('detect', () => {
    it('returns true for udemy.com hosts', () => {
      setLocation('www.udemy.com');
      expect(handler.detect()).toBe(true);
    });

    it('returns false for notudemy.com', () => {
      setLocation('notudemy.com');
      expect(handler.detect()).toBe(false);
    });
  });

  describe('isWatchPage', () => {
    it('returns true on /learn/ paths', () => {
      setLocation('www.udemy.com', '/course/slug/learn/lecture/1');
      expect(handler.isWatchPage()).toBe(true);
    });
  });

  describe('getMetadataPatterns', () => {
    it('matches lecture metadata API', () => {
      const patterns = handler.getMetadataPatterns?.() ?? [];
      expect(patterns[0].pattern.test('https://www.udemy.com/api-2.0/users/me/subscribed-courses-lectures/12345/')).toBe(
        true,
      );
    });
  });

  describe('getPatterns', () => {
    it('returns udemycdn VTT pattern', () => {
      const patterns = handler.getPatterns();
      expect(patterns).toHaveLength(1);
      expect(patterns[0].pattern.test('https://cdna.udemycdn.com/subtitles/12345/en/file.vtt')).toBe(true);
      expect(patterns[0].pattern.test('https://example.com/not-udemy.vtt')).toBe(false);
    });

    it('extracts language from subtitles/{id}/{lang}/ path', () => {
      const patterns = handler.getPatterns();
      const url = new URL('https://cdna.udemycdn.com/subtitles/99999/en_US/file.vtt');
      expect(patterns[0].languageExtractor?.(url)).toBe('en-US');
    });
  });

  describe('extractAvailableTracks', () => {
    const apiUrl = 'https://www.udemy.com/api-2.0/lectures/4242/';

    it('preserves locale region in language (en_US vs en_GB)', () => {
      const body = JSON.stringify({
        asset: {
          captions: [
            { locale_id: 'en_US', title: 'English (US)', url: 'https://cdna.udemycdn.com/a.vtt', status: 1 },
            { locale_id: 'en_GB', title: 'English (UK)', url: 'https://cdna.udemycdn.com/b.vtt', status: 1 },
          ],
        },
      });
      const tracks = extractTracks(body, 'application/json', apiUrl);
      expect(tracks.map((t) => t.language).sort()).toEqual(['en-GB', 'en-US']);
    });

    it('maps en_US locale_id to en-US BCP-47', () => {
      const body = JSON.stringify({
        captions: [{ locale_id: 'en_US', url: 'https://cdna.udemycdn.com/x.vtt', status: 1 }],
      });
      const tracks = extractTracks(body, 'application/json', apiUrl);
      expect(tracks[0].language).toBe('en-US');
    });

    it('does not use data.results fallback', () => {
      const body = JSON.stringify({
        results: [{ locale_id: 'xx_XX', url: 'https://evil.vtt', status: 1 }],
        captions: [],
      });
      const tracks = extractTracks(body, 'application/json', apiUrl);
      expect(tracks).toHaveLength(0);
    });

    it('filters captions with status 0', () => {
      const body = JSON.stringify({
        captions: [
          { locale_id: 'en_US', url: 'https://a.vtt', status: 0 },
          { locale_id: 'de_DE', url: 'https://b.vtt', status: 1 },
        ],
      });
      const tracks = extractTracks(body, 'application/json', apiUrl);
      expect(tracks).toHaveLength(1);
      expect(tracks[0].language).toBe('de-DE');
    });

    it('sets isAutoGenerated for auto and auto-generated sources', () => {
      const body = JSON.stringify({
        captions: [
          { locale_id: 'en_US', url: 'https://a.vtt', status: 1, source: 'auto' },
          { locale_id: 'es_ES', url: 'https://b.vtt', status: 1, source: 'auto-generated' },
        ],
      });
      const tracks = extractTracks(body, 'application/json', apiUrl);
      expect(tracks.every((t) => t.isAutoGenerated)).toBe(true);
    });

    it('extracts videoId from lecture API URL', () => {
      const body = JSON.stringify({
        captions: [{ locale_id: 'en_US', url: 'https://a.vtt', status: 1 }],
      });
      const tracks = extractTracks(body, 'application/json', apiUrl);
      expect(tracks[0].videoId).toBe('4242');
    });

    it('returns empty array for malformed JSON', () => {
      const warn = vi.spyOn(console, 'warn').mockImplementation(() => {});
      expect(extractTracks('{', 'application/json', apiUrl)).toEqual([]);
      warn.mockRestore();
    });

    it('parses realistic api-2.0 lecture asset.captions fixture', () => {
      const body = JSON.stringify({
        asset: {
          captions: [
            {
              locale_id: 'en_US',
              title: 'English [Auto]',
              url: 'https://cdna.udemycdn.com/subtitles/12345/en_US/file.vtt',
              status: 1,
              source: 'auto-generated',
            },
          ],
        },
      });
      const tracks = extractTracks(body, 'application/json', apiUrl);
      expect(tracks).toHaveLength(1);
      expect(tracks[0].isAutoGenerated).toBe(true);
      expect(tracks[0].url).toContain('udemycdn.com');
    });
  });

  describe('transformResponse', () => {
    it('parses standard WebVTT', () => {
      const vtt = `WEBVTT

1
00:00:01.000 --> 00:00:04.000
Udemy subtitle line`;

      const cues = handler.transformResponse(vtt, 'text/vtt', 'https://cdna.udemycdn.com/subtitles/course.vtt');
      expect(cues).toHaveLength(1);
      expect(cues[0].text).toBe('Udemy subtitle line');
    });

    it('returns empty array for sprite metadata VTT', () => {
      const spriteVtt = `WEBVTT

1
00:00:01.000 --> 00:00:04.000
thumb-sprites.jpg#xywh=0,0,100,100`;

      const cues = handler.transformResponse(spriteVtt, 'text/vtt', 'https://cdna.udemycdn.com/subtitles/sprite.vtt');
      expect(cues).toHaveLength(0);
    });

    it('returns empty array for PNG sprite metadata', () => {
      const pngSpriteVtt = `WEBVTT

1
00:00:01.000 --> 00:00:04.000
thumbnail.png#xywh=10,20,200,150`;

      const cues = handler.transformResponse(pngSpriteVtt, 'text/vtt', 'https://cdna.udemycdn.com/subtitles/thumb.vtt');
      expect(cues).toHaveLength(0);
    });

    it('filters out sprite cues from mixed content', () => {
      const mixedVtt = `WEBVTT

1
00:00:01.000 --> 00:00:04.000
thumb-sprites.jpg#xywh=0,0,100,100

2
00:00:05.000 --> 00:00:08.000
Normal subtitle text`;

      const cues = handler.transformResponse(mixedVtt, 'text/vtt', 'https://cdna.udemycdn.com/subtitles/course.vtt');
      expect(cues).toHaveLength(1);
      expect(cues[0].text).toBe('Normal subtitle text');
    });

    it('keeps short subtitles ending in image extension without xywh', () => {
      const vtt = `WEBVTT

1
00:00:01.000 --> 00:00:04.000
See photo.png`;

      const cues = handler.transformResponse(vtt, 'text/vtt', 'https://cdna.udemycdn.com/subtitles/course.vtt');
      expect(cues).toHaveLength(1);
      expect(cues[0].text).toBe('See photo.png');
    });

    it('filters sprite cues with spaces in path only when xywh present', () => {
      const vtt = `WEBVTT

1
00:00:01.000 --> 00:00:04.000
my lecture slides.jpg`;

      const cues = handler.transformResponse(vtt, 'text/vtt', 'https://cdna.udemycdn.com/subtitles/course.vtt');
      expect(cues).toHaveLength(1);
      expect(cues[0].text).toBe('my lecture slides.jpg');
    });

    it('keeps long subtitles that mention image files', () => {
      const longSubtitleVtt = `WEBVTT

1
00:00:01.000 --> 00:00:04.000
In this lecture we will learn how to work with jpg and png files in your project`;

      const cues = handler.transformResponse(longSubtitleVtt, 'text/vtt', 'https://cdna.udemycdn.com/subtitles/course.vtt');
      expect(cues).toHaveLength(1);
      expect(cues[0].text).toBe('In this lecture we will learn how to work with jpg and png files in your project');
    });

    it('parses SRT via parseSubtitles', () => {
      const srt = `1
00:00:01,000 --> 00:00:04,000
Udemy SRT line`;

      const cues = handler.transformResponse(srt, 'application/x-subrip', 'https://cdna.udemycdn.com/subtitles/x.vtt');
      expect(cues).toHaveLength(1);
      expect(cues[0].text).toBe('Udemy SRT line');
    });
  });
});
