import { describe, it, expect, beforeEach, vi } from 'vitest';
import { YoukuHandler, youkuCodeToLanguage } from '@/inject/subtitleHandlers/youku';

describe('YoukuHandler', () => {
  let handler: YoukuHandler;

  beforeEach(() => {
    handler = new YoukuHandler();
    document.body.innerHTML = '';
  });

  it('has platform identifier', () => {
    expect(handler.platform).toBe('youku');
  });

  describe('detect', () => {
    // Canonical + subdomain hosts across the three Youku domains.
    it.each([
      ['youku.tv'],
      ['www.youku.tv'],
      ['foo.youku.tv'],
      ['youku.com'],
      ['www.youku.com'],
      ['v.youku.com'],
      ['m.youku.com'],
      ['bar.youku.com'],
    ])('detects %s', (host) => {
      vi.stubGlobal('location', { hostname: host });
      expect(handler.detect()).toBe(true);
    });

    // Spoofed / unrelated hosts must be rejected (anchored match).
    it.each([
      ['www.youtube.com'],
      ['notyouku.com'],
      ['fakeyouku.tv'],
      ['youku.evil.com'],
      ['youku.com.evil.com'],
    ])('rejects %s', (host) => {
      vi.stubGlobal('location', { hostname: host });
      expect(handler.detect()).toBe(false);
    });
  });

  describe('isWatchPage', () => {
    it.each([
      // youku.tv watch path: /v/v_show/id_*
      ['/v/v_show/id_XNjQ4MDkzODY2NA==.html'],
      // youku.com / m.youku.com watch path: /v_show/id_*
      ['/v_show/id_XNjQ4MDkzODY2NA==.html'],
      // no .html suffix
      ['/v_show/id_XNjQ4MDkzODY2NA=='],
    ])('returns true for watch path %s', (path) => {
      vi.stubGlobal('location', { hostname: 'v.youku.com', pathname: path });
      expect(handler.isWatchPage()).toBe(true);
    });

    it.each([
      ['/'],
      ['/v'],
      ['/search?q=test'],
      ['/v_show'],
      ['/list/showid'],
    ])('returns false for non-watch path %s', (path) => {
      vi.stubGlobal('location', { hostname: 'www.youku.com', pathname: path });
      expect(handler.isWatchPage()).toBe(false);
    });
  });

  describe('getPatterns', () => {
    it('returns empty array (no URL interception — DOM cue scraping only)', () => {
      expect(handler.getPatterns()).toEqual([]);
    });
  });

  describe('transformResponse', () => {
    it('returns empty array (never called for a DOM cue source)', () => {
      expect(handler.transformResponse('anything', 'text/vtt', 'https://v.youku.com/x')).toEqual([]);
    });
  });

  describe('youkuCodeToLanguage', () => {
    // All 11 documented Youku subtitle codes → BCP-47.
    it.each([
      ['CHS', 'zh-Hans'],
      ['default', 'zh-Hans'],
      ['CHT', 'zh-Hant'],
      ['cht', 'zh-Hant'],
      ['EN', 'en'],
      ['en', 'en'],
      ['KR', 'ko'],
      ['kr', 'ko'],
      ['ES', 'es'],
      ['es', 'es'],
      ['PO', 'pt'],
      ['po', 'pt'],
      ['TH', 'th'],
      ['th', 'th'],
      ['AR', 'ar'],
      ['ar', 'ar'],
      ['ID', 'id'],
      ['id', 'id'],
      ['VI', 'vi'],
      ['vi', 'vi'],
      ['MS', 'ms'],
      ['ms', 'ms'],
    ])('maps %s → %s', (code, lang) => {
      expect(youkuCodeToLanguage(code)).toBe(lang);
    });

    it('falls back to the lowercased code for unknown values', () => {
      expect(youkuCodeToLanguage('ZZ')).toBe('zz');
      expect(youkuCodeToLanguage('xx')).toBe('xx');
    });

    it('returns empty string for empty input', () => {
      expect(youkuCodeToLanguage('')).toBe('');
    });
  });

  describe('extractAvailableTracks', () => {
    it('parses the subtitle picker into tracks with mapped languages', () => {
      vi.stubGlobal('location', {
        hostname: 'v.youku.com',
        pathname: '/v_show/id_XNjQ4MDkzODY2NA==.html',
      });
      document.body.innerHTML = `
        <div com="subtitle">
          <ul>
            <li data-val="default">简体中文</li>
            <li data-val="cht">繁體中文</li>
            <li data-val="en">English</li>
            <li data-val="kr">한국어</li>
            <li data-val="po">Português</li>
          </ul>
        </div>
      `;

      const tracks = handler.extractAvailableTracks('', 'application/json', '');

      expect(tracks).toHaveLength(5);
      expect(tracks[0]).toMatchObject({
        platform: 'youku',
        url: undefined,
        isAutoGenerated: false,
        language: 'zh-Hans',
        label: '简体中文',
        videoId: 'XNjQ4MDkzODY2NA==',
      });
      const korean = tracks.find((t) => t.language === 'ko');
      expect(korean).toBeDefined();
      expect(korean?.label).toBe('한국어');
      const portuguese = tracks.find((t) => t.language === 'pt');
      expect(portuguese).toBeDefined();
    });

    it('skips picker items without a data-val', () => {
      document.body.innerHTML = `
        <div com="subtitle">
          <ul>
            <li>简体中文</li>
            <li data-val="en">English</li>
          </ul>
        </div>
      `;
      const tracks = handler.extractAvailableTracks('', 'application/json', '');
      expect(tracks).toHaveLength(1);
      expect(tracks[0].language).toBe('en');
    });

    it('returns empty array when the picker is absent', () => {
      document.body.innerHTML = '';
      expect(handler.extractAvailableTracks('', 'application/json', '')).toEqual([]);
    });
  });

  describe('getDomCueSource', () => {
    it('targets the #subtitle SVG caption container and the stable player root', () => {
      const source = handler.getDomCueSource();
      // Cue text lives inside <div id="subtitle"><svg><text><tspan>…</tspan></text>
      expect(source.cueSelector).toBe('#subtitle');
      // The native caption window we hide while the overlay is active.
      expect(source.captionWindowSelector).toBe('#subtitle');
      // Observe the stable player container (survives inner SVG replacement).
      expect(source.observeRootSelector).toBe('#ykPlayer');
    });

    it('declares captionHideMethod: visibility (cue source == hide target)', () => {
      // #subtitle is BOTH the cue source AND the hide target. display:none
      // would empty it (the KUI player stops rendering into a hidden node),
      // starving the scraper of cues. visibility:hidden keeps it populated.
      const source = handler.getDomCueSource();
      expect(source.captionHideMethod).toBe('visibility');
    });

    it('readActiveLanguage maps the active picker item to a BCP-47 code', () => {
      document.body.innerHTML = `
        <div com="subtitle">
          <ul>
            <li data-val="default">简体中文</li>
            <li data-val="en" class="current">English</li>
          </ul>
        </div>
      `;
      expect(handler.getDomCueSource().readActiveLanguage()).toBe('en');
    });

    it('readActiveLanguage detects aria-selected="true" as active', () => {
      document.body.innerHTML = `
        <div com="subtitle">
          <ul>
            <li data-val="kr">한국어</li>
            <li data-val="cht" aria-selected="true">繁體中文</li>
          </ul>
        </div>
      `;
      expect(handler.getDomCueSource().readActiveLanguage()).toBe('zh-Hant');
    });

    it('readActiveLanguage returns empty string when nothing is active', () => {
      document.body.innerHTML = `
        <div com="subtitle">
          <ul>
            <li data-val="en">English</li>
            <li data-val="kr">한국어</li>
          </ul>
        </div>
      `;
      expect(handler.getDomCueSource().readActiveLanguage()).toBe('');
    });

    it('readActiveLanguage returns empty string when the picker is absent', () => {
      document.body.innerHTML = '';
      expect(handler.getDomCueSource().readActiveLanguage()).toBe('');
    });

    it('videoIdExtractor reads the id from a v_show watch path', () => {
      vi.stubGlobal('location', {
        hostname: 'v.youku.com',
        pathname: '/v_show/id_XNjQ4MDkzODY2NA==.html',
      });
      expect(handler.getDomCueSource().videoIdExtractor?.()).toBe('XNjQ4MDkzODY2NA==');
    });

    it('videoIdExtractor reads the id from a youku.tv watch path', () => {
      vi.stubGlobal('location', {
        hostname: 'www.youku.tv',
        pathname: '/v/v_show/id_XNjQ4MDkzODY2NA==.html',
      });
      expect(handler.getDomCueSource().videoIdExtractor?.()).toBe('XNjQ4MDkzODY2NA==');
    });
  });
});
