import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { YouTubeHandler } from '@/inject/subtitleHandlers/youtube';

describe('YouTubeHandler', () => {
  let handler: YouTubeHandler;
  const originalHostname = window.location.hostname;
  const originalPathname = window.location.pathname;

  beforeEach(() => {
    handler = new YouTubeHandler();
  });

  afterEach(() => {
    Object.defineProperty(window, 'location', {
      value: { hostname: originalHostname, pathname: originalPathname },
      writable: true,
    });
  });

  const setLocation = (hostname: string, pathname: string = '/') => {
    Object.defineProperty(window, 'location', {
      value: { hostname, pathname },
      writable: true,
    });
  };

  it('detects hosts, watch page, timedtext/metadata patterns, language extract', () => {
    setLocation('www.youtube.com');
    expect(handler.detect()).toBe(true);
    setLocation('m.youtube.com');
    expect(handler.detect()).toBe(true);
    setLocation('www.example.com');
    expect(handler.detect()).toBe(false);

    setLocation('www.youtube.com', '/watch');
    expect(handler.isWatchPage()).toBe(true);
    setLocation('www.youtube.com', '/feed/subscriptions');
    expect(handler.isWatchPage()).toBe(false);
    setLocation('www.youtube.com', '/embed/abc123');
    expect(handler.isWatchPage()).toBe(false);

    const patterns = handler.getPatterns();
    expect(patterns).toHaveLength(1);
    expect(patterns[0].pattern.test('https://www.youtube.com/api/timedtext?v=abc')).toBe(true);
    expect(patterns[0].pattern.test('https://example.com/api/timedtext')).toBe(false);
    const extractor = patterns[0].languageExtractor;
    expect(extractor).toBeTypeOf('function');
    if (!extractor) throw new Error('expected languageExtractor');
    expect(extractor(new URL('https://www.youtube.com/api/timedtext?lang=en&tlang=vi'))).toBe('vi');
    expect(extractor(new URL('https://www.youtube.com/api/timedtext?lang=en'))).toBe('en');
    expect(extractor(new URL('https://www.youtube.com/api/timedtext?v=abc'))).toBe('');

    const meta = handler.getMetadataPatterns();
    expect(meta[0].pattern.test('https://www.youtube.com/youtubei/v1/player')).toBe(true);
    expect(meta[0].pattern.test('https://www.youtube.com/api/timedtext')).toBe(false);
  });

  it('extracts caption tracks including ASR, filters empty, handles invalid', () => {
    const playerApiResponse = JSON.stringify({
      captions: {
        playerCaptionsTracklistRenderer: {
          captionTracks: [
            {
              languageCode: 'en',
              name: { simpleText: 'English' },
              baseUrl: 'https://www.youtube.com/api/timedtext?lang=en',
            },
            {
              languageCode: 'vi',
              name: { simpleText: 'Vietnamese' },
              baseUrl: 'https://www.youtube.com/api/timedtext?lang=vi',
            },
          ],
        },
      },
      videoDetails: { videoId: 'abc123' },
    });

    const tracks = handler.extractAvailableTracks(playerApiResponse);
    expect(tracks).toHaveLength(2);
    expect(tracks[0]).toMatchObject({
      language: 'en',
      label: 'English',
      platform: 'youtube',
      videoId: 'abc123',
      isAutoGenerated: false,
    });

    const asr = handler.extractAvailableTracks(
      JSON.stringify({
        captions: {
          playerCaptionsTracklistRenderer: {
            captionTracks: [
              {
                languageCode: 'en',
                name: { simpleText: 'English (auto-generated)' },
                kind: 'asr',
                baseUrl: 'https://www.youtube.com/api/timedtext?lang=en',
              },
            ],
          },
        },
        videoDetails: { videoId: 'xyz789' },
      }),
    );
    expect(asr[0].isAutoGenerated).toBe(true);

    const withEmpty = handler.extractAvailableTracks(
      JSON.stringify({
        captions: {
          playerCaptionsTracklistRenderer: {
            captionTracks: [
              { languageCode: '', name: { simpleText: 'Unknown' } },
              { languageCode: 'en', name: { simpleText: 'English' } },
            ],
          },
        },
        videoDetails: { videoId: 'abc' },
      }),
    );
    expect(withEmpty).toHaveLength(1);

    expect(handler.extractAvailableTracks('not valid json')).toEqual([]);
    expect(
      handler.extractAvailableTracks(JSON.stringify({ videoDetails: { videoId: 'abc' } })),
    ).toEqual([]);
    const labelFallback = handler.extractAvailableTracks(
      JSON.stringify({
        captions: {
          playerCaptionsTracklistRenderer: {
            captionTracks: [{ languageCode: 'fr', baseUrl: 'https://example.com/fr' }],
          },
        },
      }),
    );
    expect(labelFallback[0].label).toBe('fr');
    expect(labelFallback[0].videoId).toBeUndefined();
  });

  it('parses srv3 XML and json3, filters empties, rejects unparseable', () => {
    const srv3Xml = `<?xml version="1.0" encoding="utf-8" ?>
<transcript>
  <text start="1.5" dur="2.0">Hello world</text>
  <text start="4.0" dur="3.0">Second cue</text>
</transcript>`;

    const json3Body = JSON.stringify({
      events: [
        {
          tStartMs: 1000,
          dDurationMs: 2000,
          segs: [{ utf8: 'Hello ' }, { utf8: 'world' }],
        },
        {
          tStartMs: 4000,
          dDurationMs: 3000,
          segs: [{ utf8: 'Second cue' }],
        },
      ],
    });

    const cues = handler.transformResponse(
      srv3Xml,
      'text/xml',
      'https://www.youtube.com/api/timedtext?lang=en',
    );
    expect(cues).toHaveLength(2);
    expect(cues[0]).toMatchObject({ startTime: 1.5, endTime: 3.5, text: 'Hello world' });

    const withEmpty = `<?xml version="1.0" encoding="utf-8" ?>
<transcript>
  <text start="0" dur="1.0"></text>
  <text start="1.0" dur="2.0">Valid cue</text>
</transcript>`;
    expect(
      handler.transformResponse(
        withEmpty,
        'text/xml',
        'https://www.youtube.com/api/timedtext?lang=en',
      ),
    ).toHaveLength(1);

    const viaFmt = handler.transformResponse(
      json3Body,
      'text/plain',
      'https://www.youtube.com/api/timedtext?fmt=json3&lang=en',
    );
    expect(viaFmt).toHaveLength(2);
    expect(viaFmt[0].text).toBe('Hello world');

    const viaCt = handler.transformResponse(
      json3Body,
      'application/json; charset=utf-8',
      'https://www.youtube.com/api/timedtext?lang=en',
    );
    expect(viaCt).toHaveLength(2);

    const filtered = handler.transformResponse(
      JSON.stringify({
        events: [
          { tStartMs: 0, dDurationMs: 1000 },
          { tStartMs: 0, dDurationMs: 1000, segs: [{ utf8: '\n' }] },
          { tStartMs: 1000, dDurationMs: 1000, segs: [{ utf8: 'Valid' }] },
        ],
      }),
      'application/json',
      'https://www.youtube.com/api/timedtext?fmt=json3',
    );
    expect(filtered).toHaveLength(1);
    expect(filtered[0].text).toBe('Valid');

    expect(handler.transformResponse('', 'text/plain', 'https://example.com')).toEqual([]);
    expect(
      handler.transformResponse('not valid content', 'text/plain', 'https://example.com'),
    ).toEqual([]);
  });

  it('parseWordEvents extracts ASR word timings; empty for non-JSON3', () => {
    const body = JSON.stringify({
      events: [
        {
          tStartMs: 1000,
          dDurationMs: 2000,
          segs: [
            { utf8: 'Auto ', tOffsetMs: 0 },
            { utf8: 'generated ', tOffsetMs: 400 },
            { utf8: 'fragment', tOffsetMs: 900 },
          ],
        },
        {
          tStartMs: 3500,
          dDurationMs: 1000,
          segs: [{ utf8: '\n' }, { utf8: 'Next', tOffsetMs: 0 }],
        },
      ],
    });
    const words = handler.parseWordEvents(body);
    expect(words.length).toBe(4);
    expect(words[0]).toMatchObject({ text: 'Auto', startMs: 1000 });
    expect(words[1].startMs).toBe(1400);
    expect(words[3]).toMatchObject({ text: 'Next', startMs: 3500 });

    expect(handler.parseWordEvents('')).toEqual([]);
    expect(handler.parseWordEvents('<transcript></transcript>')).toEqual([]);
  });
});
